In [141]:
import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib.pyplot as plt

In [142]:
df = pd.read_json('/Users/butler/Documents/springboard_bootcamp/Classification_of_Indian_clothing_images/data/raw/test_data.json', lines=True)

In [143]:
df.head()

,image_url,image_path,brand,product_title,class_label,color
0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN
1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN
2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN
3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN
4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN

In [144]:
df.tail()

,image_url,image_path,brand,product_title,class_label,color
7495,https://rukminim1.flixcart.com/image/309/371/k...,images/test/7495.jpeg,aaliya fashion,Women Embroidered Rayon Anarkali Kurta,women_kurta,Purple
7496,https://m.media-amazon.com/images/I/71xJFbz+uV...,images/test/7496.jpeg,AnjuShree Choice,Women's Rayon & Viscose Regular Stitched Kurta,women_kurta,NaN
7497,https://m.media-amazon.com/images/I/71CawDGew+...,images/test/7497.jpeg,W for Woman,Women's cotton straight Kurta,women_kurta,NaN
7498,https://m.media-amazon.com/images/I/61VBgoJQAt...,images/test/7498.jpeg,Vaamsi,Crepe Printed Kurti (VPK1805_Purple_Free Size),women_kurta,NaN
7499,https://m.media-amazon.com/images/I/612gggywBm...,images/test/7499.jpeg,Vbuyz,Women's Rayon Regular Kurta,women_kurta,NaN

In [145]:
df.shape

(7500, 6)

In [146]:
df.class_label.unique()

array(['saree', 'blouse', 'dhoti_pants', 'dupattas', 'gowns', 'kurta_men',
       'leggings_and_salwars', 'lehenga', 'mojaris_men', 'mojaris_women',
       'nehru_jackets', 'palazzos', 'petticoats', 'sherwanis',
       'women_kurta'], dtype=object)

In [147]:
df_revised = df.copy()

In [148]:
df_revised.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   image_url      7500 non-null   object
 1   image_path     7500 non-null   object
 2   brand          7500 non-null   object
 3   product_title  7500 non-null   object
 4   class_label    7500 non-null   object
 5   color          905 non-null    object
dtypes: object(6)
memory usage: 351.7+ KB

In [149]:
df_revised = df_revised.reset_index(names='number')

In [150]:
df_revised.tail()

,number,image_url,image_path,brand,product_title,class_label,color
7495,7495,https://rukminim1.flixcart.com/image/309/371/k...,images/test/7495.jpeg,aaliya fashion,Women Embroidered Rayon Anarkali Kurta,women_kurta,Purple
7496,7496,https://m.media-amazon.com/images/I/71xJFbz+uV...,images/test/7496.jpeg,AnjuShree Choice,Women's Rayon & Viscose Regular Stitched Kurta,women_kurta,NaN
7497,7497,https://m.media-amazon.com/images/I/71CawDGew+...,images/test/7497.jpeg,W for Woman,Women's cotton straight Kurta,women_kurta,NaN
7498,7498,https://m.media-amazon.com/images/I/61VBgoJQAt...,images/test/7498.jpeg,Vaamsi,Crepe Printed Kurti (VPK1805_Purple_Free Size),women_kurta,NaN
7499,7499,https://m.media-amazon.com/images/I/612gggywBm...,images/test/7499.jpeg,Vbuyz,Women's Rayon Regular Kurta,women_kurta,NaN

In [151]:
df_revised.tail()

,number,image_url,image_path,brand,product_title,class_label,color
7495,7495,https://rukminim1.flixcart.com/image/309/371/k...,images/test/7495.jpeg,aaliya fashion,Women Embroidered Rayon Anarkali Kurta,women_kurta,Purple
7496,7496,https://m.media-amazon.com/images/I/71xJFbz+uV...,images/test/7496.jpeg,AnjuShree Choice,Women's Rayon & Viscose Regular Stitched Kurta,women_kurta,NaN
7497,7497,https://m.media-amazon.com/images/I/71CawDGew+...,images/test/7497.jpeg,W for Woman,Women's cotton straight Kurta,women_kurta,NaN
7498,7498,https://m.media-amazon.com/images/I/61VBgoJQAt...,images/test/7498.jpeg,Vaamsi,Crepe Printed Kurti (VPK1805_Purple_Free Size),women_kurta,NaN
7499,7499,https://m.media-amazon.com/images/I/612gggywBm...,images/test/7499.jpeg,Vbuyz,Women's Rayon Regular Kurta,women_kurta,NaN

In [152]:
columns = ['kurta', 'women', 'men', 'dhoti', 'saree', 'sherwani', 'palazzo', 
           'mojari', 'nehru', 'legging', 'salwar', 'petticoat', 'blouse', 
           'dupatta', 'gown','lehenga']

In [153]:
for column in columns:
    df_revised[str(column)] = df_revised.product_title.str.contains(str(column), flags=re.IGNORECASE)

In [154]:
df_revised.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,women,men,...,palazzo,mojari,nehru,legging,salwar,petticoat,blouse,dupatta,gown,lehenga
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,True,True,...,False,False,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN,False,True,True,...,False,False,False,False,False,False,True,False,False,False
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN,False,True,True,...,False,False,False,False,False,False,True,False,False,False
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN,False,True,True,...,False,False,False,False,False,False,True,False,False,False
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN,False,True,True,...,False,False,False,False,False,False,True,False,False,False

In [155]:
df_revised_men = df_revised[df_revised.men == True]
df_revised_men.shape

(5466, 23)

In [156]:
df_revised_men.loc[0]

number                                                           0
image_url        https://m.media-amazon.com/images/I/71NZQ-aaAS...
image_path                                      images/test/0.jpeg
brand                                      TANTUJA BENGAL HANDLOOM
product_title    (A Govt. of West Bengal Enterprises) Handloom ...
class_label                                                  saree
color                                                          NaN
kurta                                                        False
women                                                         True
men                                                           True
dhoti                                                        False
saree                                                        False
sherwani                                                     False
palazzo                                                      False
mojari                                                       False
nehru                                                        False
legging                                                      False
salwar                                                       False
petticoat                                                    False
blouse                                                       False
dupatta                                                      False
gown                                                         False
lehenga                                                      False
Name: 0, dtype: object

In [157]:
df_revised.columns

Index(['number', 'image_url', 'image_path', 'brand', 'product_title',
       'class_label', 'color', 'kurta', 'women', 'men', 'dhoti', 'saree',
       'sherwani', 'palazzo', 'mojari', 'nehru', 'legging', 'salwar',
       'petticoat', 'blouse', 'dupatta', 'gown', 'lehenga'],
      dtype='object')

In [158]:
con1 = (df_revised['men'] == True) 
con2 = (df_revised['women'] == True)


df_revised.loc[con1 & con2, 'men'] = False

In [159]:
df_revised_men = df_revised[df_revised.men == True]

In [160]:
df_revised_men.shape

(1581, 23)

In [161]:
df_revised_men.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,women,men,...,palazzo,mojari,nehru,legging,salwar,petticoat,blouse,dupatta,gown,lehenga
645,645,https://m.media-amazon.com/images/I/81Q3XClKdX...,images/test/645.jpeg,ARUNA,KULLU Jacket Nehru Jacket Reversal Both Side U...,blouse,NaN,False,False,True,...,False,False,True,False,False,False,False,False,False,False
1000,1000,https://rukminim1.flixcart.com/image/309/371/j...,images/test/1000.jpeg,N/A,ARYA Welcro Solid Men Dhoti,dhoti_pants,N/A,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1005,1005,https://m.media-amazon.com/images/I/61z0+oMvE8...,images/test/1005.jpeg,Larwa,Men's Silk Solid Dhoti,dhoti_pants,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1008,1008,https://rukminim1.flixcart.com/image/309/371/k...,images/test/1008.jpeg,N/A,GOLFER Men Stylish Ethnic Dupion Dhoti (Maroon...,dhoti_pants,N/A,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1009,1009,https://rukminim1.flixcart.com/image/309/371/j...,images/test/1009.jpeg,N/A,GREEN TEE Men Dhoti,dhoti_pants,N/A,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [162]:
df_revised.iloc[2,4]

"Women's Georgette Net Embroidered Saree with Blouse Piece (Black)"

In [163]:
df_revised.iloc[1,4]

"Women's Silk Saree With Blouse Piece"

In [164]:
df_revised.loc[1000]

number                                                        1000
image_url        https://rukminim1.flixcart.com/image/309/371/j...
image_path                                   images/test/1000.jpeg
brand                                                          N/A
product_title                          ARYA Welcro Solid Men Dhoti
class_label                                            dhoti_pants
color                                                          N/A
kurta                                                        False
women                                                        False
men                                                           True
dhoti                                                         True
saree                                                        False
sherwani                                                     False
palazzo                                                      False
mojari                                                       False
nehru                                                        False
legging                                                      False
salwar                                                       False
petticoat                                                    False
blouse                                                       False
dupatta                                                      False
gown                                                         False
lehenga                                                      False
Name: 1000, dtype: object

In [165]:
df_revised.iloc[1000,4]

'ARYA Welcro Solid Men Dhoti'

In [166]:
df_revised['women_kurta'] = [False]* 7500

In [167]:
df_revised['kurta_men'] = [False]* 7500

In [168]:
df_revised.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,women,men,...,nehru,legging,salwar,petticoat,blouse,dupatta,gown,lehenga,women_kurta,kurta_men
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN,False,True,False,...,False,False,False,False,True,False,False,False,False,False
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN,False,True,False,...,False,False,False,False,True,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN,False,True,False,...,False,False,False,False,True,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN,False,True,False,...,False,False,False,False,True,False,False,False,False,False

In [169]:
con1 = (df_revised['kurta'] == True) 
con2 = (df_revised['women'] == True)


df_revised.loc[con1 & con2, 'women_kurta'] = True

In [170]:
df = df_revised[df_revised.women_kurta == True]

In [171]:
df.shape

(489, 25)

In [172]:
con1 = (df_revised['kurta'] == True) 
con2 = (df_revised['men'] == True)


df_revised.loc[con1 & con2, 'kurta_men'] = True

In [173]:
df_revised['mojaris_men'] = [False]*7500
df_revised['mojaris_women'] = [False]*7500
df_revised['leggings_and_salwars'] = [False]*7500

In [174]:
con1 = (df_revised['mojari'] == True) 
con2 = (df_revised['women'] == True)


df_revised.loc[con1 & con2, 'mojaris_women'] = True

In [175]:
con1 = (df_revised['mojari'] == True) 
con2 = (df_revised['men'] == True)


df_revised.loc[con1 & con2, 'mojaris_men'] = True

In [176]:
con1 = (df_revised['legging'] == True) 
con2 = (df_revised['salwar'] == True)


df_revised.loc[con1 | con2, 'leggings_and_salwars'] = True

In [177]:
df_revised.leggings_and_salwars.nunique()

2

In [178]:
df_revised.drop(['men', 'women', 'legging','salwar','mojari'], axis=1, inplace=True)

In [179]:
df_revised.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti,saree,...,petticoat,blouse,dupatta,gown,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN,False,False,True,...,False,True,False,False,False,False,False,False,False,False
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN,False,False,True,...,False,True,False,False,False,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN,False,False,True,...,False,True,False,False,False,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN,False,False,True,...,False,True,False,False,False,False,False,False,False,False

In [180]:
con1 = (df_revised['class_label'] == 'saree') 
con2 = (df_revised['blouse'] == True)


df_revised.loc[con1 & con2, 'blouse'] = False

In [181]:
df_revised.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti,saree,...,petticoat,blouse,dupatta,gown,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [182]:
df_revised.loc[1]

number                                                                  1
image_url               https://m.media-amazon.com/images/I/81aQmbWsG7...
image_path                                             images/test/1.jpeg
brand                                                          Trilok Fab
product_title                        Women's Silk Saree With Blouse Piece
class_label                                                         saree
color                                                                 NaN
kurta                                                               False
dhoti                                                               False
saree                                                                True
sherwani                                                            False
palazzo                                                             False
nehru                                                               False
petticoat                                                           False
blouse                                                              False
dupatta                                                             False
gown                                                                False
lehenga                                                             False
women_kurta                                                         False
kurta_men                                                           False
mojaris_men                                                         False
mojaris_women                                                       False
leggings_and_salwars                                                False
Name: 1, dtype: object

In [183]:
dfk = df_revised[df_revised.kurta == True]

In [184]:
dfk1 = dfk[dfk.kurta_men == False]

In [185]:
dfk2 = dfk1[dfk1.women_kurta == False]

In [186]:
dfk2.shape

(63, 23)

In [187]:
dfk2m = dfk2[dfk2.class_label == 'kurta_men']

In [188]:
dfk2w = dfk2[dfk2.class_label == 'women_kurta']

In [189]:
dfk2n = dfk2[dfk2.class_label != 'kurta_men']

In [190]:
dfk2n = dfk2n[dfk2.class_label != 'women_kurta']

/var/folders/nv/lggm200n09vgfy5n8_6lcz6c0000gn/T/ipykernel_17168/1037558784.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  dfk2n = dfk2n[dfk2.class_label != 'women_kurta']

In [191]:
dfk2n.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti,saree,...,petticoat,blouse,dupatta,gown,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
1181,1181,https://m.media-amazon.com/images/I/71Hmlej5cD...,images/test/1181.jpeg,HUZUR,Dupion Silk Full Sleeve Long Kurta Blended Dho...,dhoti_pants,NaN,True,True,False,...,False,False,False,False,False,False,False,False,False,False
1222,1222,https://m.media-amazon.com/images/I/61dBKxehGi...,images/test/1222.jpeg,VASTRAMAY,Baap Beta Maroon Kurta and Dhoti Pant Set (Man...,dhoti_pants,NaN,True,True,False,...,False,False,False,False,False,False,False,False,False,False
1278,1278,https://m.media-amazon.com/images/I/61sMYTsq6C...,images/test/1278.jpeg,KANGLI,Rayon Girl's Full Stitched Straight Combo Kurt...,dhoti_pants,NaN,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1335,1335,https://m.media-amazon.com/images/I/61EXPqaFUs...,images/test/1335.jpeg,TAU-G,Dupion Silk Full Sleeve Long Kurta Blended Dho...,dhoti_pants,NaN,True,True,False,...,False,False,False,False,False,False,False,False,False,False
1379,1379,https://m.media-amazon.com/images/I/81OSmVR81p...,images/test/1379.jpeg,Raoshmi Kapur Designs,Black Chanderi Silk Kurta with organza hand wo...,dhoti_pants,NaN,True,True,False,...,False,False,True,False,False,False,False,False,False,False

In [192]:
dfk2n.shape

(24, 23)

In [193]:
df_revised.iloc[6948, 4]

'Embroidered Collar Art Silk Sherwani in Purple'

In [194]:
df_revised.columns

Index(['number', 'image_url', 'image_path', 'brand', 'product_title',
       'class_label', 'color', 'kurta', 'dhoti', 'saree', 'sherwani',
       'palazzo', 'nehru', 'petticoat', 'blouse', 'dupatta', 'gown', 'lehenga',
       'women_kurta', 'kurta_men', 'mojaris_men', 'mojaris_women',
       'leggings_and_salwars'],
      dtype='object')

In [195]:
df_revised.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti,saree,...,petticoat,blouse,dupatta,gown,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [196]:
df_revised = df_revised.rename({'dhoti':'dhoti_pants', 'sherwani':'sherwanis', 'palazzo':'palazzos', 
             'nehru':'nehru_jackets', 'petticoat':'petticoats', 'dupatta':'dupattas', 
             'gown':'gowns'},axis=1)
df_revised.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [199]:
columns = ['dhoti_pants', 'saree', 'sherwanis', 'palazzos', 'nehru_jackets', 'petticoats',
           'blouse','dupattas', 'gowns', 'lehenga', 'women_kurta', 'kurta_men', 
           'mojaris_men', 'mojaris_women', 'leggings_and_salwars']

for column in columns:
    c1 = (df_revised[str(column)] == True)
    c2 = (df_revised['class_label'] == str(column))
    df_revised.loc[c1 & c2, str(column)] = False

df_revised.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [200]:
def func(x):
    if x == True:
        return str(column)
    else:
        return 0

for column in columns:
    df_revised[str(column)] = df_revised[str(column)].apply(lambda x: func(x))

In [125]:
df_revised.to_csv('/Users/butler/Downloads/df_revised.csv')

In [126]:
#dfw = dfvr[dfvr.class_label == 'women_kurta']

In [201]:
df_revised.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,0

In [202]:
df_revised.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
7495,7495,https://rukminim1.flixcart.com/image/309/371/k...,images/test/7495.jpeg,aaliya fashion,Women Embroidered Rayon Anarkali Kurta,women_kurta,Purple,True,0,0,...,0,0,0,0,0,0,0,0,0,0
7496,7496,https://m.media-amazon.com/images/I/71xJFbz+uV...,images/test/7496.jpeg,AnjuShree Choice,Women's Rayon & Viscose Regular Stitched Kurta,women_kurta,NaN,True,0,0,...,0,0,0,0,0,0,0,0,0,0
7497,7497,https://m.media-amazon.com/images/I/71CawDGew+...,images/test/7497.jpeg,W for Woman,Women's cotton straight Kurta,women_kurta,NaN,True,0,0,...,0,0,0,0,0,0,0,0,0,0
7498,7498,https://m.media-amazon.com/images/I/61VBgoJQAt...,images/test/7498.jpeg,Vaamsi,Crepe Printed Kurti (VPK1805_Purple_Free Size),women_kurta,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,0
7499,7499,https://m.media-amazon.com/images/I/612gggywBm...,images/test/7499.jpeg,Vbuyz,Women's Rayon Regular Kurta,women_kurta,NaN,True,0,0,...,0,0,0,0,0,0,0,0,0,0

In [212]:
c1 = (df_revised.class_label == 'women_kurta')
c2 = (df_revised.class_label == 'kurta_men')
c3 = (df_revised.kurta == True)

df_revised.loc[c3 & (c1 | c2), 'kurta'] = 0

In [213]:
c1 = (df_revised.class_label != 'women_kurta')
c2 = (df_revised.class_label != 'kurta_men')
c3 = (df_revised.kurta == True)
df_revised.loc[c3 & c1 & c2, 'kurta'] = 'kurta'

In [214]:
df_revised.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
7495,7495,https://rukminim1.flixcart.com/image/309/371/k...,images/test/7495.jpeg,aaliya fashion,Women Embroidered Rayon Anarkali Kurta,women_kurta,Purple,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7496,7496,https://m.media-amazon.com/images/I/71xJFbz+uV...,images/test/7496.jpeg,AnjuShree Choice,Women's Rayon & Viscose Regular Stitched Kurta,women_kurta,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7497,7497,https://m.media-amazon.com/images/I/71CawDGew+...,images/test/7497.jpeg,W for Woman,Women's cotton straight Kurta,women_kurta,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7498,7498,https://m.media-amazon.com/images/I/61VBgoJQAt...,images/test/7498.jpeg,Vaamsi,Crepe Printed Kurti (VPK1805_Purple_Free Size),women_kurta,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,0
7499,7499,https://m.media-amazon.com/images/I/612gggywBm...,images/test/7499.jpeg,Vbuyz,Women's Rayon Regular Kurta,women_kurta,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [1220]:
df_revised.iloc[7498,4]

'Crepe Printed Kurti (VPK1805_Purple_Free Size)'

In [1221]:
df_revised.iloc[1001,4]

"Women's Regular Fit Patiala Pant"

In [1222]:
df_revised.iloc[1001]

number                                                               1001
image_url               https://m.media-amazon.com/images/I/41P8Dmis0p...
image_path                                          images/test/1001.jpeg
brand                                                  Sri Belha Fashions
product_title                            Women's Regular Fit Patiala Pant
class_label                                                   dhoti_pants
color                                                                 NaN
kurta                                                               False
dhoti_pants                                                             0
saree                                                                   0
sherwanis                                                               0
palazzos                                                                0
nehru_jackets                                                           0
petticoats                                                              0
blouse                                                                  0
dupattas                                                                0
gowns                                                                   0
lehenga                                                                 0
women_kurta                                                             0
kurta_men                                                               0
mojaris_men                                                             0
mojaris_women                                                           0
leggings_and_salwars                                                    0
Name: 1001, dtype: object

In [1223]:
df_revised.columns

Index(['number', 'image_url', 'image_path', 'brand', 'product_title',
       'class_label', 'color', 'kurta', 'dhoti_pants', 'saree', 'sherwanis',
       'palazzos', 'nehru_jackets', 'petticoats', 'blouse', 'dupattas',
       'gowns', 'lehenga', 'women_kurta', 'kurta_men', 'mojaris_men',
       'mojaris_women', 'leggings_and_salwars'],
      dtype='object')

In [1224]:
c1 = (dfr.saree == 0)
c2 = (dfr.dhoti_pants == 0)
c3 = (dfr.sherwanis == 0)
c4 = (dfr.palazzos == 0)
c5 = (dfr.nehru_jackets == 0)
c6 = (dfr.petticoats == 0)
c7 = (dfr.blouse == 0)
c8 = (dfr.dupattas == 0)
c9 = (dfr.gowns == 0)
c10 = (dfr.lehenga == 0)
c11 = (dfr.women_kurta == 0)
c12 = (dfr.kurta_men == 0)
c13 = (dfr.leggings_and_salwars == 0)
c14 = (dfr.mojaris_men == 0)
c15 = (dfr.mojaris_women == 0)


dfr.loc[c1 & c2 & c3 & c4 & c5 & c6 & c7 & c8 & c9 & c10 & c11 & c12 & c13 & c14 & c15,'none'] = 1

In [1225]:
df_none = dfr[dfr.none == 1]

In [1226]:
df_none.shape

(1914, 24)

In [1227]:
df_none.class_label.unique()

array(['saree', 'blouse', 'dhoti_pants', 'dupattas', 'gowns', 'kurta_men',
       'leggings_and_salwars', 'lehenga', 'mojaris_men', 'mojaris_women',
       'nehru_jackets', 'palazzos', 'petticoats', 'sherwanis',
       'women_kurta'], dtype=object)

In [1228]:
df_none.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
124,124,https://m.media-amazon.com/images/I/91B5uXeY0v...,images/test/124.jpeg,JISB,Women's Stitched Readymade Tissue blouse with ...,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
131,131,https://m.media-amazon.com/images/I/71l8qd8uV5...,images/test/131.jpeg,XAYA,Women's Banarasi Silk Sadi with Unstitched Blo...,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
140,140,https://m.media-amazon.com/images/I/81yZdcXtjb...,images/test/140.jpeg,Anjaneya Sarees,Banarasi Kanjivaram Silk Sari With Blouse,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
271,271,https://m.media-amazon.com/images/I/81ZZKa6Go6...,images/test/271.jpeg,T.J. SAREES,Tant Jamdani Handloom Pure Cotton Saees for Wo...,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1229]:
df_none.loc[0]

number                                                                  0
image_url               https://m.media-amazon.com/images/I/71NZQ-aaAS...
image_path                                             images/test/0.jpeg
brand                                             TANTUJA BENGAL HANDLOOM
product_title           (A Govt. of West Bengal Enterprises) Handloom ...
class_label                                                         saree
color                                                                 NaN
kurta                                                               False
dhoti_pants                                                             0
saree                                                                   0
sherwanis                                                               0
palazzos                                                                0
nehru_jackets                                                           0
petticoats                                                              0
blouse                                                                  0
dupattas                                                                0
gowns                                                                   0
lehenga                                                                 0
women_kurta                                                             0
kurta_men                                                               0
mojaris_men                                                             0
mojaris_women                                                           0
leggings_and_salwars                                                    0
none                                                                  1.0
Name: 0, dtype: object

In [1230]:
df_none.iloc[0,4]

"(A Govt. of West Bengal Enterprises) Handloom Cotton Ethnic Wear For Women's-011H8B9699/BB 12 Black"

In [1231]:
df_none.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
7485,7485,https://m.media-amazon.com/images/I/617BoECVXQ...,images/test/7485.jpeg,INDIBELLE,Cotton Floral Print A-line ShrugCape,women_kurta,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
7486,7486,https://m.media-amazon.com/images/I/71D8VV47Bq...,images/test/7486.jpeg,KIPEK,Kipek Women's Rayon Ikat Print Mirror Work Str...,women_kurta,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
7491,7491,https://m.media-amazon.com/images/I/610E0164bb...,images/test/7491.jpeg,Shatranj,Ethnic Short Kurta,women_kurta,NaN,True,0,0,...,0,0,0,0,0,0,0,0,0,1.0
7492,7492,https://m.media-amazon.com/images/I/41nz8G8qtK...,images/test/7492.jpeg,KANSHI,Women's Rayon Anarkali Kurti With Beautiful Wo...,women_kurta,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
7498,7498,https://m.media-amazon.com/images/I/61VBgoJQAt...,images/test/7498.jpeg,Vaamsi,Crepe Printed Kurti (VPK1805_Purple_Free Size),women_kurta,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1232]:
c1 = (dfr.class_label == 'saree')
c2 = (dfr.none == 1)

dfr.loc[c1 & c2,'saree'] = 1
dfr.loc[c1 & c2,'none'] = 0

In [1233]:
dfs = dfr[dfr.class_label == 'saree']

In [1234]:
dfsn = dfs[dfs.none == 1]
dfsn.shape

(0, 24)

In [1235]:
c1 = (dfr.class_label == 'women_kurta')
c2 = (dfr.kurta == 1)
c3 = (dfr.none == 1)

dfr.loc[c1 & c2 & c3,'women_kurta'] = 1
dfr.loc[c1 & c2 & c3,'none'] = 0

In [1236]:
c1 = (dfr.class_label == 'kurta_men')
c2 = (dfr.kurta == 1)
c3 = (dfr.none == 1)

dfr.loc[c1 & c2 & c3,'kurta_men'] = 1
dfr.loc[c1 & c2 & c3,'none'] = 0

In [1237]:
df_none = dfr[dfr.none == 1]

In [1238]:
df_none.shape

(1865, 24)

In [1239]:
df_none.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
778,778,https://m.media-amazon.com/images/I/61a6yIY7ar...,images/test/778.jpeg,THE BLAZZE,1057 Women Basic Sexy Solid Scoop Neck Slim Fi...,blouse,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
893,893,https://m.media-amazon.com/images/I/61XRuCibz7...,images/test/893.jpeg,SP ENTERPRISE,Designer Lycra Blause For Women(Red & Gold),blouse,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1001,1001,https://m.media-amazon.com/images/I/41P8Dmis0p...,images/test/1001.jpeg,Sri Belha Fashions,Women's Regular Fit Patiala Pant,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1006,1006,https://m.media-amazon.com/images/I/617oAL+MQj...,images/test/1006.jpeg,Generic,Urban Shtri Women's Yellow Machine Embroidered...,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1015,1015,https://m.media-amazon.com/images/I/61do53A0W9...,images/test/1015.jpeg,Revolution,Plus Size Women's White Solid Loose Fit Trousers,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1240]:
df_none.class_label.unique()

array(['blouse', 'dhoti_pants', 'dupattas', 'gowns', 'kurta_men',
       'leggings_and_salwars', 'lehenga', 'mojaris_men', 'mojaris_women',
       'nehru_jackets', 'palazzos', 'petticoats', 'sherwanis',
       'women_kurta'], dtype=object)

In [1241]:
df_none.iloc[0,4]

'1057 Women Basic Sexy Solid Scoop Neck Slim Fit 3/4 Sleeve Crop Top'

In [1242]:
df_none_dupattas = df_none[df_none.class_label == 'dupattas']

In [1243]:
df_none_dupattas.shape

(27, 24)

In [1244]:
df_none_dupattas.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
1515,1515,https://m.media-amazon.com/images/I/61aUy-c+Km...,images/test/1515.jpeg,Generic,Women Rayon Regular Kurtis and Pant Set (Small...,dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1531,1531,https://m.media-amazon.com/images/I/516YVm23M0...,images/test/1531.jpeg,Shaily Retails,White & Multi Color Solid Kurta Set,dupattas,NaN,True,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1536,1536,https://m.media-amazon.com/images/I/81sFjRCTUs...,images/test/1536.jpeg,Rangriti,Women's Rayon Dress Material,dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1573,1573,https://m.media-amazon.com/images/I/81SM0xta7M...,images/test/1573.jpeg,EthnicJunction,Women's Republic Day Special Tricolor Chiffon ...,dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1578,1578,https://m.media-amazon.com/images/I/31lm-lca5S...,images/test/1578.jpeg,Generic,"Women's Big Dyeable Net (White, 5 m, Width 60 ...",dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1245]:
dupattas = dfr[dfr.class_label == 'dupattas']

In [1246]:
dupattas.shape

(500, 24)

In [1247]:
dfr.shape

(7500, 24)

In [1248]:
dup = df_none_dupattas.index

In [1249]:
dfr = dfr.drop(dup)

In [1250]:
dfr.shape

(7473, 24)

In [1251]:
df_none = dfr[dfr.none == 1]

In [1252]:
df_none.shape

(1838, 24)

In [1253]:
df_none_dupattas.iloc[0,4]

'Women Rayon Regular Kurtis and Pant Set (Small) Yellow'

In [1254]:
df_none_dupattas.iloc[4,4]

"Women's Big Dyeable Net (White, 5 m, Width 60 Inches)"

In [1255]:
dfg = df_none[df_none.class_label == 'gowns' ]
dfg.shape

(97, 24)

In [1256]:
dfg.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
2002,2002,https://m.media-amazon.com/images/I/81Jwacq61w...,images/test/2002.jpeg,Dhruvi,Women's Long Maxi Dress Gold Print with Attach...,gowns,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
2007,2007,https://m.media-amazon.com/images/I/71VXTDUlPR...,images/test/2007.jpeg,Doodle,Satin Material Navy Floral Printed 3/4 Sleeve ...,gowns,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
2015,2015,https://m.media-amazon.com/images/I/81UmPZzHOB...,images/test/2015.jpeg,9shines Label,Cotton Feeding Nursing Maternity Kurti with Zips,gowns,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
2023,2023,https://m.media-amazon.com/images/I/81pBouBvKD...,images/test/2023.jpeg,EKTA textiles,Present Women's Banarasi Silk Unstitched Dress...,gowns,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
2027,2027,https://m.media-amazon.com/images/I/71oNC6AxrT...,images/test/2027.jpeg,GOLDSTROMS,Minelli Cotton Maternity Kurti with extra inne...,gowns,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1257]:
dfg.iloc[0,4]

"Women's Long Maxi Dress Gold Print with Attached Sleeve (Free Size L-XXL)"

In [1258]:
dfg.iloc[1,4]

'Satin Material Navy Floral Printed 3/4 Sleeve Dress'

In [1259]:
dfg.iloc[2,4]

'Cotton Feeding Nursing Maternity Kurti with Zips'

In [1260]:
dfg.iloc[3,4]

"Present Women's Banarasi Silk Unstitched Dress Material With duppata"

In [1261]:
dfg['gowns'] = dfr.product_title.str.contains('dress', flags=re.IGNORECASE)

/var/folders/nv/lggm200n09vgfy5n8_6lcz6c0000gn/T/ipykernel_3255/2467206437.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfg['gowns'] = dfr.product_title.str.contains('dress', flags=re.IGNORECASE)

In [1262]:
dfgd = dfg[dfg['gowns'] == True]

In [1263]:
dfgd.shape

(53, 24)

In [1264]:
c1 = (dfg.gowns == True)
c2 = (dfr.none == 1)
dfr.loc[c1 & c2,'gowns'] = 1
dfr.loc[c1 & c2,'none'] = 0

In [1265]:
dfkm = df_none[df_none.class_label == 'kurta_men']
dfkm.shape

(26, 24)

In [1266]:
dfkm.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
2537,2537,https://m.media-amazon.com/images/I/917+vo+Zze...,images/test/2537.jpeg,Ethnix by Raymond,Men's Regular Tunic Shirt (RTHA00140-W1_White ...,kurta_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
2542,2542,https://m.media-amazon.com/images/I/81oLOvJGGU...,images/test/2542.jpeg,Ethnix by Raymond,Men's Regular Tunic Shirt,kurta_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
2553,2553,https://m.media-amazon.com/images/I/81cfCXwV52...,images/test/2553.jpeg,Ethnix by Raymond,Men's Regular Tunic Shirt (RTKB01373-Y5_Medium...,kurta_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
2573,2573,https://m.media-amazon.com/images/I/81ztbwxSHd...,images/test/2573.jpeg,Ethnix by Raymond,Men's Regular Tunic Shirt,kurta_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
2582,2582,https://m.media-amazon.com/images/I/71A1BZIQfq...,images/test/2582.jpeg,Ethnix by Raymond,Men's Regular Tunic Shirt (RTKB00441-L2_Light ...,kurta_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1267]:
mkur = df_none.index[df_none.class_label == 'kurta_men']

In [1268]:
dfr.shape

(7473, 24)

In [1269]:
dfr = dfr.drop(mkur)

In [1270]:
dfr.shape

(7447, 24)

In [1271]:
dfl = df_none[df_none.class_label == 'leggings_and_salwars']

In [1272]:
dfl.shape

(141, 24)

In [1273]:
dfl.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
3007,3007,https://m.media-amazon.com/images/I/71KtWhtCdu...,images/test/3007.jpeg,Eazy Trendz,Viscose Lycra Solid Patiala for Womens - White,leggings_and_salwars,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3012,3012,https://m.media-amazon.com/images/I/71oiIy2PK0...,images/test/3012.jpeg,Aurelia,Women's Chudidar Bottom,leggings_and_salwars,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3016,3016,"https://assets.myntassets.com/h_720,q_90,w_540...",images/test/3016.jpeg,GRACIT,Women Pack Of 2 Solid Patialas,leggings_and_salwars,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3018,3018,https://m.media-amazon.com/images/I/61Scx08vos...,images/test/3018.jpeg,BIBA,Women's Parallel Bottom,leggings_and_salwars,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3025,3025,https://m.media-amazon.com/images/I/713ePAdID7...,images/test/3025.jpeg,W for Woman,Chudidar Bottom,leggings_and_salwars,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1274]:
c1 = (dfr.product_title.str.contains('churidar', flags=re.IGNORECASE))
c2 = (dfr.product_title.str.contains('patiala', flags=re.IGNORECASE))
c3 = (dfr.none == 1)
dfr.loc[(c1 | c2) & c3, 'leggings_and_salwars'] = 1
dfr.loc[(c1 | c2) & c3, 'none'] = 0

In [1275]:
df_none = dfr[dfr.none == 1]
df_none.shape

(1652, 24)

In [1276]:
dfle = df_none[df_none.class_label == 'lehenga']
dfle.shape

(155, 24)

In [1277]:
dfle.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
3504,3504,N/A,images/test/3504.jpg,N/A,N/A,lehenga,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3508,3508,N/A,images/test/3508.jpeg,N/A,N/A,lehenga,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3512,3512,N/A,images/test/3512.jpg,N/A,N/A,lehenga,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3518,3518,N/A,images/test/3518.jpg,N/A,N/A,lehenga,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3525,3525,N/A,images/test/3525.jpg,N/A,N/A,lehenga,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1278]:
dflef = dfr[dfr.class_label == 'lehenga']

In [1279]:
dflef.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
3500,3500,"https://assets.myntassets.com/h_720,q_90,w_540...",images/test/3500.jpeg,Mitera,Green Semi-Stitched Embroidered Lehenga &amp; ...,lehenga,NaN,False,0,0,...,0,1,0,1,0,0,0,0,0,NaN
3501,3501,"https://assets.myntassets.com/h_720,q_90,w_540...",images/test/3501.jpeg,Bollywood Vogue,Blue &amp; Pink Made to Measure Printed Leheng...,lehenga,NaN,False,0,0,...,1,0,0,1,0,0,0,0,0,NaN
3502,3502,"https://assets.myntassets.com/h_720,q_90,w_540...",images/test/3502.jpeg,Baani Creations,Girls Black &amp; Green Printed Ready to Wear ...,lehenga,NaN,False,0,0,...,0,0,0,1,0,0,0,0,0,NaN
3503,3503,"https://assets.myntassets.com/h_720,q_90,w_540...",images/test/3503.jpeg,Mitera,Women Orange &amp; Green Woven Design Semi-Sti...,lehenga,NaN,False,0,0,...,1,1,0,1,0,0,0,0,0,NaN
3504,3504,N/A,images/test/3504.jpg,N/A,N/A,lehenga,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1280]:
dflef.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
3995,3995,N/A,images/test/3995.jpg,N/A,N/A,lehenga,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3996,3996,https://rukminim1.flixcart.com/image/309/371/j...,images/test/3996.jpeg,JSItaliya,Embroidered Semi Stitched Lehenga Choli,lehenga,Green,False,0,0,...,0,0,0,1,0,0,0,0,0,NaN
3997,3997,"https://assets.myntassets.com/h_720,q_90,w_540...",images/test/3997.jpeg,MIMOSA,Pink &amp; Black Woven Design Semi-Stitched Br...,lehenga,NaN,False,0,0,...,1,1,0,1,0,0,0,0,0,NaN
3998,3998,https://m.media-amazon.com/images/I/51emWXWQ6P...,images/test/3998.jpeg,BABA FAB,Women's Self Design Embroidered Semi Stitched ...,lehenga,NaN,False,0,0,...,0,0,0,1,0,0,0,0,0,NaN
3999,3999,https://assets0.mirraw.com/images/8790757/imag...,images/test/3999.jpeg,Mirraw,Red thread embroidery satin semi stitched lehenga,lehenga,NaN,False,0,0,...,0,0,0,1,0,0,0,0,0,NaN

In [1281]:
dfleff = dflef[dflef.product_title == 'N/A']
dfleff.shape

(151, 24)

In [1282]:
c1 = (dfr.product_title == 'N/A') 
c2 = (dfr.class_label == 'lehenga')
c3 = (dfr.none == 1)
dfr.loc[c1 & c2 & c3, 'lehenga'] = 1
dfr.loc[c1 & c2 & c3, 'none'] = 0

In [1283]:
df_none = dfr[dfr.none == 1]
df_none.shape

(1501, 24)

In [1284]:
df_none.columns

Index(['number', 'image_url', 'image_path', 'brand', 'product_title',
       'class_label', 'color', 'kurta', 'dhoti_pants', 'saree', 'sherwanis',
       'palazzos', 'nehru_jackets', 'petticoats', 'blouse', 'dupattas',
       'gowns', 'lehenga', 'women_kurta', 'kurta_men', 'mojaris_men',
       'mojaris_women', 'leggings_and_salwars', 'none'],
      dtype='object')

In [1285]:
dfpe = df_none[df_none.class_label == 'petticoats']
dfpe.shape

(104, 24)

In [1286]:
dfpe.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
6001,6001,N/A,images/test/6001.jpg,N/A,N/A,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
6002,6002,N/A,images/test/6002.jpeg,N/A,N/A,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
6018,6018,N/A,images/test/6018.jpeg,N/A,N/A,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
6022,6022,N/A,images/test/6022.png,N/A,N/A,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
6025,6025,N/A,images/test/6025.jpg,N/A,N/A,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1287]:
dfpe.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
6485,6485,N/A,images/test/6485.jpg,N/A,N/A,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
6487,6487,https://m.media-amazon.com/images/I/71ANJeHYgw...,images/test/6487.jpeg,LAAHI,Plain Cotton Multi-Colour Slips/Camisole/Vests...,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
6489,6489,https://m.media-amazon.com/images/I/31lKlxe6KW...,images/test/6489.jpeg,People,Women's Trouser Suit,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
6493,6493,N/A,images/test/6493.jpeg,N/A,N/A,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
6497,6497,https://m.media-amazon.com/images/I/61fK9-zfqb...,images/test/6497.jpeg,THE BLAZZE,Women's Summer Basic Sexy Strappy Sleeveless R...,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1288]:
pet = df_none.index[df_none.class_label == 'petticoats']

In [1289]:
dfr = dfr.drop(pet)
dfr.shape

(7343, 24)

In [1290]:
dfnj = df_none[df_none.class_label == 'nehru_jackets']
dfnj.shape

(155, 24)

In [1291]:
dfnj.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
5005,5005,https://m.media-amazon.com/images/I/81dsOi8Y12...,images/test/5005.jpeg,Ethnix by Raymond,Men Waist Coat,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5007,5007,https://m.media-amazon.com/images/I/71x6rPxM9K...,images/test/5007.jpeg,Royal Kurta,Royal Men's Black Silk blend Jacket,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5010,5010,https://m.media-amazon.com/images/I/91fYTQxfGn...,images/test/5010.jpeg,Ethnix by Raymond,Men Waist Coat,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5011,5011,N/A,images/test/5011.jpeg,N/A,N/A,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5021,5021,https://m.media-amazon.com/images/I/81WVy3mYFC...,images/test/5021.jpeg,Ethnix,Jacquard Medium Green Coloured Cotton Bundi,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1292]:
dfnj.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
5482,5482,https://m.media-amazon.com/images/I/614VpU3oja...,images/test/5482.jpeg,.Zuricch,Men's Cotton Waistcoat,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5483,5483,N/A,images/test/5483.jpg,N/A,N/A,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5489,5489,https://m.media-amazon.com/images/I/8105+e13He...,images/test/5489.jpeg,Ethnix by Raymond,Men's Jacket (RTUW00231-B1_Light Blue_104),nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5497,5497,https://m.media-amazon.com/images/I/51OSTgiOr0...,images/test/5497.jpeg,hangup,Men's synthetic Waist Coat,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5498,5498,https://m.media-amazon.com/images/I/91bW5Gi7Si...,images/test/5498.jpeg,Ethnix by Raymond,Men Waist Coat,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1293]:
dfr.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,0.0
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,NaN
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,NaN
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,NaN
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,NaN

In [1294]:
dfnj = dfr[dfr.class_label == 'nehru_jackets']
dfnj.shape

(500, 24)

In [1295]:
df_none_dupattas.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
1515,1515,https://m.media-amazon.com/images/I/61aUy-c+Km...,images/test/1515.jpeg,Generic,Women Rayon Regular Kurtis and Pant Set (Small...,dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1531,1531,https://m.media-amazon.com/images/I/516YVm23M0...,images/test/1531.jpeg,Shaily Retails,White & Multi Color Solid Kurta Set,dupattas,NaN,True,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1536,1536,https://m.media-amazon.com/images/I/81sFjRCTUs...,images/test/1536.jpeg,Rangriti,Women's Rayon Dress Material,dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1573,1573,https://m.media-amazon.com/images/I/81SM0xta7M...,images/test/1573.jpeg,EthnicJunction,Women's Republic Day Special Tricolor Chiffon ...,dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1578,1578,https://m.media-amazon.com/images/I/31lm-lca5S...,images/test/1578.jpeg,Generic,"Women's Big Dyeable Net (White, 5 m, Width 60 ...",dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1296]:
c1 = (dfr.product_title == 'N/A') 
c2 = (dfr.class_label == 'lehenga')
c3 = (dfr.none == 1)

dfr.loc[c1 & c2 & c3, 'lehenga'] = 1
dfr.loc[c1 & c2 & c3, 'none'] = 0

In [1297]:
c1 = (dfr.class_label == 'nehru_jackets')
c2 = (dfr.none == 1)

dfr.loc[c1 & c2, 'nehru_jackets'] = 1
dfr.loc[c1 & c2, 'none'] = 0

In [1298]:
dfmm = df_none[df_none.class_label == 'mojaris_men']
dfmm.shape

(272, 24)

In [1299]:
dfmm.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
4002,4002,https://m.media-amazon.com/images/I/61DYZNh1Yr...,images/test/4002.jpeg,PM Traders,Rajasthani Men's Desi Style Leather Jutti Brown,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4003,4003,https://m.media-amazon.com/images/I/7116kC9G6t...,images/test/4003.jpeg,AANYA,Stylish & Comfortable Casual/Sport/Running/Wal...,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4005,4005,https://m.media-amazon.com/images/I/71GadUErW4...,images/test/4005.jpeg,CatBird,"Mens and Boys Faux Leather Ethnic Jutti,Casual...",mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4009,4009,https://m.media-amazon.com/images/I/31FYGRdI6L...,images/test/4009.jpeg,Stanfield,SF Men's Craft Shoe Black,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4012,4012,https://m.media-amazon.com/images/I/41nhoyOMkn...,images/test/4012.jpeg,Generic,Brown,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1300]:
dfmm.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
4493,4493,N/A,images/test/4493.jpeg,N/A,N/A,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4494,4494,https://m.media-amazon.com/images/I/71nl28ARRZ...,images/test/4494.jpeg,Great Art,Handmade Kolhapuri Brown Men Chappals,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4496,4496,https://m.media-amazon.com/images/I/41dZzGpuIy...,images/test/4496.jpeg,TIME SHOES,Formal Mojdi (Jutti) - Numeric 9 UK Black,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4497,4497,https://m.media-amazon.com/images/I/615goEBJ4z...,images/test/4497.jpeg,PADUKI,Men's Loafer,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4499,4499,https://rukminim1.flixcart.com/image/309/371/k...,images/test/4499.jpeg,Di-Michele,Stylish Casual Comfy Party wear Light weight N...,mojaris_men,N/A,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1301]:
mo = dfmm.index
dfr = dfr.drop(mo)

In [1302]:
dfr.shape

(7071, 24)

In [1303]:
dfmw = df_none[df_none.class_label == 'mojaris_women']
dfmw.shape

(258, 24)

In [1304]:
dfmw.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
4502,4502,https://m.media-amazon.com/images/I/81uvfxpURS...,images/test/4502.jpeg,Generic,Tribal India Women Casaul Pink Embroidered Lea...,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4503,4503,https://m.media-amazon.com/images/I/71lOlNuHb7...,images/test/4503.jpeg,The Desi Dulhan,Present This Brown Colored Embellished Casual ...,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4505,4505,https://m.media-amazon.com/images/I/51hSessptd...,images/test/4505.jpeg,Prolific,Men Casual Loafers Shoes,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4510,4510,https://m.media-amazon.com/images/I/41UB+2KjYa...,images/test/4510.jpeg,Generic,Paradise Jutis Mojri for Women || Pretty Style...,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4518,4518,https://m.media-amazon.com/images/I/61d+jzIHa8...,images/test/4518.jpeg,SHAHI Punjabi Handicrafts,Shahi Punjabi Footwear Traditional Punjabi Jut...,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1305]:
dfmw.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
4993,4993,https://m.media-amazon.com/images/I/41mqaHD1RT...,images/test/4993.jpeg,Great Art,Black and White Sandals for Women's Girls,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4994,4994,N/A,images/test/4994.jpeg,N/A,N/A,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4995,4995,https://m.media-amazon.com/images/I/81rDNfQ3yq...,images/test/4995.jpeg,RearStep,Women's Flat Fancy Slip-On Slippers,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4997,4997,N/A,images/test/4997.jpeg,N/A,N/A,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4998,4998,https://m.media-amazon.com/images/I/71JUAFOFj7...,images/test/4998.jpeg,JONT,"FLOST, Jutti, Leather Sole, Hand Made, Stitche...",mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1306]:
mw = dfmw.index
dfr = dfr.drop(mw)

In [1307]:
dfr.shape

(6813, 24)

In [1308]:
df_none.columns

Index(['number', 'image_url', 'image_path', 'brand', 'product_title',
       'class_label', 'color', 'kurta', 'dhoti_pants', 'saree', 'sherwanis',
       'palazzos', 'nehru_jackets', 'petticoats', 'blouse', 'dupattas',
       'gowns', 'lehenga', 'women_kurta', 'kurta_men', 'mojaris_men',
       'mojaris_women', 'leggings_and_salwars', 'none'],
      dtype='object')

In [1309]:
dfpa = df_none[df_none.class_label == 'palazzos']
dfpa.shape

(213, 24)

In [1310]:
dfpa.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
5501,5501,https://rukminim1.flixcart.com/image/309/371/k...,images/test/5501.jpeg,SANGAFASHION,Regular Fit Women White Rayon Trousers,palazzos,N/A,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5502,5502,https://rukminim1.flixcart.com/image/309/371/k...,images/test/5502.jpeg,MAX,Women Black Rayon Trousers,palazzos,N/A,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5504,5504,https://rukminim1.flixcart.com/image/309/371/j...,images/test/5504.jpeg,Myra-Syra,Regular Fit Women Multicolor Polyester Trousers,palazzos,N/A,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5505,5505,"https://assets.myntassets.com/h_720,q_90,w_540...",images/test/5505.jpeg,TAG 7,Women Beige Hem Design,palazzos,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5507,5507,N/A,images/test/5507.jpg,N/A,N/A,palazzos,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1311]:
dfpa.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
5992,5992,https://rukminim1.flixcart.com/image/309/371/k...,images/test/5992.jpeg,Viaan,Relaxed Women White Cotton Blend Trousers,palazzos,N/A,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5993,5993,https://rukminim1.flixcart.com/image/309/371/t...,images/test/5993.jpeg,rare,Regular Fit Women Maroon Poly Georgette Trousers,palazzos,N/A,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5994,5994,https://rukminim1.flixcart.com/image/309/371/k...,images/test/5994.jpeg,DARZI,Regular Fit Women Multicolor Lycra Blend Trousers,palazzos,N/A,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5995,5995,"https://assets.myntassets.com/h_720,q_90,w_540...",images/test/5995.jpeg,NEUDIS,Women Pink Solid,palazzos,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5997,5997,https://rukminim1.flixcart.com/image/309/371/j...,images/test/5997.jpeg,FMC,Relaxed Women Multicolor Poly Crepe Trousers,palazzos,N/A,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1312]:
c1 = (dfr.class_label == 'palazzos')
c2 = (dfr.none == 1)

dfr.loc[c1 & c2, 'palazzos'] = 1
dfr.loc[c1 & c2, 'none'] = 0

In [1313]:
dfd = df_none[df_none.class_label == 'dhoti_pants']
dfd.shape

(67, 24)

In [1314]:
dfd.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
1006,1006,https://m.media-amazon.com/images/I/617oAL+MQj...,images/test/1006.jpeg,Generic,Urban Shtri Women's Yellow Machine Embroidered...,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1015,1015,https://m.media-amazon.com/images/I/61do53A0W9...,images/test/1015.jpeg,Revolution,Plus Size Women's White Solid Loose Fit Trousers,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1022,1022,https://m.media-amazon.com/images/I/61hVYv2Rpo...,images/test/1022.jpeg,PATRORNA,Womens Collared High Low Tunic Maternity Nursing,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1040,1040,https://m.media-amazon.com/images/I/712--34Lwz...,images/test/1040.jpeg,PATRORNA,Womens Pathani Style Tunic Maternity Nursing,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1050,1050,https://m.media-amazon.com/images/I/51jq6XPmES...,images/test/1050.jpeg,Glampunch,Women's Exclusive Multicolor Stripes Top for W...,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1315]:
dfd.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
1450,1450,https://m.media-amazon.com/images/I/517oWK4-01...,images/test/1450.jpeg,Jaipur Manthan,Rayon Multi Color Gotta Work Casual Wear Kurti...,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1454,1454,https://m.media-amazon.com/images/I/41w++jmmQs...,images/test/1454.jpeg,Glampunch,Women's Exclusive Blue Checks Ruffle Top for W...,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1466,1466,https://m.media-amazon.com/images/I/41gAPPN9y0...,images/test/1466.jpeg,Nandu,Brand Men's Cotton Stitched Lungi (Pattern May...,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1489,1489,https://m.media-amazon.com/images/I/61MLwW7hl+...,images/test/1489.jpeg,PATRORNA,Womens Double Layer Crop Top,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1493,1493,https://m.media-amazon.com/images/I/61Gp1XObxd...,images/test/1493.jpeg,PATRORNA,Womens Double Layer Crop Top,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [1316]:
dfr.iloc[1061, 4]

'Rayon Short Tunic Kurti with Dhoti Pant Set Maroon and White'

In [1317]:
dp = dfd.index

In [1318]:
dfr = dfr.drop(dp)

In [1319]:
dfr.shape

(6746, 24)

In [1320]:
dfr.to_csv('/Users/butler/Documents/springboard_bootcamp/Classification_of_Indian_clothing_images/data/interim/df_test_multilabel.csv')

In [1321]:
dfr = dfr.drop(['number', 'image_url', 'brand', 'product_title',
       'class_label', 'color', 'kurta', 'none'], axis=1)

In [1322]:
dfr.head()

,image_path,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,images/test/0.jpeg,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,images/test/1.jpeg,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2,images/test/2.jpeg,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3,images/test/3.jpeg,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4,images/test/4.jpeg,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [1323]:
dfr.to_csv('/Users/butler/Documents/springboard_bootcamp/Classification_of_Indian_clothing_images/data/interim/test_one_hot.csv')