In [1]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv("/Users/butler/Documents/GitHub/projects/Storm_events/StormEvents_details-ftp_v1.0_d1950_c20210803.csv")

In [16]:
df.head()

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE
0,195004,28,1445,195004,28,1445,NaN,10096222,OKLAHOMA,40,...,0,NaN,NaN,35.12,-99.20,35.17,-99.20,NaN,NaN,PUB
1,195004,29,1530,195004,29,1530,NaN,10120412,TEXAS,48,...,0,NaN,NaN,31.90,-98.60,31.73,-98.60,NaN,NaN,PUB
2,195007,5,1800,195007,5,1800,NaN,10104927,PENNSYLVANIA,42,...,0,NaN,NaN,40.58,-75.70,40.65,-75.47,NaN,NaN,PUB
3,195007,5,1830,195007,5,1830,NaN,10104928,PENNSYLVANIA,42,...,0,NaN,NaN,40.60,-76.75,NaN,NaN,NaN,NaN,PUB
4,195007,24,1440,195007,24,1440,NaN,10104929,PENNSYLVANIA,42,...,0,NaN,NaN,41.63,-79.68,NaN,NaN,NaN,NaN,PUB

In [21]:
df.shape

(446, 51)

In [25]:
old_file = "/Users/butler/Documents/GitHub/projects/Storm_events/StormEvents_details-ftp_v1.0_d1950_c20210803.csv"
old_date = '1950'
for i in range(1951, 1952):
    new_date = str(i)
    new_file = old_file.replace(old_date, new_date)
    
    print(new_file)
    df_new = pd.read_csv(new_file)
    df = pd.concat([df, df_new])

/Users/butler/Documents/GitHub/projects/Storm_events/StormEvents_details-ftp_v1.0_d1951_c20210803.csv

FileNotFoundError: [Errno 2] No such file or directory: '/Users/butler/Documents/GitHub/projects/Storm_events/StormEvents_details-ftp_v1.0_d1951_c20210803.csv'

In [ ]:
StormEvents_details-ftp_v1.0_d1951_c20210803

In [23]:
df_new

,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,...,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE
0,195004,28,1445,195004,28,1445,NaN,10096222,OKLAHOMA,40,...,0,NaN,NaN,35.12,-99.20,35.17,-99.20,NaN,NaN,PUB
1,195004,29,1530,195004,29,1530,NaN,10120412,TEXAS,48,...,0,NaN,NaN,31.90,-98.60,31.73,-98.60,NaN,NaN,PUB
2,195007,5,1800,195007,5,1800,NaN,10104927,PENNSYLVANIA,42,...,0,NaN,NaN,40.58,-75.70,40.65,-75.47,NaN,NaN,PUB
3,195007,5,1830,195007,5,1830,NaN,10104928,PENNSYLVANIA,42,...,0,NaN,NaN,40.60,-76.75,NaN,NaN,NaN,NaN,PUB
4,195007,24,1440,195007,24,1440,NaN,10104929,PENNSYLVANIA,42,...,0,NaN,NaN,41.63,-79.68,NaN,NaN,NaN,NaN,PUB
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,195012,2,1500,195012,2,1500,NaN,10009716,ILLINOIS,17,...,0,NaN,NaN,38.97,-90.05,39.00,-89.92,NaN,NaN,PUB
219,195012,2,1515,195012,2,1515,NaN,10009717,ILLINOIS,17,...,0,NaN,NaN,39.00,-89.92,39.07,-89.72,NaN,NaN,PUB
220,195012,2,1600,195012,2,1600,NaN,10009718,ILLINOIS,17,...,0,NaN,NaN,38.75,-89.67,38.80,-89.60,NaN,NaN,PUB
221,195012,2,1600,195012,2,1600,NaN,10009719,ILLINOIS,17,...,0,NaN,NaN,38.80,-89.60,38.90,-89.38,NaN,NaN,PUB
222,195012,2,1730,195012,2,1730,NaN,10009720,ILLINOIS,17,...,0,NaN,NaN,38.17,-89.78,38.22,-89.62,NaN,NaN,PUB

In [8]:
df.loc[1]

BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,STATE_FIPS,YEAR,MONTH_NAME,EVENT_TYPE,CZ_TYPE,CZ_FIPS,CZ_NAME,WFO,BEGIN_DATE_TIME,CZ_TIMEZONE,END_DATE_TIME,INJURIES_DIRECT,INJURIES_INDIRECT,DEATHS_DIRECT,DEATHS_INDIRECT,DAMAGE_PROPERTY,DAMAGE_CROPS,SOURCE,MAGNITUDE,MAGNITUDE_TYPE,FLOOD_CAUSE,CATEGORY,TOR_F_SCALE,TOR_LENGTH,TOR_WIDTH,TOR_OTHER_WFO,TOR_OTHER_CZ_STATE,TOR_OTHER_CZ_FIPS,TOR_OTHER_CZ_NAME,BEGIN_RANGE,BEGIN_AZIMUTH,BEGIN_LOCATION,END_RANGE,END_AZIMUTH,END_LOCATION,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EPISODE_NARRATIVE,EVENT_NARRATIVE,DATA_SOURCE    195004,29,1530,195004,29,1530,,10120412,"TEXAS...
Name: 1, dtype: object