In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [11]:
ejscreen_2021 = '/Users/butler/Documents/hp/Capstone_Two/data/raw/EJSCREEN_2020_StatePctile.csv'
df = pd.read_csv('/data/raw/EJSCREEN_2020_StatePctile.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/data/raw/EJSCREEN_2020_StatePctile.csv'

In [5]:
df.shape

NameError: name 'df' is not defined

In [ ]:
df.head()

,OBJECTID,ID,STATE_NAME,ST_ABBREV,REGION,ACSTOTPOP,D_PM25_2,B_PM25_D2,P_PM25_D2,D_OZONE_2,...,T_PNPL,T_PNPL_D2,T_PRMP,T_PRMP_D2,T_PTSDF,T_PTSDF_D2,T_PWDIS,T_PWDIS_D2,Shape_Length,Shape_Area
0,1,10010201001,Alabama,AL,4,636,-492.025529,6,52.0,-1866.386370,...,0.071 facilities/km distance (79%ile),40%ile,0.085 facilities/km distance (23%ile),53%ile,0.59 facilities/km distance (57%ile),38%ile,NaN,NaN,13443.155206,6.040790e+06
1,2,10010201002,Alabama,AL,4,1287,-2053.083414,4,30.0,-7787.902602,...,0.064 facilities/km distance (76%ile),19%ile,0.074 facilities/km distance (17%ile),42%ile,0.45 facilities/km distance (52%ile),23%ile,NaN,NaN,11917.089598,7.834160e+06
2,3,10010202001,Alabama,AL,4,810,1846.126938,8,75.0,7002.783717,...,0.069 facilities/km distance (78%ile),85%ile,0.078 facilities/km distance (20%ile),67%ile,0.65 facilities/km distance (59%ile),77%ile,NaN,NaN,7770.915121,2.900774e+06
3,4,10010202002,Alabama,AL,4,1218,1392.075305,8,72.0,5280.461532,...,0.076 facilities/km distance (81%ile),83%ile,0.087 facilities/km distance (24%ile),66%ile,1 facilities/km distance (69%ile),78%ile,NaN,NaN,6506.804784,1.793332e+06
4,5,10010203001,Alabama,AL,4,2641,-769.374640,5,48.0,-2911.892606,...,0.074 facilities/km distance (80%ile),32%ile,0.08 facilities/km distance (21%ile),51%ile,1.2 facilities/km distance (74%ile),24%ile,NaN,NaN,11070.367848,5.461602e+06

In [ ]:
df.tail()

,OBJECTID,ID,STATE_NAME,ST_ABBREV,REGION,ACSTOTPOP,D_PM25_2,B_PM25_D2,P_PM25_D2,D_OZONE_2,...,T_PNPL,T_PNPL_D2,T_PRMP,T_PRMP_D2,T_PTSDF,T_PTSDF_D2,T_PWDIS,T_PWDIS_D2,Shape_Length,Shape_Area
220328,220329,721537506011,Puerto Rico,PR,2,699,NaN,0,NaN,NaN,...,0.071 facilities/km distance (39%ile),61%ile,1.1 facilities/km distance (74%ile),81%ile,0.28 facilities/km distance (48%ile),71%ile,0.0025 toxicity-weighted concentration/meters ...,72%ile,19751.958143,8.486394e+06
220329,220330,721537506012,Puerto Rico,PR,2,2432,NaN,0,NaN,NaN,...,0.064 facilities/km distance (35%ile),63%ile,1.5 facilities/km distance (83%ile),88%ile,0.39 facilities/km distance (53%ile),79%ile,0.0032 toxicity-weighted concentration/meters ...,75%ile,6704.079316,1.744950e+06
220330,220331,721537506013,Puerto Rico,PR,2,976,NaN,0,NaN,NaN,...,0.064 facilities/km distance (35%ile),49%ile,2.3 facilities/km distance (91%ile),79%ile,0.5 facilities/km distance (57%ile),66%ile,0.061 toxicity-weighted concentration/meters d...,86%ile,7737.485130,1.989274e+06
220331,220332,721537506021,Puerto Rico,PR,2,1707,NaN,0,NaN,NaN,...,0.056 facilities/km distance (27%ile),70%ile,0.53 facilities/km distance (44%ile),80%ile,0.33 facilities/km distance (51%ile),82%ile,0.000024 toxicity-weighted concentration/meter...,55%ile,5128.437876,1.265271e+06
220332,220333,721537506022,Puerto Rico,PR,2,804,NaN,0,NaN,NaN,...,0.063 facilities/km distance (34%ile),65%ile,0.62 facilities/km distance (51%ile),76%ile,0.23 facilities/km distance (43%ile),73%ile,0.0015 toxicity-weighted concentration/meters ...,71%ile,20006.384457,1.848868e+07

In [ ]:
df.describe()

,OBJECTID,ID,REGION,ACSTOTPOP,D_PM25_2,B_PM25_D2,P_PM25_D2,D_OZONE_2,B_OZONE_D2,P_OZONE_D2,...,B_LESHSPCT,P_LESHSPCT,UNDER5PCT,B_UNDR5PCT,P_UNDR5PCT,OVER64PCT,B_OVR64PCT,P_OVR64PCT,Shape_Length,Shape_Area
count,220333.000000,2.203330e+05,220333.000000,220333.000000,216046.000000,220333.000000,216046.000000,216075.000000,220333.000000,216046.000000,...,220333.000000,220333.000000,220333.000000,220333.000000,220333.000000,220333.000000,220333.000000,220333.000000,2.203330e+05,2.203330e+05
mean,110167.000000,2.863577e+11,5.167642,1480.894696,141.804077,5.678836,52.125825,120.102489,5.677338,52.115503,...,5.684006,50.877826,0.058312,5.293115,47.009272,0.164956,5.908534,52.917339,2.159727e+04,1.035941e+08
std,63604.802768,1.633201e+11,2.482247,988.146948,3444.401415,2.703466,25.484327,16722.439926,2.700227,25.451861,...,3.012208,29.231050,0.040289,3.071742,29.795501,0.101952,3.034565,29.508831,6.339526e+04,3.809275e+09
min,1.000000,1.001020e+10,1.000000,0.000000,-90644.530105,0.000000,0.000000,-371198.063720,0.000000,0.000000,...,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,3.015633e+02,5.494842e+03
25%,55084.000000,1.312101e+11,3.000000,890.000000,-1746.870154,4.000000,32.000000,-9156.587422,4.000000,32.000000,...,3.000000,25.000000,0.030006,3.000000,20.000000,0.097784,3.000000,28.000000,4.161934e+03,8.056123e+05
50%,110167.000000,2.816395e+11,5.000000,1266.000000,-538.105932,6.000000,53.000000,-2793.854824,6.000000,53.000000,...,6.000000,52.000000,0.053263,5.000000,45.000000,0.150147,6.000000,55.000000,7.461881e+03,2.223780e+06
75%,165250.000000,4.200343e+11,7.000000,1817.000000,1563.734759,8.000000,73.000000,7611.002317,8.000000,73.000000,...,8.000000,76.000000,0.080402,8.000000,73.000000,0.210931,8.000000,79.000000,2.034583e+04,1.521968e+07
max,220333.000000,7.215375e+11,10.000000,55407.000000,62799.333874,11.000000,100.000000,272045.350467,11.000000,100.000000,...,11.000000,100.000000,0.525000,11.000000,100.000000,1.000000,11.000000,100.000000,8.214219e+06,1.289561e+12

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220333 entries, 0 to 220332
Columns: 124 entries, OBJECTID to Shape_Area
dtypes: float64(60), int64(33), object(31)
memory usage: 208.4+ MB

In [ ]:
df.dtypes

OBJECTID          int64
ID                int64
STATE_NAME       object
ST_ABBREV        object
REGION            int64
                 ...
T_PTSDF_D2       object
T_PWDIS          object
T_PWDIS_D2       object
Shape_Length    float64
Shape_Area      float64
Length: 124, dtype: object

In [ ]:
df['ACSTOTPOP'].dtypes

dtype('int64')

In [ ]:
df['MINORPCT'].dtypes

dtype('float64')

In [ ]:
df['PRE1960PCT'].dtypes

dtype('float64')

In [ ]:
df['P_MINORPCT'].dtypes

dtype('float64')

In [ ]:
pol = df.astype({"ID":'int64'})

In [ ]:
pol.head()

,OBJECTID,ID,STATE_NAME,ST_ABBREV,REGION,ACSTOTPOP,D_PM25_2,B_PM25_D2,P_PM25_D2,D_OZONE_2,...,T_PNPL,T_PNPL_D2,T_PRMP,T_PRMP_D2,T_PTSDF,T_PTSDF_D2,T_PWDIS,T_PWDIS_D2,Shape_Length,Shape_Area
0,1,10010201001,Alabama,AL,4,636,-492.025529,6,52.0,-1866.386370,...,0.071 facilities/km distance (79%ile),40%ile,0.085 facilities/km distance (23%ile),53%ile,0.59 facilities/km distance (57%ile),38%ile,NaN,NaN,13443.155206,6.040790e+06
1,2,10010201002,Alabama,AL,4,1287,-2053.083414,4,30.0,-7787.902602,...,0.064 facilities/km distance (76%ile),19%ile,0.074 facilities/km distance (17%ile),42%ile,0.45 facilities/km distance (52%ile),23%ile,NaN,NaN,11917.089598,7.834160e+06
2,3,10010202001,Alabama,AL,4,810,1846.126938,8,75.0,7002.783717,...,0.069 facilities/km distance (78%ile),85%ile,0.078 facilities/km distance (20%ile),67%ile,0.65 facilities/km distance (59%ile),77%ile,NaN,NaN,7770.915121,2.900774e+06
3,4,10010202002,Alabama,AL,4,1218,1392.075305,8,72.0,5280.461532,...,0.076 facilities/km distance (81%ile),83%ile,0.087 facilities/km distance (24%ile),66%ile,1 facilities/km distance (69%ile),78%ile,NaN,NaN,6506.804784,1.793332e+06
4,5,10010203001,Alabama,AL,4,2641,-769.374640,5,48.0,-2911.892606,...,0.074 facilities/km distance (80%ile),32%ile,0.08 facilities/km distance (21%ile),51%ile,1.2 facilities/km distance (74%ile),24%ile,NaN,NaN,11070.367848,5.461602e+06

In [ ]:
df.columns.get_loc('P_MINORPCT')

77

To prepare this for concatenation with health data, need to make health LocationName and df ID the same. ID has one extra digit for the block group, while LocationName only includes census tracts. Combining the block groups into census tracts by averaging the features scaled by population.

In [ ]:
pol['LocationName'] = pol['ID'] // 10
poll = pol.copy()
poll.head()

C:\Users\butle\AppData\Local\Temp\ipykernel_15896\3921973867.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pol['LocationName'] = pol['ID'] // 10

,OBJECTID,ID,STATE_NAME,ST_ABBREV,REGION,ACSTOTPOP,D_PM25_2,B_PM25_D2,P_PM25_D2,D_OZONE_2,...,T_PNPL_D2,T_PRMP,T_PRMP_D2,T_PTSDF,T_PTSDF_D2,T_PWDIS,T_PWDIS_D2,Shape_Length,Shape_Area,LocationName
0,1,10010201001,Alabama,AL,4,636,-492.025529,6,52.0,-1866.386370,...,40%ile,0.085 facilities/km distance (23%ile),53%ile,0.59 facilities/km distance (57%ile),38%ile,NaN,NaN,13443.155206,6.040790e+06,1001020100
1,2,10010201002,Alabama,AL,4,1287,-2053.083414,4,30.0,-7787.902602,...,19%ile,0.074 facilities/km distance (17%ile),42%ile,0.45 facilities/km distance (52%ile),23%ile,NaN,NaN,11917.089598,7.834160e+06,1001020100
2,3,10010202001,Alabama,AL,4,810,1846.126938,8,75.0,7002.783717,...,85%ile,0.078 facilities/km distance (20%ile),67%ile,0.65 facilities/km distance (59%ile),77%ile,NaN,NaN,7770.915121,2.900774e+06,1001020200
3,4,10010202002,Alabama,AL,4,1218,1392.075305,8,72.0,5280.461532,...,83%ile,0.087 facilities/km distance (24%ile),66%ile,1 facilities/km distance (69%ile),78%ile,NaN,NaN,6506.804784,1.793332e+06,1001020200
4,5,10010203001,Alabama,AL,4,2641,-769.374640,5,48.0,-2911.892606,...,32%ile,0.08 facilities/km distance (21%ile),51%ile,1.2 facilities/km distance (74%ile),24%ile,NaN,NaN,11070.367848,5.461602e+06,1001020300

Getting rid of any rows with zero population

In [ ]:
poll = poll[poll['ACSTOTPOP'] != 0]

Dropping columns not needed

In [ ]:
poll = poll.drop(["OBJECTID", 'STATE_NAME', 'ID', 'REGION', 'Shape_Length', 'Shape_Area'], axis=1)
poll.head()

,ST_ABBREV,ACSTOTPOP,D_PM25_2,B_PM25_D2,P_PM25_D2,D_OZONE_2,B_OZONE_D2,P_OZONE_D2,D_DSLPM_2,B_DSLPM_D2,...,T_LDPNT_D2,T_PNPL,T_PNPL_D2,T_PRMP,T_PRMP_D2,T_PTSDF,T_PTSDF_D2,T_PWDIS,T_PWDIS_D2,LocationName
0,AL,636,-492.025529,6,52.0,-1866.386370,6,52.0,-14.148258,6,...,31%ile,0.071 facilities/km distance (79%ile),40%ile,0.085 facilities/km distance (23%ile),53%ile,0.59 facilities/km distance (57%ile),38%ile,NaN,NaN,1001020100
1,AL,1287,-2053.083414,4,30.0,-7787.902602,4,32.0,-59.036679,4,...,20%ile,0.064 facilities/km distance (76%ile),19%ile,0.074 facilities/km distance (17%ile),42%ile,0.45 facilities/km distance (52%ile),23%ile,NaN,NaN,1001020100
2,AL,810,1846.126938,8,75.0,7002.783717,8,75.0,57.850440,8,...,77%ile,0.069 facilities/km distance (78%ile),85%ile,0.078 facilities/km distance (20%ile),67%ile,0.65 facilities/km distance (59%ile),77%ile,NaN,NaN,1001020200
3,AL,1218,1392.075305,8,72.0,5280.461532,8,71.0,43.622227,8,...,83%ile,0.076 facilities/km distance (81%ile),83%ile,0.087 facilities/km distance (24%ile),66%ile,1 facilities/km distance (69%ile),78%ile,NaN,NaN,1001020200
4,AL,2641,-769.374640,5,48.0,-2911.892606,5,49.0,-28.752998,5,...,42%ile,0.074 facilities/km distance (80%ile),32%ile,0.08 facilities/km distance (21%ile),51%ile,1.2 facilities/km distance (74%ile),24%ile,NaN,NaN,1001020300

In [ ]:
poll.head()

,ST_ABBREV,ACSTOTPOP,D_PM25_2,B_PM25_D2,P_PM25_D2,D_OZONE_2,B_OZONE_D2,P_OZONE_D2,D_DSLPM_2,B_DSLPM_D2,...,T_LDPNT_D2,T_PNPL,T_PNPL_D2,T_PRMP,T_PRMP_D2,T_PTSDF,T_PTSDF_D2,T_PWDIS,T_PWDIS_D2,LocationName
0,AL,636,-492.025529,6,52.0,-1866.386370,6,52.0,-14.148258,6,...,31%ile,0.071 facilities/km distance (79%ile),40%ile,0.085 facilities/km distance (23%ile),53%ile,0.59 facilities/km distance (57%ile),38%ile,NaN,NaN,1001020100
1,AL,1287,-2053.083414,4,30.0,-7787.902602,4,32.0,-59.036679,4,...,20%ile,0.064 facilities/km distance (76%ile),19%ile,0.074 facilities/km distance (17%ile),42%ile,0.45 facilities/km distance (52%ile),23%ile,NaN,NaN,1001020100
2,AL,810,1846.126938,8,75.0,7002.783717,8,75.0,57.850440,8,...,77%ile,0.069 facilities/km distance (78%ile),85%ile,0.078 facilities/km distance (20%ile),67%ile,0.65 facilities/km distance (59%ile),77%ile,NaN,NaN,1001020200
3,AL,1218,1392.075305,8,72.0,5280.461532,8,71.0,43.622227,8,...,83%ile,0.076 facilities/km distance (81%ile),83%ile,0.087 facilities/km distance (24%ile),66%ile,1 facilities/km distance (69%ile),78%ile,NaN,NaN,1001020200
4,AL,2641,-769.374640,5,48.0,-2911.892606,5,49.0,-28.752998,5,...,42%ile,0.074 facilities/km distance (80%ile),32%ile,0.08 facilities/km distance (21%ile),51%ile,1.2 facilities/km distance (74%ile),24%ile,NaN,NaN,1001020300

In [ ]:
df.columns.get_loc('DSLPM')

45

Getting rid of map data

In [ ]:
df = poll
pop = df.ACSTOTPOP
loc = df.LocationName
df = df.iloc[:, 1:67]

Multiplying numerical columns, except ACSTOTPOP, by population (ACSTOTPOP), as a step in the process of combining the numberical data of rows with same LocationName by a weighted average

In [ ]:
df.head()

,ACSTOTPOP,D_PM25_2,B_PM25_D2,P_PM25_D2,D_OZONE_2,B_OZONE_D2,P_OZONE_D2,D_DSLPM_2,B_DSLPM_D2,P_DSLPM_D2,...,B_PNPL,P_PNPL,PRMP,B_PRMP,P_PRMP,PTSDF,B_PTSDF,P_PTSDF,PWDIS,B_PWDIS
0,636,-492.025529,6,52.0,-1866.386370,6,52.0,-14.148258,6,51.0,...,8,79.0,0.085201,3,23.0,0.586754,6,57.0,NaN,0
1,1287,-2053.083414,4,30.0,-7787.902602,4,32.0,-59.036679,4,30.0,...,8,76.0,0.073796,2,17.0,0.450601,6,52.0,NaN,0
2,810,1846.126938,8,75.0,7002.783717,8,75.0,57.850440,8,76.0,...,8,78.0,0.077868,3,20.0,0.653377,6,59.0,NaN,0
3,1218,1392.075305,8,72.0,5280.461532,8,71.0,43.622227,8,72.0,...,9,81.0,0.086918,3,24.0,1.009395,7,69.0,NaN,0
4,2641,-769.374640,5,48.0,-2911.892606,5,49.0,-28.752998,5,42.0,...,9,80.0,0.080274,3,21.0,1.177764,8,74.0,NaN,0

In [ ]:
df = df.drop(['B_RESP', 'P_RESP', 'P_CANCR', 'B_CANCR', 'P_DSLPM', 'B_DSLPM', 'P_OZONE', 'B_OZONE', 'P_PM25', 'B_PM25','P_PWDIS_D2','B_PWDIS_D2', 'D_PWDIS_2','P_DSLPM_D2', 'B_DSLPM_D2','B_PWDIS','P_PTSDF', 'B_PTSDF','P_PRMP','B_PRMP','P_PNPL','B_PNPL','P_LDPNT','B_LDPNT','P_PTRAF','B_PTRAF','B_CANCR_D2'], axis=1)
df.head()

,ACSTOTPOP,D_PM25_2,B_PM25_D2,P_PM25_D2,D_OZONE_2,B_OZONE_D2,P_OZONE_D2,D_DSLPM_2,D_CANCR_2,P_CANCR_D2,...,OZONE,DSLPM,CANCER,RESP,PTRAF,PRE1960PCT,PNPL,PRMP,PTSDF,PWDIS
0,636,-492.025529,6,52.0,-1866.386370,6,52.0,-14.148258,-2506.966483,51.0,...,36.760212,0.278663,49.377032,0.788052,91.015900,0.272109,0.070942,0.085201,0.586754,NaN
1,1287,-2053.083414,4,30.0,-7787.902602,4,32.0,-59.036679,-10460.862287,27.0,...,36.760212,0.278663,49.377032,0.788052,2.618744,0.115464,0.064344,0.073796,0.450601,NaN
2,810,1846.126938,8,75.0,7002.783717,8,75.0,57.850440,9566.077321,77.0,...,36.836966,0.304313,50.320741,0.808744,4.679322,0.143243,0.069234,0.077868,0.653377,NaN
3,1218,1392.075305,8,72.0,5280.461532,8,71.0,43.622227,7213.317639,73.0,...,36.836966,0.304313,50.320741,0.808744,218.647491,0.342324,0.075614,0.086918,1.009395,NaN
4,2641,-769.374640,5,48.0,-2911.892606,5,49.0,-28.752998,-4008.215270,46.0,...,36.884999,0.364215,50.772140,0.816773,69.644262,0.083889,0.073913,0.080274,1.177764,NaN

In [ ]:
df.columns

Index(['ACSTOTPOP', 'D_PM25_2', 'B_PM25_D2', 'P_PM25_D2', 'D_OZONE_2',
       'B_OZONE_D2', 'P_OZONE_D2', 'D_DSLPM_2', 'D_CANCR_2', 'P_CANCR_D2',
       'D_RESP_2', 'B_RESP_D2', 'P_RESP_D2', 'D_PTRAF_2', 'B_PTRAF_D2',
       'P_PTRAF_D2', 'D_LDPNT_2', 'B_LDPNT_D2', 'P_LDPNT_D2', 'D_PNPL_2',
       'B_PNPL_D2', 'P_PNPL_D2', 'D_PRMP_2', 'B_PRMP_D2', 'P_PRMP_D2',
       'D_PTSDF_2', 'B_PTSDF_D2', 'P_PTSDF_D2', 'PM25', 'OZONE', 'DSLPM',
       'CANCER', 'RESP', 'PTRAF', 'PRE1960PCT', 'PNPL', 'PRMP', 'PTSDF',
       'PWDIS'],
      dtype='object')

In [ ]:
pop = df['ACSTOTPOP']

In [ ]:
df = df.iloc[:,28:]

In [ ]:
df.head()

,PM25,OZONE,DSLPM,CANCER,RESP,PTRAF,PRE1960PCT,PNPL,PRMP,PTSDF,PWDIS
0,9.690899,36.760212,0.278663,49.377032,0.788052,91.015900,0.272109,0.070942,0.085201,0.586754,NaN
1,9.690899,36.760212,0.278663,49.377032,0.788052,2.618744,0.115464,0.064344,0.073796,0.450601,NaN
2,9.711240,36.836966,0.304313,50.320741,0.808744,4.679322,0.143243,0.069234,0.077868,0.653377,NaN
3,9.711240,36.836966,0.304313,50.320741,0.808744,218.647491,0.342324,0.075614,0.086918,1.009395,NaN
4,9.745683,36.884999,0.364215,50.772140,0.816773,69.644262,0.083889,0.073913,0.080274,1.177764,NaN

In [ ]:
df['ACSTOTPOP'] = pop
df.head()

,PM25,OZONE,DSLPM,CANCER,RESP,PTRAF,PRE1960PCT,PNPL,PRMP,PTSDF,PWDIS,ACSTOTPOP
0,9.690899,36.760212,0.278663,49.377032,0.788052,91.015900,0.272109,0.070942,0.085201,0.586754,NaN,636
1,9.690899,36.760212,0.278663,49.377032,0.788052,2.618744,0.115464,0.064344,0.073796,0.450601,NaN,1287
2,9.711240,36.836966,0.304313,50.320741,0.808744,4.679322,0.143243,0.069234,0.077868,0.653377,NaN,810
3,9.711240,36.836966,0.304313,50.320741,0.808744,218.647491,0.342324,0.075614,0.086918,1.009395,NaN,1218
4,9.745683,36.884999,0.364215,50.772140,0.816773,69.644262,0.083889,0.073913,0.080274,1.177764,NaN,2641

In [ ]:
for column in df:
    if column != 'ACSTOTPOP':
        df[column] *= df['ACSTOTPOP']

Adding back in LocationName

In [ ]:
df['LocationName'] = loc

Grouping rows with same LocationName. Each numerical value is given the population-weighted mean

In [ ]:
def mean_normed_by_pop(x):
    x = x.sum() / x['ACSTOTPOP'].sum()
    return x

df = df.groupby('LocationName', group_keys=False).apply(mean_normed_by_pop)

LocationName and ACSTOPOP were also normed, so they need to be dropped. The LocationName as the index is made into a column

In [ ]:
df.drop(['LocationName', 'ACSTOTPOP'], axis=1, inplace=True)
df.reset_index(inplace=True)
df = df.rename(columns = {'index':'LocationName'})
df.head()

,LocationName,PM25,OZONE,DSLPM,CANCER,RESP,PTRAF,PRE1960PCT,PNPL,PRMP,PTSDF,PWDIS
0,1001020100,9.690899,36.760212,0.278663,49.377032,0.788052,31.854621,0.167272,0.066526,0.077568,0.495631,0.000000
1,1001020200,9.711240,36.836966,0.304313,50.320741,0.808744,133.186831,0.262809,0.073066,0.083303,0.867199,0.000000
2,1001020300,9.745683,36.884999,0.364215,50.772140,0.816773,183.972683,0.078924,0.075626,0.082494,1.528117,0.000000
3,1001020400,9.761186,36.949586,0.447920,51.595926,0.835904,448.339640,0.114548,0.084700,0.087962,2.299506,0.000000
4,1001020500,9.791458,37.041363,0.499163,51.729998,0.841417,198.171325,0.000000,0.094754,0.091258,1.635841,0.000005

In [ ]:
df.tail()

,LocationName,PM25,OZONE,DSLPM,CANCER,RESP,PTRAF,PRE1960PCT,PNPL,PRMP,PTSDF,PWDIS
73294,72153750501,0.0,0.0,0.053854,17.372062,0.260988,62.944027,0.009816,0.056186,0.720871,0.783596,0.020576
73295,72153750502,0.0,0.0,0.058167,17.482087,0.260866,730.916547,0.072855,0.058919,0.851300,0.747859,0.024960
73296,72153750503,0.0,0.0,0.049858,17.283555,0.258829,160.747911,0.067748,0.056212,0.604643,0.506445,0.006058
73297,72153750601,0.0,0.0,0.055070,17.199448,0.258637,94.865143,0.061086,0.065172,1.636494,0.397525,0.016798
73298,72153750602,0.0,0.0,0.057248,16.929739,0.256232,202.266125,0.167015,0.057998,0.557440,0.299630,0.000496

In [ ]:
df.to_csv('C:/Users/butle/hp/Capstone_Two/data/interim/EJSCREEN_2020_interim.csv')

In [ ]:
health_2022 = 'C:/Users/butle/hp/Capstone_Two/data/raw/PLACES__Local_Data_for_Better_Health__Census_Tract_Data_2022_release.csv'
df2 = pd.read_csv(health_2022)

In [ ]:
df2.head()

,Year,StateAbbr,StateDesc,CountyName,CountyFIPS,LocationName,DataSource,Category,Measure,Data_Value_Unit,...,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text
0,2020,AL,Alabama,Autauga,1001,1001020200,BRFSS,Health Outcomes,Chronic obstructive pulmonary disease among ad...,%,...,NaN,6.8,8.5,2170,POINT (-86.47338874 32.47425254),1001020200,HLTHOUT,COPD,CrdPrv,COPD
1,2020,AL,Alabama,Autauga,1001,1001020400,BRFSS,Health Outcomes,Obesity among adults aged >=18 years,%,...,NaN,31.5,35.0,4386,POINT (-86.44370417 32.47203959),1001020400,HLTHOUT,OBESITY,CrdPrv,Obesity
2,2020,AL,Alabama,Autauga,1001,1001021000,BRFSS,Health Outcomes,Obesity among adults aged >=18 years,%,...,NaN,39.3,41.2,2894,POINT (-86.75607371 32.60894544),1001021000,HLTHOUT,OBESITY,CrdPrv,Obesity
3,2020,AL,Alabama,Baldwin,1003,1003010905,BRFSS,Health Outcomes,Stroke among adults aged >=18 years,%,...,NaN,2.7,3.2,8011,POINT (-87.75682132 30.53592075),1003010905,HLTHOUT,STROKE,CrdPrv,Stroke
4,2020,AL,Alabama,Baldwin,1003,1003010906,BRFSS,Health Outcomes,Depression among adults aged >=18 years,%,...,NaN,26.3,28.9,4302,POINT (-87.68753351 30.56418914),1003010906,HLTHOUT,DEPRESSION,CrdPrv,Depression

In [ ]:
df2.shape

(2161543, 23)

In [ ]:
df2.tail()

,Year,StateAbbr,StateDesc,CountyName,CountyFIPS,LocationName,DataSource,Category,Measure,Data_Value_Unit,...,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text
2161538,2020,WI,Wisconsin,Waukesha,55133,55133204002,BRFSS,Prevention,"Fecal occult blood test, sigmoidoscopy, or col...",%,...,NaN,59.0,64.9,5479,POINT (-88.4824858 42.88723077),55133204002,PREVENT,COLON_SCREEN,CrdPrv,Colorectal Cancer Screening
2161539,2020,WI,Wisconsin,Rock,55105,55105002700,BRFSS,Health Status,Physical health not good for >=14 days among a...,%,...,NaN,9.6,11.6,2571,POINT (-89.24626648 42.548431),55105002700,HLTHSTAT,PHLTH,CrdPrv,Physical Health
2161540,2020,WI,Wisconsin,Waukesha,55133,55133203200,BRFSS,Health Outcomes,Cancer (excluding skin cancer) among adults ag...,%,...,NaN,7.0,7.8,4106,POINT (-88.31331246 43.07069963),55133203200,HLTHOUT,CANCER,CrdPrv,Cancer (except skin)
2161541,2020,WI,Wisconsin,Waukesha,55133,55133203101,BRFSS,Prevention,Visits to dentist or dental clinic among adult...,%,...,NaN,74.7,80.6,6536,POINT (-88.27895206 43.04127835),55133203101,PREVENT,DENTAL,CrdPrv,Dental Visit
2161542,2020,WI,Wisconsin,Waukesha,55133,55133200400,BRFSS,Health Outcomes,Chronic kidney disease among adults aged >=18 ...,%,...,NaN,2.1,2.5,6582,POINT (-88.10191212 43.13413751),55133200400,HLTHOUT,KIDNEY,CrdPrv,Chronic Kidney Disease

In [ ]:
df2 = df2[df2['Category'] == 'Health Outcomes']

In [ ]:
df2.shape

(936284, 23)

In [ ]:
df[df['LocationName'] == 1001020200]

,LocationName,PM25,OZONE,DSLPM,CANCER,RESP,PTRAF,PRE1960PCT,PNPL,PRMP,PTSDF,PWDIS
1,1001020200,9.71124,36.836966,0.304313,50.320741,0.808744,133.186831,0.262809,0.073066,0.083303,0.867199,0.0

In [ ]:
df[df['LocationName'] == 55133200400]

,LocationName,PM25,OZONE,DSLPM,CANCER,RESP,PTRAF,PRE1960PCT,PNPL,PRMP,PTSDF,PWDIS
72123,55133200400,7.514909,43.06825,0.387525,22.748623,0.292665,180.213938,0.221044,0.222978,1.888956,1.393416,0.011332

In [ ]:
df2['LocationName'].isin(df['LocationName']).value_counts()

True     936104
False       180
Name: LocationName, dtype: int64

In [ ]:
df['LocationName'].isin(df2['LocationName']).value_counts()

True     72323
False      976
Name: LocationName, dtype: int64

Not all of the LocationNames in the health data are present in the environmental data. Slicing the health database

In [ ]:
common_rows_health = df2.loc[df2['LocationName'].isin(df['LocationName'])]
common_rows_health.head()

,Year,StateAbbr,StateDesc,CountyName,CountyFIPS,LocationName,DataSource,Category,Measure,Data_Value_Unit,...,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text
0,2020,AL,Alabama,Autauga,1001,1001020200,BRFSS,Health Outcomes,Chronic obstructive pulmonary disease among ad...,%,...,NaN,6.8,8.5,2170,POINT (-86.47338874 32.47425254),1001020200,HLTHOUT,COPD,CrdPrv,COPD
1,2020,AL,Alabama,Autauga,1001,1001020400,BRFSS,Health Outcomes,Obesity among adults aged >=18 years,%,...,NaN,31.5,35.0,4386,POINT (-86.44370417 32.47203959),1001020400,HLTHOUT,OBESITY,CrdPrv,Obesity
2,2020,AL,Alabama,Autauga,1001,1001021000,BRFSS,Health Outcomes,Obesity among adults aged >=18 years,%,...,NaN,39.3,41.2,2894,POINT (-86.75607371 32.60894544),1001021000,HLTHOUT,OBESITY,CrdPrv,Obesity
3,2020,AL,Alabama,Baldwin,1003,1003010905,BRFSS,Health Outcomes,Stroke among adults aged >=18 years,%,...,NaN,2.7,3.2,8011,POINT (-87.75682132 30.53592075),1003010905,HLTHOUT,STROKE,CrdPrv,Stroke
4,2020,AL,Alabama,Baldwin,1003,1003010906,BRFSS,Health Outcomes,Depression among adults aged >=18 years,%,...,NaN,26.3,28.9,4302,POINT (-87.68753351 30.56418914),1003010906,HLTHOUT,DEPRESSION,CrdPrv,Depression

In [ ]:
common_rows_health.shape

(936104, 23)

In [ ]:
df3 = common_rows_health
df3.Category.nunique()

1

In [ ]:
df3.Category.unique()

array(['Health Outcomes'], dtype=object)

In [ ]:
df3.shape

(936104, 23)

In [ ]:
df3.DataSource.nunique()

1

In [ ]:
df3.DataSource.unique()

array(['BRFSS'], dtype=object)

In [ ]:
df3.Data_Value_Footnote_Symbol.nunique()

0

In [ ]:
df3.Data_Value_Footnote.nunique()

0

In [ ]:
df3.DataValueTypeID.unique()

array(['CrdPrv'], dtype=object)

In [ ]:
df3.DataValueTypeID.nunique()

1

Getting rid of unnecessary columns

In [ ]:
df3.head()

,Year,StateAbbr,StateDesc,CountyName,CountyFIPS,LocationName,DataSource,Category,Measure,Data_Value_Unit,...,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text
0,2020,AL,Alabama,Autauga,1001,1001020200,BRFSS,Health Outcomes,Chronic obstructive pulmonary disease among ad...,%,...,NaN,6.8,8.5,2170,POINT (-86.47338874 32.47425254),1001020200,HLTHOUT,COPD,CrdPrv,COPD
1,2020,AL,Alabama,Autauga,1001,1001020400,BRFSS,Health Outcomes,Obesity among adults aged >=18 years,%,...,NaN,31.5,35.0,4386,POINT (-86.44370417 32.47203959),1001020400,HLTHOUT,OBESITY,CrdPrv,Obesity
2,2020,AL,Alabama,Autauga,1001,1001021000,BRFSS,Health Outcomes,Obesity among adults aged >=18 years,%,...,NaN,39.3,41.2,2894,POINT (-86.75607371 32.60894544),1001021000,HLTHOUT,OBESITY,CrdPrv,Obesity
3,2020,AL,Alabama,Baldwin,1003,1003010905,BRFSS,Health Outcomes,Stroke among adults aged >=18 years,%,...,NaN,2.7,3.2,8011,POINT (-87.75682132 30.53592075),1003010905,HLTHOUT,STROKE,CrdPrv,Stroke
4,2020,AL,Alabama,Baldwin,1003,1003010906,BRFSS,Health Outcomes,Depression among adults aged >=18 years,%,...,NaN,26.3,28.9,4302,POINT (-87.68753351 30.56418914),1003010906,HLTHOUT,DEPRESSION,CrdPrv,Depression

In [ ]:
df3.shape

(936104, 23)

In [ ]:
df3.MeasureId.unique()

array(['COPD', 'OBESITY', 'STROKE', 'DEPRESSION', 'CASTHMA', 'TEETHLOST',
       'ARTHRITIS', 'DIABETES', 'BPHIGH', 'CANCER', 'CHD', 'KIDNEY',
       'HIGHCHOL'], dtype=object)

In [ ]:
df3.drop(['StateDesc', 'Year', 'CountyFIPS', 'Geolocation', 'DataValueTypeID', 'Data_Value_Footnote','Data_Value_Footnote_Symbol', 'DataSource'], axis=1, inplace=True)

C:\Users\butle\AppData\Local\Temp\ipykernel_15896\1140354131.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.drop(['StateDesc', 'Year', 'CountyFIPS', 'Geolocation', 'DataValueTypeID', 'Data_Value_Footnote','Data_Value_Footnote_Symbol', 'DataSource'], axis=1, inplace=True)

In [ ]:
df3.head()

,StateAbbr,CountyName,LocationName,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,LocationID,CategoryID,MeasureId,Short_Question_Text
0,AL,Autauga,1001020200,Health Outcomes,Chronic obstructive pulmonary disease among ad...,%,Crude prevalence,7.6,6.8,8.5,2170,1001020200,HLTHOUT,COPD,COPD
1,AL,Autauga,1001020400,Health Outcomes,Obesity among adults aged >=18 years,%,Crude prevalence,33.2,31.5,35.0,4386,1001020400,HLTHOUT,OBESITY,Obesity
2,AL,Autauga,1001021000,Health Outcomes,Obesity among adults aged >=18 years,%,Crude prevalence,40.3,39.3,41.2,2894,1001021000,HLTHOUT,OBESITY,Obesity
3,AL,Baldwin,1003010905,Health Outcomes,Stroke among adults aged >=18 years,%,Crude prevalence,2.9,2.7,3.2,8011,1003010905,HLTHOUT,STROKE,Stroke
4,AL,Baldwin,1003010906,Health Outcomes,Depression among adults aged >=18 years,%,Crude prevalence,27.6,26.3,28.9,4302,1003010906,HLTHOUT,DEPRESSION,Depression

In [ ]:
df3 = df3.iloc[:, 2:]

In [ ]:
df3.head()

,LocationName,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,LocationID,CategoryID,MeasureId,Short_Question_Text
0,1001020200,Health Outcomes,Chronic obstructive pulmonary disease among ad...,%,Crude prevalence,7.6,6.8,8.5,2170,1001020200,HLTHOUT,COPD,COPD
1,1001020400,Health Outcomes,Obesity among adults aged >=18 years,%,Crude prevalence,33.2,31.5,35.0,4386,1001020400,HLTHOUT,OBESITY,Obesity
2,1001021000,Health Outcomes,Obesity among adults aged >=18 years,%,Crude prevalence,40.3,39.3,41.2,2894,1001021000,HLTHOUT,OBESITY,Obesity
3,1003010905,Health Outcomes,Stroke among adults aged >=18 years,%,Crude prevalence,2.9,2.7,3.2,8011,1003010905,HLTHOUT,STROKE,Stroke
4,1003010906,Health Outcomes,Depression among adults aged >=18 years,%,Crude prevalence,27.6,26.3,28.9,4302,1003010906,HLTHOUT,DEPRESSION,Depression

In [ ]:
df3['Crude_prevalence'] = df3['Data_Value']

In [ ]:
df3['Category'].unique()

array(['Health Outcomes'], dtype=object)

In [ ]:
df3.shape

(936104, 14)

In [ ]:
df3.head()

,LocationName,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,LocationID,CategoryID,MeasureId,Short_Question_Text,Crude_prevalence
0,1001020200,Health Outcomes,Chronic obstructive pulmonary disease among ad...,%,Crude prevalence,7.6,6.8,8.5,2170,1001020200,HLTHOUT,COPD,COPD,7.6
1,1001020400,Health Outcomes,Obesity among adults aged >=18 years,%,Crude prevalence,33.2,31.5,35.0,4386,1001020400,HLTHOUT,OBESITY,Obesity,33.2
2,1001021000,Health Outcomes,Obesity among adults aged >=18 years,%,Crude prevalence,40.3,39.3,41.2,2894,1001021000,HLTHOUT,OBESITY,Obesity,40.3
3,1003010905,Health Outcomes,Stroke among adults aged >=18 years,%,Crude prevalence,2.9,2.7,3.2,8011,1003010905,HLTHOUT,STROKE,Stroke,2.9
4,1003010906,Health Outcomes,Depression among adults aged >=18 years,%,Crude prevalence,27.6,26.3,28.9,4302,1003010906,HLTHOUT,DEPRESSION,Depression,27.6

In [ ]:
df3 = df3.drop(['Category', 'Measure','Data_Value_Unit','Data_Value','LocationID','CategoryID'],axis=1)

In [ ]:
df3.head()

,LocationName,Data_Value_Type,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,MeasureId,Short_Question_Text,Crude_prevalence
0,1001020200,Crude prevalence,6.8,8.5,2170,COPD,COPD,7.6
1,1001020400,Crude prevalence,31.5,35.0,4386,OBESITY,Obesity,33.2
2,1001021000,Crude prevalence,39.3,41.2,2894,OBESITY,Obesity,40.3
3,1003010905,Crude prevalence,2.7,3.2,8011,STROKE,Stroke,2.9
4,1003010906,Crude prevalence,26.3,28.9,4302,DEPRESSION,Depression,27.6

In [ ]:
df3.tail()

,LocationName,Data_Value_Type,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,MeasureId,Short_Question_Text,Crude_prevalence
2161530,55109120202,Crude prevalence,1.6,1.9,5161,KIDNEY,Chronic Kidney Disease,1.7
2161532,56043000301,Crude prevalence,17.3,19.5,2665,DEPRESSION,Depression,18.4
2161536,55127001602,Crude prevalence,5.6,6.8,5643,CHD,Coronary Heart Disease,6.2
2161540,55133203200,Crude prevalence,7.0,7.8,4106,CANCER,Cancer (except skin),7.4
2161542,55133200400,Crude prevalence,2.1,2.5,6582,KIDNEY,Chronic Kidney Disease,2.3

In [ ]:
df3 = df3.drop(['Data_Value_Type', 'Short_Question_Text'], axis=1)

In [ ]:
df3.columns

Index(['LocationName', 'Low_Confidence_Limit', 'High_Confidence_Limit',
       'TotalPopulation', 'MeasureId', 'Crude_prevalence'],
      dtype='object')

In [ ]:
col = df3.columns.to_list()
col

['LocationName',
 'Low_Confidence_Limit',
 'High_Confidence_Limit',
 'TotalPopulation',
 'MeasureId',
 'Crude_prevalence']

In [ ]:
cols = ['LocationName', 'MeasureId', 'Crude_prevalence','Low_Confidence_Limit', 'High_Confidence_Limit',  'TotalPopulation'  ]
cols

['LocationName',
 'MeasureId',
 'Crude_prevalence',
 'Low_Confidence_Limit',
 'High_Confidence_Limit',
 'TotalPopulation']

In [ ]:
df3 = df3[cols]
df3.columns

Index(['LocationName', 'MeasureId', 'Crude_prevalence', 'Low_Confidence_Limit',
       'High_Confidence_Limit', 'TotalPopulation'],
      dtype='object')

In [ ]:
df3.head()

,LocationName,MeasureId,Crude_prevalence,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation
0,1001020200,COPD,7.6,6.8,8.5,2170
1,1001020400,OBESITY,33.2,31.5,35.0,4386
2,1001021000,OBESITY,40.3,39.3,41.2,2894
3,1003010905,STROKE,2.9,2.7,3.2,8011
4,1003010906,DEPRESSION,27.6,26.3,28.9,4302

In [ ]:
df3[df3['MeasureId'] == 'COPD'].shape

(72323, 6)

In [ ]:
df3[df3['MeasureId'] == 'Obesity'].shape

(0, 6)

In [ ]:
df3.MeasureId.unique()

array(['COPD', 'OBESITY', 'STROKE', 'DEPRESSION', 'CASTHMA', 'TEETHLOST',
       'ARTHRITIS', 'DIABETES', 'BPHIGH', 'CANCER', 'CHD', 'KIDNEY',
       'HIGHCHOL'], dtype=object)

In [ ]:
outcomes = df3.copy()

In [ ]:
combined = pd.merge(outcomes,df)
combined.rename({'LocationName': 'CensusTract', 'TotalPopulation':'TotalPopHealth',"CANCER": "AirToxicsRisk", 'DSLPM':'DieselPM'}, axis=1, inplace=True)
combined.head()

,CensusTract,MeasureId,Crude_prevalence,Low_Confidence_Limit,High_Confidence_Limit,TotalPopHealth,PM25,OZONE,DieselPM,AirToxicsRisk,RESP,PTRAF,PRE1960PCT,PNPL,PRMP,PTSDF,PWDIS
0,1001020200,COPD,7.6,6.8,8.5,2170,9.71124,36.836966,0.304313,50.320741,0.808744,133.186831,0.262809,0.073066,0.083303,0.867199,0.0
1,1001020200,CHD,5.9,5.5,6.3,2170,9.71124,36.836966,0.304313,50.320741,0.808744,133.186831,0.262809,0.073066,0.083303,0.867199,0.0
2,1001020200,BPHIGH,43.6,42.3,44.7,2170,9.71124,36.836966,0.304313,50.320741,0.808744,133.186831,0.262809,0.073066,0.083303,0.867199,0.0
3,1001020200,TEETHLOST,19.4,14.4,25.0,2170,9.71124,36.836966,0.304313,50.320741,0.808744,133.186831,0.262809,0.073066,0.083303,0.867199,0.0
4,1001020200,CANCER,5.0,4.8,5.2,2170,9.71124,36.836966,0.304313,50.320741,0.808744,133.186831,0.262809,0.073066,0.083303,0.867199,0.0

Re-indexing as CensusTract will not be a feature.

In [ ]:
combined.set_index('CensusTract', inplace=True)

Making a separate dataframe for each health concern.

In [ ]:
asthma = combined[combined['MeasureId'] == 'CASTHMA']
asthma = asthma.drop('MeasureId', axis = 1)
asthma = asthma.rename({'Crude_prevalence': "Asthma_prevalence"}, axis=1)
asthma.head()

,Asthma_prevalence,Low_Confidence_Limit,High_Confidence_Limit,TotalPopHealth,PM25,OZONE,DieselPM,AirToxicsRisk,RESP,PTRAF,PRE1960PCT,PNPL,PRMP,PTSDF,PWDIS
CensusTract,,,,,,,,,,,,,,,
1001020200,10.9,10.4,11.4,2170,9.711240,36.836966,0.304313,50.320741,0.808744,133.186831,0.262809,0.073066,0.083303,0.867199,0.000000e+00
1001020400,8.8,8.4,9.3,4386,9.761186,36.949586,0.447920,51.595926,0.835904,448.339640,0.114548,0.084700,0.087962,2.299506,0.000000e+00
1001021000,10.3,10.0,10.6,2894,9.292441,35.908669,0.160869,45.941855,0.733025,4.501463,0.166322,0.024765,0.222258,0.042577,2.861655e-04
1003010905,9.4,9.1,9.8,8011,8.402913,37.153641,0.233462,35.633327,0.528960,224.749567,0.099045,0.020701,0.528059,0.078937,1.444756e-04
1003010906,9.9,9.4,10.5,4302,8.414995,36.808459,0.249121,36.136884,0.539997,103.595218,0.063483,0.021972,0.614922,0.063767,1.033556e-07

In [ ]:
asthma.shape

(72323, 15)

In [ ]:
asthma.describe

NameError: name 'asthma' is not defined

In [ ]:
kidney = combined[combined['MeasureId'] == 'KIDNEY']  
kidney = kidney.drop('MeasureId', axis = 1)
kidney = kidney.rename({'Crude_prevalence': "Kidney_prevalence"}, axis=1)
kidney.head()

,Kidney_prevalence,Low_Confidence_Limit,High_Confidence_Limit,TotalPopHealth,PM25,OZONE,DieselPM,AirToxicsRisk,RESP,PTRAF,PRE1960PCT,PNPL,PRMP,PTSDF,PWDIS
CensusTract,,,,,,,,,,,,,,,
1001020200,3.1,2.9,3.3,2170,9.711240,36.836966,0.304313,50.320741,0.808744,133.186831,0.262809,0.073066,0.083303,0.867199,0.000000e+00
1001020400,2.9,2.7,3.2,4386,9.761186,36.949586,0.447920,51.595926,0.835904,448.339640,0.114548,0.084700,0.087962,2.299506,0.000000e+00
1001021000,3.3,3.2,3.4,2894,9.292441,35.908669,0.160869,45.941855,0.733025,4.501463,0.166322,0.024765,0.222258,0.042577,2.861655e-04
1003010905,2.7,2.6,2.9,8011,8.402913,37.153641,0.233462,35.633327,0.528960,224.749567,0.099045,0.020701,0.528059,0.078937,1.444756e-04
1003010906,3.3,3.0,3.6,4302,8.414995,36.808459,0.249121,36.136884,0.539997,103.595218,0.063483,0.021972,0.614922,0.063767,1.033556e-07

In [ ]:
kidney.shape

(72323, 15)

In [ ]:
chd = combined[combined['MeasureId'] == 'CHD']  
chd = chd.drop('MeasureId', axis = 1)
chd = chd.rename({'Crude_prevalence': "CHD_prevalence"}, axis=1)
chd.head()

,CHD_prevalence,Low_Confidence_Limit,High_Confidence_Limit,TotalPopHealth,PM25,OZONE,DieselPM,AirToxicsRisk,RESP,PTRAF,PRE1960PCT,PNPL,PRMP,PTSDF,PWDIS
CensusTract,,,,,,,,,,,,,,,
1001020200,5.9,5.5,6.3,2170,9.711240,36.836966,0.304313,50.320741,0.808744,133.186831,0.262809,0.073066,0.083303,0.867199,0.000000e+00
1001020400,7.1,6.4,7.9,4386,9.761186,36.949586,0.447920,51.595926,0.835904,448.339640,0.114548,0.084700,0.087962,2.299506,0.000000e+00
1001021000,7.3,7.0,7.7,2894,9.292441,35.908669,0.160869,45.941855,0.733025,4.501463,0.166322,0.024765,0.222258,0.042577,2.861655e-04
1003010905,6.4,6.0,6.8,8011,8.402913,37.153641,0.233462,35.633327,0.528960,224.749567,0.099045,0.020701,0.528059,0.078937,1.444756e-04
1003010906,7.9,7.2,8.6,4302,8.414995,36.808459,0.249121,36.136884,0.539997,103.595218,0.063483,0.021972,0.614922,0.063767,1.033556e-07

In [ ]:
stroke = combined[combined['MeasureId'] == 'STROKE']
stroke = stroke.drop('MeasureId', axis = 1)
stroke = stroke.rename({'Crude_prevalence': "Stroke_prevalence"}, axis=1)
stroke.head()

,Stroke_prevalence,Low_Confidence_Limit,High_Confidence_Limit,TotalPopHealth,PM25,OZONE,DieselPM,AirToxicsRisk,RESP,PTRAF,PRE1960PCT,PNPL,PRMP,PTSDF,PWDIS
CensusTract,,,,,,,,,,,,,,,
1001020200,3.7,3.4,4.1,2170,9.711240,36.836966,0.304313,50.320741,0.808744,133.186831,0.262809,0.073066,0.083303,0.867199,0.000000e+00
1001020400,3.0,2.6,3.5,4386,9.761186,36.949586,0.447920,51.595926,0.835904,448.339640,0.114548,0.084700,0.087962,2.299506,0.000000e+00
1001021000,3.8,3.5,4.0,2894,9.292441,35.908669,0.160869,45.941855,0.733025,4.501463,0.166322,0.024765,0.222258,0.042577,2.861655e-04
1003010905,2.9,2.7,3.2,8011,8.402913,37.153641,0.233462,35.633327,0.528960,224.749567,0.099045,0.020701,0.528059,0.078937,1.444756e-04
1003010906,3.7,3.3,4.2,4302,8.414995,36.808459,0.249121,36.136884,0.539997,103.595218,0.063483,0.021972,0.614922,0.063767,1.033556e-07

In [ ]:
cancer = combined[combined['MeasureId'] == 'CANCER']
cancer = cancer.drop('MeasureId', axis = 1)
cancer = cancer.rename({'Crude_prevalence': "Cancer_prevalence"}, axis=1)
cancer.head()

,Cancer_prevalence,Low_Confidence_Limit,High_Confidence_Limit,TotalPopHealth,PM25,OZONE,DieselPM,AirToxicsRisk,RESP,PTRAF,PRE1960PCT,PNPL,PRMP,PTSDF,PWDIS
CensusTract,,,,,,,,,,,,,,,
1001020200,5.0,4.8,5.2,2170,9.711240,36.836966,0.304313,50.320741,0.808744,133.186831,0.262809,0.073066,0.083303,0.867199,0.000000e+00
1001020400,8.0,7.5,8.4,4386,9.761186,36.949586,0.447920,51.595926,0.835904,448.339640,0.114548,0.084700,0.087962,2.299506,0.000000e+00
1001021000,6.2,6.0,6.3,2894,9.292441,35.908669,0.160869,45.941855,0.733025,4.501463,0.166322,0.024765,0.222258,0.042577,2.861655e-04
1003010905,6.1,5.9,6.3,8011,8.402913,37.153641,0.233462,35.633327,0.528960,224.749567,0.099045,0.020701,0.528059,0.078937,1.444756e-04
1003010906,7.1,6.7,7.5,4302,8.414995,36.808459,0.249121,36.136884,0.539997,103.595218,0.063483,0.021972,0.614922,0.063767,1.033556e-07

In [ ]:
copd = combined[combined['MeasureId'] == 'COPD']
copd = copd.drop('MeasureId', axis = 1)
copd = copd.rename({'Crude_prevalence': "COPD_prevalence"}, axis=1)
copd.head()

,COPD_prevalence,Low_Confidence_Limit,High_Confidence_Limit,TotalPopHealth,PM25,OZONE,DieselPM,AirToxicsRisk,RESP,PTRAF,PRE1960PCT,PNPL,PRMP,PTSDF,PWDIS
CensusTract,,,,,,,,,,,,,,,
1001020200,7.6,6.8,8.5,2170,9.711240,36.836966,0.304313,50.320741,0.808744,133.186831,0.262809,0.073066,0.083303,0.867199,0.000000e+00
1001020400,7.2,6.0,8.6,4386,9.761186,36.949586,0.447920,51.595926,0.835904,448.339640,0.114548,0.084700,0.087962,2.299506,0.000000e+00
1001021000,9.2,8.5,9.9,2894,9.292441,35.908669,0.160869,45.941855,0.733025,4.501463,0.166322,0.024765,0.222258,0.042577,2.861655e-04
1003010905,7.8,7.1,8.6,8011,8.402913,37.153641,0.233462,35.633327,0.528960,224.749567,0.099045,0.020701,0.528059,0.078937,1.444756e-04
1003010906,9.8,8.6,11.2,4302,8.414995,36.808459,0.249121,36.136884,0.539997,103.595218,0.063483,0.021972,0.614922,0.063767,1.033556e-07

**Environmental risk columns defined** 

PM25 = PM2.5 level in air  

Ozone = Ozone level in air  

DieselPM = Diesel particulate matter level in air  

AirToxicsRisk = Air toxics cancer risk  

RESP = Air toxics respiratory hazard index  

PTRAF = Traffic proximity and volume  

PRE1960PCT = % pre-1960 housing (lead paint indicator)  

PNPL = Proximity to National Priorities List (NPL) [superfund] sites  

PRMP = Proximity to Risk Management Plan (RMP) facilities, facilities that use extremely 
       hazardous substances  
       
PTSDF = Proximity to Treatment Storage and Disposal (TSDF) facilities  

PWDIS = Indicator for major direct dischargers to water

Making a dataset for each health concern

In [ ]:
copd.to_csv('C:/Users/butle/hp/Capstone_Two/data/interim/copd_data.csv')

In [ ]:
asthma.to_csv('C:/Users/butle/hp/Capstone_Two/data/interim/asthma_data.csv')

In [ ]:
stroke.to_csv('C:/Users/butle/hp/Capstone_Two/data/interim/stroke_data.csv')

In [ ]:
cancer.to_csv('C:/Users/butle/hp/Capstone_Two/data/interim/cancer_data.csv')

In [ ]:
chd.to_csv('C:/Users/butle/hp/Capstone_Two/data/interim/chd_data.csv')

In [ ]:
kidney.to_csv('C:/Users/butle/hp/Capstone_Two/data/interim/kidney_data.csv')