In [3]:
import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
df = pd.read_json('/data/raw/test_data.json', lines=True)

In [5]:
df.head()

,image_url,image_path,brand,product_title,class_label,color
0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN
1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN
2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN
3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN
4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN

In [6]:
df.tail()

,image_url,image_path,brand,product_title,class_label,color
7495,https://rukminim1.flixcart.com/image/309/371/k...,images/test/7495.jpeg,aaliya fashion,Women Embroidered Rayon Anarkali Kurta,women_kurta,Purple
7496,https://m.media-amazon.com/images/I/71xJFbz+uV...,images/test/7496.jpeg,AnjuShree Choice,Women's Rayon & Viscose Regular Stitched Kurta,women_kurta,NaN
7497,https://m.media-amazon.com/images/I/71CawDGew+...,images/test/7497.jpeg,W for Woman,Women's cotton straight Kurta,women_kurta,NaN
7498,https://m.media-amazon.com/images/I/61VBgoJQAt...,images/test/7498.jpeg,Vaamsi,Crepe Printed Kurti (VPK1805_Purple_Free Size),women_kurta,NaN
7499,https://m.media-amazon.com/images/I/612gggywBm...,images/test/7499.jpeg,Vbuyz,Women's Rayon Regular Kurta,women_kurta,NaN

In [7]:
df.shape

(7500, 6)

In [8]:
df.class_label.unique()

array(['saree', 'blouse', 'dhoti_pants', 'dupattas', 'gowns', 'kurta_men',
       'leggings_and_salwars', 'lehenga', 'mojaris_men', 'mojaris_women',
       'nehru_jackets', 'palazzos', 'petticoats', 'sherwanis',
       'women_kurta'], dtype=object)

In [9]:
df_revised = df.copy()

In [13]:
df_revised.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   image_url      7500 non-null   object
 1   image_path     7500 non-null   object
 2   brand          7500 non-null   object
 3   product_title  7500 non-null   object
 4   class_label    7500 non-null   object
 5   color          905 non-null    object
dtypes: object(6)
memory usage: 351.7+ KB

In [14]:
df_revised = df_revised.reset_index(names='number')

In [15]:
df_revised.head()

,number,image_url,image_path,brand,product_title,class_label,color
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN

In [16]:
df_revised.tail()

,number,image_url,image_path,brand,product_title,class_label,color
7495,7495,https://rukminim1.flixcart.com/image/309/371/k...,images/test/7495.jpeg,aaliya fashion,Women Embroidered Rayon Anarkali Kurta,women_kurta,Purple
7496,7496,https://m.media-amazon.com/images/I/71xJFbz+uV...,images/test/7496.jpeg,AnjuShree Choice,Women's Rayon & Viscose Regular Stitched Kurta,women_kurta,NaN
7497,7497,https://m.media-amazon.com/images/I/71CawDGew+...,images/test/7497.jpeg,W for Woman,Women's cotton straight Kurta,women_kurta,NaN
7498,7498,https://m.media-amazon.com/images/I/61VBgoJQAt...,images/test/7498.jpeg,Vaamsi,Crepe Printed Kurti (VPK1805_Purple_Free Size),women_kurta,NaN
7499,7499,https://m.media-amazon.com/images/I/612gggywBm...,images/test/7499.jpeg,Vbuyz,Women's Rayon Regular Kurta,women_kurta,NaN

In [17]:
columns = ['kurta', 'women', 'men', 'dhoti', 'saree', 'sherwani', 'palazzo', 
           'mojari', 'nehru', 'legging', 'salwar', 'petticoat', 'blouse', 
           'dupatta', 'gown','lehenga']

In [18]:
for column in columns:
    df_revised[str(column)] = df_revised.product_title.str.contains(str(column), flags=re.IGNORECASE)

In [19]:
df_revised.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,women,men,...,palazzo,mojari,nehru,legging,salwar,petticoat,blouse,dupatta,gown,lehenga
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,True,True,...,False,False,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN,False,True,True,...,False,False,False,False,False,False,True,False,False,False
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN,False,True,True,...,False,False,False,False,False,False,True,False,False,False
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN,False,True,True,...,False,False,False,False,False,False,True,False,False,False
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN,False,True,True,...,False,False,False,False,False,False,True,False,False,False

In [20]:
df_revised_men = df_revised[df_revised.men == True]
df_revised_men.shape

(5466, 23)

In [21]:
df_revised_men.loc[0]

number                                                           0
image_url        https://m.media-amazon.com/images/I/71NZQ-aaAS...
image_path                                      images/test/0.jpeg
brand                                      TANTUJA BENGAL HANDLOOM
product_title    (A Govt. of West Bengal Enterprises) Handloom ...
class_label                                                  saree
color                                                          NaN
kurta                                                        False
women                                                         True
men                                                           True
dhoti                                                        False
saree                                                        False
sherwani                                                     False
palazzo                                                      False
mojari                                                       False
nehru                                                        False
legging                                                      False
salwar                                                       False
petticoat                                                    False
blouse                                                       False
dupatta                                                      False
gown                                                         False
lehenga                                                      False
Name: 0, dtype: object

In [22]:
df_revised.columns

Index(['number', 'image_url', 'image_path', 'brand', 'product_title',
       'class_label', 'color', 'kurta', 'women', 'men', 'dhoti', 'saree',
       'sherwani', 'palazzo', 'mojari', 'nehru', 'legging', 'salwar',
       'petticoat', 'blouse', 'dupatta', 'gown', 'lehenga'],
      dtype='object')

In [23]:
c1 = (df_revised['men'] == True) 
c2 = (df_revised['women'] == True)

df_revised.loc[c1 & c2, 'men'] = False

In [24]:
df_revised_men = df_revised[df_revised.men == True]

In [25]:
df_revised_men.shape

(1581, 23)

In [26]:
df_revised_men.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,women,men,...,palazzo,mojari,nehru,legging,salwar,petticoat,blouse,dupatta,gown,lehenga
645,645,https://m.media-amazon.com/images/I/81Q3XClKdX...,images/test/645.jpeg,ARUNA,KULLU Jacket Nehru Jacket Reversal Both Side U...,blouse,NaN,False,False,True,...,False,False,True,False,False,False,False,False,False,False
1000,1000,https://rukminim1.flixcart.com/image/309/371/j...,images/test/1000.jpeg,N/A,ARYA Welcro Solid Men Dhoti,dhoti_pants,N/A,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1005,1005,https://m.media-amazon.com/images/I/61z0+oMvE8...,images/test/1005.jpeg,Larwa,Men's Silk Solid Dhoti,dhoti_pants,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1008,1008,https://rukminim1.flixcart.com/image/309/371/k...,images/test/1008.jpeg,N/A,GOLFER Men Stylish Ethnic Dupion Dhoti (Maroon...,dhoti_pants,N/A,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1009,1009,https://rukminim1.flixcart.com/image/309/371/j...,images/test/1009.jpeg,N/A,GREEN TEE Men Dhoti,dhoti_pants,N/A,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [27]:
df_revised.iloc[2,4]

"Women's Georgette Net Embroidered Saree with Blouse Piece (Black)"

In [28]:
df_revised.iloc[1,4]

"Women's Silk Saree With Blouse Piece"

In [29]:
df_revised.loc[1000]

number                                                        1000
image_url        https://rukminim1.flixcart.com/image/309/371/j...
image_path                                   images/test/1000.jpeg
brand                                                          N/A
product_title                          ARYA Welcro Solid Men Dhoti
class_label                                            dhoti_pants
color                                                          N/A
kurta                                                        False
women                                                        False
men                                                           True
dhoti                                                         True
saree                                                        False
sherwani                                                     False
palazzo                                                      False
mojari                                                       False
nehru                                                        False
legging                                                      False
salwar                                                       False
petticoat                                                    False
blouse                                                       False
dupatta                                                      False
gown                                                         False
lehenga                                                      False
Name: 1000, dtype: object

In [30]:
df_revised.iloc[1000,4]

'ARYA Welcro Solid Men Dhoti'

In [31]:
df_revised['women_kurta'] = [False]* 7500

In [32]:
df_revised['kurta_men'] = [False]* 7500

In [33]:
df_revised.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,women,men,...,nehru,legging,salwar,petticoat,blouse,dupatta,gown,lehenga,women_kurta,kurta_men
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN,False,True,False,...,False,False,False,False,True,False,False,False,False,False
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN,False,True,False,...,False,False,False,False,True,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN,False,True,False,...,False,False,False,False,True,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN,False,True,False,...,False,False,False,False,True,False,False,False,False,False

In [34]:
c1 = (df_revised['kurta'] == True) 
c2 = (df_revised['women'] == True)

df_revised.loc[c1 & c2, 'women_kurta'] = True

In [35]:
df = df_revised[df_revised.women_kurta == True]

In [36]:
df.shape

(489, 25)

In [37]:
c1 = (df_revised['kurta'] == True) 
c2 = (df_revised['men'] == True)


df_revised.loc[c1 & c2, 'kurta_men'] = True

In [38]:
df_kurta = df_revised[df_revised.kurta == True]

In [39]:
df_kurta1 = df_kurta[df_kurta.kurta_men == False]

In [40]:
df_kurta2 = df_kurta1[df_kurta1.women_kurta == False]

In [41]:
df_kurta2.shape

(63, 25)

In [42]:
df_kurta2_men = df_kurta2[df_kurta2.class_label == 'kurta_men']
df_kurta2_men.shape

(20, 25)

In [43]:
df_kurta2_women = df_kurta2[df_kurta2.class_label == 'women_kurta']
df_kurta2_women.shape

(19, 25)

In [44]:
df_revised['mojaris_men'] = [False]*7500
df_revised['mojaris_women'] = [False]*7500
df_revised['leggings_and_salwars'] = [False]*7500

In [45]:
con1 = (df_revised['mojari'] == True) 
con2 = (df_revised['women'] == True)


df_revised.loc[con1 & con2, 'mojaris_women'] = True

In [46]:
con1 = (df_revised['mojari'] == True) 
con2 = (df_revised['men'] == True)


df_revised.loc[con1 & con2, 'mojaris_men'] = True

In [49]:
df_revised[str(column)] = df_revised.product_title.str.contains(str(column), flags=re.IGNORECASE)

In [50]:
con1 = (df_revised['legging'] == True) 
con2 = (df_revised['salwar'] == True)


df_revised.loc[con1 | con2, 'leggings_and_salwars'] = True

In [51]:
df_revised.leggings_and_salwars.nunique()

2

In [52]:
df_revised.drop(['men', 'women', 'legging','salwar','mojari'], axis=1, inplace=True)

In [53]:
df_revised.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti,saree,...,petticoat,blouse,dupatta,gown,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN,False,False,True,...,False,True,False,False,False,False,False,False,False,False
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN,False,False,True,...,False,True,False,False,False,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN,False,False,True,...,False,True,False,False,False,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN,False,False,True,...,False,True,False,False,False,False,False,False,False,False

In [54]:
# Removing the blouse label from all sarees in class_label because 
# models wearing sarees cannot be shown without a saree blouse

c1 = (df_revised['class_label'] == 'saree') 
c2 = (df_revised['blouse'] == True)

df_revised.loc[c1 & c2, 'blouse'] = False

In [55]:
# Removing the saree label from all blouses in class_label because 
# blouses are blouses for sarees or lehengas. Therefore, it is likely that saree 
# will be in the product description

c1 = (df_revised['class_label'] == 'blouse') 
c2 = (df_revised['saree'] == True)

df_revised.loc[c1 & c2, 'saree'] = False

In [56]:
# Removing the saree label from all blouses in class_label because 
# blouses are blouses for sarees or lehengas.Therefore, it is likely that lehenga 
# will be in the product description

c1 = (df_revised['class_label'] == 'blouse') 
c2 = (df_revised['lehenga'] == True)

df_revised.loc[c1 & c2, 'lehenga'] = False

In [57]:
df_revised.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti,saree,...,petticoat,blouse,dupatta,gown,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [58]:
df_revised.loc[1]

number                                                                  1
image_url               https://m.media-amazon.com/images/I/81aQmbWsG7...
image_path                                             images/test/1.jpeg
brand                                                          Trilok Fab
product_title                        Women's Silk Saree With Blouse Piece
class_label                                                         saree
color                                                                 NaN
kurta                                                               False
dhoti                                                               False
saree                                                                True
sherwani                                                            False
palazzo                                                             False
nehru                                                               False
petticoat                                                           False
blouse                                                              False
dupatta                                                             False
gown                                                                False
lehenga                                                             False
women_kurta                                                         False
kurta_men                                                           False
mojaris_men                                                         False
mojaris_women                                                       False
leggings_and_salwars                                                False
Name: 1, dtype: object

In [59]:
df_revised = df_revised.rename({'dhoti':'dhoti_pants', 'sherwani':'sherwanis', 'palazzo':'palazzos', 
             'nehru':'nehru_jackets', 'petticoat':'petticoats', 'dupatta':'dupattas', 
             'gown':'gowns'},axis=1)
df_revised.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [60]:
# Changing each new column to false if the class_label is the same as the column name

columns = ['dhoti_pants', 'saree', 'sherwanis', 'palazzos', 'nehru_jackets', 'petticoats',
           'blouse','dupattas', 'gowns', 'lehenga', 'women_kurta', 'kurta_men', 
           'mojaris_men', 'mojaris_women', 'leggings_and_salwars']

for column in columns:
    c1 = (df_revised[str(column)] == True)
    c2 = (df_revised['class_label'] == str(column))
    df_revised.loc[c1 & c2, str(column)] = False

df_revised.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [61]:
def func(x):
    if x == True:
        return str(column)
    else:
        return 0

for column in columns:
    df_revised[str(column)] = df_revised[str(column)].apply(lambda x: func(x))

In [62]:
df_revised.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,0,https://m.media-amazon.com/images/I/71NZQ-aaAS...,images/test/0.jpeg,TANTUJA BENGAL HANDLOOM,(A Govt. of West Bengal Enterprises) Handloom ...,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,https://m.media-amazon.com/images/I/81aQmbWsG7...,images/test/1.jpeg,Trilok Fab,Women's Silk Saree With Blouse Piece,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,https://m.media-amazon.com/images/I/71YjGvzs9y...,images/test/2.jpeg,Nine Sister,Women's Georgette Net Embroidered Saree with B...,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,https://m.media-amazon.com/images/I/81JYhYV5Xr...,images/test/3.jpeg,Gauri Laxmi Enterprise,Women's Crepe Saree with Blouse (GLE$CHICKOO C...,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,https://m.media-amazon.com/images/I/91fXc5i5Dy...,images/test/4.jpeg,SOURBH,Women's Cotton Blend Digital Butta Printed Sar...,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,0

In [63]:
df_revised.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
7495,7495,https://rukminim1.flixcart.com/image/309/371/k...,images/test/7495.jpeg,aaliya fashion,Women Embroidered Rayon Anarkali Kurta,women_kurta,Purple,True,0,0,...,0,0,0,0,0,0,0,0,0,0
7496,7496,https://m.media-amazon.com/images/I/71xJFbz+uV...,images/test/7496.jpeg,AnjuShree Choice,Women's Rayon & Viscose Regular Stitched Kurta,women_kurta,NaN,True,0,0,...,0,0,0,0,0,0,0,0,0,0
7497,7497,https://m.media-amazon.com/images/I/71CawDGew+...,images/test/7497.jpeg,W for Woman,Women's cotton straight Kurta,women_kurta,NaN,True,0,0,...,0,0,0,0,0,0,0,0,0,0
7498,7498,https://m.media-amazon.com/images/I/61VBgoJQAt...,images/test/7498.jpeg,Vaamsi,Crepe Printed Kurti (VPK1805_Purple_Free Size),women_kurta,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,0
7499,7499,https://m.media-amazon.com/images/I/612gggywBm...,images/test/7499.jpeg,Vbuyz,Women's Rayon Regular Kurta,women_kurta,NaN,True,0,0,...,0,0,0,0,0,0,0,0,0,0

In [64]:
df_revised.replace({'kurta': True}, {'kurta': 'kurta'}, inplace=True)

In [65]:
c1 = (df_revised.class_label == 'women_kurta')
c2 = (df_revised.class_label == 'kurta_men')
c3 = (df_revised.kurta == 'kurta')

df_revised.loc[c3 & (c1 | c2), 'kurta'] = 0

In [66]:
df_revised.replace({'kurta': False}, {'kurta': 0}, inplace=True)

In [67]:
df_revised.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
7495,7495,https://rukminim1.flixcart.com/image/309/371/k...,images/test/7495.jpeg,aaliya fashion,Women Embroidered Rayon Anarkali Kurta,women_kurta,Purple,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7496,7496,https://m.media-amazon.com/images/I/71xJFbz+uV...,images/test/7496.jpeg,AnjuShree Choice,Women's Rayon & Viscose Regular Stitched Kurta,women_kurta,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7497,7497,https://m.media-amazon.com/images/I/71CawDGew+...,images/test/7497.jpeg,W for Woman,Women's cotton straight Kurta,women_kurta,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7498,7498,https://m.media-amazon.com/images/I/61VBgoJQAt...,images/test/7498.jpeg,Vaamsi,Crepe Printed Kurti (VPK1805_Purple_Free Size),women_kurta,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7499,7499,https://m.media-amazon.com/images/I/612gggywBm...,images/test/7499.jpeg,Vbuyz,Women's Rayon Regular Kurta,women_kurta,NaN,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [68]:
df_revised.iloc[7498,4]

'Crepe Printed Kurti (VPK1805_Purple_Free Size)'

In [69]:
df_revised.iloc[1001,4]

"Women's Regular Fit Patiala Pant"

In [70]:
df_revised.iloc[1001]

number                                                               1001
image_url               https://m.media-amazon.com/images/I/41P8Dmis0p...
image_path                                          images/test/1001.jpeg
brand                                                  Sri Belha Fashions
product_title                            Women's Regular Fit Patiala Pant
class_label                                                   dhoti_pants
color                                                                 NaN
kurta                                                                   0
dhoti_pants                                                             0
saree                                                                   0
sherwanis                                                               0
palazzos                                                                0
nehru_jackets                                                           0
petticoats                                                              0
blouse                                                                  0
dupattas                                                                0
gowns                                                                   0
lehenga                                                                 0
women_kurta                                                             0
kurta_men                                                               0
mojaris_men                                                             0
mojaris_women                                                           0
leggings_and_salwars                                                    0
Name: 1001, dtype: object

In [71]:
df_revised.gowns.value_counts()

gowns
0        7487
gowns      13
Name: count, dtype: int64

In [72]:
# Gowns are sometimes called dresses

df_revised['dress'] = df_revised.product_title.str.contains('dress', flags=re.IGNORECASE)

In [73]:
c1 = (df_revised.gowns == 0)
c2 = (df_revised.dress == True)
df_revised.loc[c1 & c2, 'gowns'] = 'gowns'

In [74]:
df_revised.gowns.value_counts()

gowns
0        7326
gowns     174
Name: count, dtype: int64

In [75]:
df_revised = df_revised.drop(['number', 'image_url', 'brand',
        'color', 'dress'], axis=1)

In [76]:
df_saree = df_revised[df_revised.saree == 'saree']
df_saree.shape

(191, 19)

In [77]:
df_saree.head()

,image_path,product_title,class_label,kurta,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
2056,images/test/2056.jpeg,Saree for women | Women's Fancy Saree | Silk S...,gowns,0,0,saree,0,0,0,0,blouse,0,0,0,0,0,0,0,0
2090,images/test/2090.jpeg,Chiffon with Blouse Piece Saree (Riva516_Yello...,gowns,0,0,saree,0,0,0,0,blouse,0,0,0,0,0,0,0,0
2265,images/test/2265.jpeg,DaSync Silver Stone Hanging latkan Laces Borde...,gowns,0,0,saree,0,0,0,0,blouse,0,gowns,lehenga,0,0,0,0,0
2397,images/test/2397.jpeg,Women's Saree with blouse piece,gowns,0,0,saree,0,0,0,0,blouse,0,0,0,0,0,0,0,0
2412,images/test/2412.jpeg,Women's Satin Saree With Blouse Piece,gowns,0,0,saree,0,0,0,0,blouse,0,0,0,0,0,0,0,0

In [78]:
df_saree.iloc[0,1]

"Saree for women | Women's Fancy Saree | Silk Saree With Silk Blouse Women's Saree (PARENT-ZQ-152)"

In [79]:
df_blouse = df_revised[df_revised.blouse == 'blouse']
df_blouse.shape

(201, 19)

In [80]:
df_blouse.head()

,image_path,product_title,class_label,kurta,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
1769,images/test/1769.jpeg,Women'S Kashmiri Art Printed Shawl Dupatta Wit...,dupattas,0,0,0,0,0,0,0,blouse,0,0,0,0,0,0,0,0
2056,images/test/2056.jpeg,Saree for women | Women's Fancy Saree | Silk S...,gowns,0,0,saree,0,0,0,0,blouse,0,0,0,0,0,0,0,0
2069,images/test/2069.jpeg,Chlamys Women Floral Printed Crape Unstiched F...,gowns,0,0,0,0,0,0,0,blouse,0,gowns,0,0,0,0,0,0
2090,images/test/2090.jpeg,Chiffon with Blouse Piece Saree (Riva516_Yello...,gowns,0,0,saree,0,0,0,0,blouse,0,0,0,0,0,0,0,0
2115,images/test/2115.jpeg,Woman's/Girl's Ethnic Unstitched Art Crepe Pri...,gowns,0,0,0,0,palazzos,0,0,blouse,0,gowns,0,0,0,0,0,0

In [81]:
df_dhoti_pants = df_revised[df_revised.dhoti_pants == 'dhoti_pants']
df_dhoti_pants.shape

(45, 19)

In [82]:
df_dhoti_pants.head()

,image_path,product_title,class_label,kurta,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
117,images/test/117.jpeg,Women's Olive Green Poly Crepe Crop Top And Dh...,saree,0,dhoti_pants,0,0,0,0,0,0,dupattas,0,0,0,0,0,0,0
2328,images/test/2328.jpeg,Women's Regular Fit Dhoti Pants,gowns,0,dhoti_pants,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2541,images/test/2541.jpeg,Men Beige Dhoti Pants,kurta_men,0,dhoti_pants,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2735,images/test/2735.jpeg,Men Beige Dupion Silk Dhoti & Maroon Kurta,kurta_men,0,dhoti_pants,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2782,images/test/2782.jpeg,Men Green Solid Kurta with Dhoti Pants,kurta_men,0,dhoti_pants,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [83]:
df_dhoti_pants.iloc[0,1]

"Women's Olive Green Poly Crepe Crop Top And Dhoti With Attached Dupatta"

In [84]:
df_dupattas = df_revised[df_revised.dupattas == 'dupattas']
df_dupattas.shape

(278, 19)

In [120]:
df_dupattas.head()

,image_path,product_title,class_label,kurta,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
117,images/test/117.jpeg,Women's Olive Green Poly Crepe Crop Top And Dh...,saree,0,dhoti_pants,0,0,0,0,0,0,dupattas,0,0,0,0,0,0,0
262,images/test/262.jpeg,Women's Jacquard Banarasi Silk Dupatta,saree,0,0,0,0,0,0,0,0,dupattas,0,0,0,0,0,0,0
1002,images/test/1002.jpeg,Women Cotton Floral and Embroidered Pattern St...,dhoti_pants,kurta,0,0,0,0,0,0,0,dupattas,0,0,women_kurta,0,0,0,0
1017,images/test/1017.jpeg,Women’s Pure Cotton Plain Semi Patiala Dhoti S...,dhoti_pants,0,0,0,0,0,0,0,0,dupattas,0,0,0,0,0,0,leggings_and_salwars
1032,images/test/1032.jpeg,Women’s Pure Cotton Plain Semi Patiala Dhoti S...,dhoti_pants,0,0,0,0,0,0,0,0,dupattas,0,0,0,0,0,0,leggings_and_salwars

In [85]:
df_dupattas.iloc[0,1]

"Women's Olive Green Poly Crepe Crop Top And Dhoti With Attached Dupatta"

In [86]:
df_gowns = df_revised[df_revised.gowns == 'gowns']
df_gowns.shape

(174, 19)

In [87]:
df_gowns.head()

,image_path,product_title,class_label,kurta,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
568,images/test/568.jpeg,Women/Girls Ethnic Unstitched Chanderi Cotton ...,blouse,0,0,0,0,0,0,0,0,0,gowns,0,0,0,0,0,0
777,images/test/777.jpeg,Women/Girls Ethnic Unstitched Chanderi Cotton ...,blouse,0,0,0,0,0,0,0,0,0,gowns,0,0,0,0,0,0
1211,images/test/1211.jpeg,"Women's Satin 2 Piece Night Suit Dress (Black,...",dhoti_pants,0,0,0,0,0,0,0,0,0,gowns,0,0,0,0,0,0
1341,images/test/1341.jpeg,Girls Western Dresses Cotton Blend Top and Den...,dhoti_pants,0,0,0,0,0,0,0,0,0,gowns,0,0,0,0,0,0
1533,images/test/1533.jpeg,Woman's Jacquard Lining Designed Net Dupatta w...,dupattas,0,0,0,0,0,0,0,0,0,gowns,0,0,0,0,0,0

In [88]:
df_gowns.iloc[0,1]

'Women/Girls Ethnic Unstitched Chanderi Cotton Jacquard Slightly Transparent Fabric/Cloth/Dress Material for Dress, Suit, Blouse etc. -I52'

In [89]:
df_kurta = df_revised[df_revised.kurta == 'kurta']
df_kurta.shape

(246, 19)

In [90]:
df_kurta.head()

,image_path,product_title,class_label,kurta,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
111,images/test/111.jpeg,Women's georgette with blouse piece Kurta (Kur...,saree,kurta,0,0,0,0,0,0,0,0,0,0,women_kurta,0,0,0,0
1002,images/test/1002.jpeg,Women Cotton Floral and Embroidered Pattern St...,dhoti_pants,kurta,0,0,0,0,0,0,0,dupattas,0,0,women_kurta,0,0,0,0
1016,images/test/1016.jpeg,Women's Black Pure Cotton Straight Kurta With ...,dhoti_pants,kurta,0,0,0,0,0,0,0,0,0,0,women_kurta,0,0,0,0
1027,images/test/1027.jpeg,Rayon Kurta and Multicolor Dhoti Pant Set For ...,dhoti_pants,kurta,0,0,0,0,0,0,0,0,0,0,women_kurta,0,0,0,0
1028,images/test/1028.jpeg,Women's Sage Green Umbrella Print Rayon Kurta ...,dhoti_pants,kurta,0,0,0,0,0,0,0,0,0,0,women_kurta,0,0,0,0

In [91]:
df_kurta.iloc[0,1]

"Women's georgette with blouse piece Kurta (Kurtas321_ Rani_ 6 Meter)"

In [92]:
df_kurta_men = df_revised[df_revised.kurta_men == 'kurta_men']
df_kurta_men.shape

(59, 19)

In [93]:
df_kurta_men.head()

,image_path,product_title,class_label,kurta,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
1120,images/test/1120.jpeg,Men's Ethnic Rayon Side Button Long Straight K...,dhoti_pants,kurta,0,0,0,0,0,0,0,0,0,0,0,kurta_men,0,0,0
1235,images/test/1235.jpeg,Mens Silk Self Design Kurta And Dhoti Pant (Blue),dhoti_pants,kurta,0,0,0,0,0,0,0,0,0,0,0,kurta_men,0,0,0
1252,images/test/1252.jpeg,Men's Regular Kurta,dhoti_pants,kurta,0,0,0,0,0,0,0,0,0,0,0,kurta_men,0,0,0
1269,images/test/1269.jpeg,Mens Self Design Kurta and Dhoti Pant Set,dhoti_pants,kurta,0,0,0,0,0,0,0,0,0,0,0,kurta_men,0,0,0
1295,images/test/1295.jpeg,Men's White Silk Blend Kurta and Dhoti Pant Set,dhoti_pants,kurta,0,0,0,0,0,0,0,0,0,0,0,kurta_men,0,0,0

In [94]:
# Obviously mislabeled

df_kurta_men.iloc[0,1]

"Men's Ethnic Rayon Side Button Long Straight Kurta"

In [95]:
df_leggings_and_salwars = df_revised[df_revised.leggings_and_salwars == 'leggings_and_salwars']
df_leggings_and_salwars.shape

(214, 19)

In [96]:
df_leggings_and_salwars.head()

,image_path,product_title,class_label,kurta,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
234,images/test/234.jpeg,The Boutique House - Soft malmal cotton sarees...,saree,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,leggings_and_salwars
1003,images/test/1003.jpeg,Women's Lycra Side Plated Dhoti Patiala Salwar...,dhoti_pants,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,leggings_and_salwars
1004,images/test/1004.jpeg,Women's Cotton Viscose Lycra Dhoti Patiyala Sa...,dhoti_pants,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,leggings_and_salwars
1007,images/test/1007.jpeg,Women's Viscose Lycra Cotton Dhoti Patiyala Sa...,dhoti_pants,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,leggings_and_salwars
1017,images/test/1017.jpeg,Women’s Pure Cotton Plain Semi Patiala Dhoti S...,dhoti_pants,0,0,0,0,0,0,0,0,dupattas,0,0,0,0,0,0,leggings_and_salwars

In [97]:
df_leggings_and_salwars.iloc[0,1]

'The Boutique House - Soft malmal cotton sarees with zari checks with embroidery Work - Kota Doria cotton saree - Kota Doria Lehanga - Salwar suits - Ethnic Wear - Pattern 3'

In [98]:
df_lehenga = df_revised[df_revised.lehenga == 'lehenga']
df_lehenga.shape

(29, 19)

In [99]:
df_lehenga.head()

,image_path,product_title,class_label,kurta,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
1522,images/test/1522.jpeg,Women and Girls Latest Design Chanderi Dupatta...,dupattas,kurta,0,0,0,0,0,0,0,0,0,lehenga,women_kurta,0,0,0,0
1527,images/test/1527.jpeg,"Girl's Embroidered Long Jacket, Lehenga and Du...",dupattas,0,0,0,0,0,0,0,0,0,0,lehenga,0,0,0,0,0
1535,images/test/1535.jpeg,Women's Silk semi-stitched Lehenga Choli with ...,dupattas,0,0,0,0,0,0,0,0,0,0,lehenga,0,0,0,0,0
1646,images/test/1646.jpeg,Celebrity Women's Net Embroidered Lehenga Chol...,dupattas,0,0,0,0,0,0,0,0,0,0,lehenga,0,0,0,0,0
1665,images/test/1665.jpeg,Digital Printed Chandei Latest Floral Design D...,dupattas,kurta,0,0,0,0,0,0,0,0,0,lehenga,women_kurta,0,0,0,0

In [100]:
df_mojaris_men = df_revised[df_revised.mojaris_men == 'mojaris_men']
df_mojaris_men.shape

(16, 19)

In [101]:
df_mojaris_men.head()

,image_path,product_title,class_label,kurta,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
4559,images/test/4559.jpeg,Men Casual Shoe Style Ethnic and Traditional B...,mojaris_women,0,0,0,0,0,0,0,0,0,0,0,0,0,mojaris_men,0,0
4564,images/test/4564.jpeg,Stylish Casual Ethnic Nagra/Mojaris/Jutti Form...,mojaris_women,0,0,0,0,0,0,0,0,0,0,0,0,0,mojaris_men,0,0
4588,images/test/4588.jpeg,Men's Ethnic Mojari/Juttis/Nagra/Loafers,mojaris_women,0,0,0,0,0,0,0,0,0,0,0,0,0,mojaris_men,0,0
4606,images/test/4606.jpeg,Unique Craft Men's Leather Mojaris,mojaris_women,0,0,0,0,0,0,0,0,0,0,0,0,0,mojaris_men,0,0
4608,images/test/4608.jpeg,Wedding Mojaris Shoes for Men Loafer Stylish B...,mojaris_women,0,0,0,0,0,0,0,0,0,0,0,0,0,mojaris_men,0,0

Some of the class_labels are incorrect for those labeled mojaris_women

In [102]:
df_mojaris_women = df_revised[df_revised.mojaris_women == 'mojaris_women']
df_mojaris_women.shape

(5, 19)

In [103]:
df_mojaris_women.head()

,image_path,product_title,class_label,kurta,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
4035,images/test/4035.jpeg,"Juttiwala Women's Ethnic Mojari, Juti, Bellies...",mojaris_men,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mojaris_women,0
4112,images/test/4112.jpeg,Women's Fabric Mojaris,mojaris_men,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mojaris_women,0
4302,images/test/4302.jpeg,Women Mojari Handicraft Slipper Shoes,mojaris_men,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mojaris_women,0
4355,images/test/4355.jpeg,Juttiwala Women's Traditional Slip-On Mojari J...,mojaris_men,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mojaris_women,0
4464,images/test/4464.jpeg,Ballet Flats Slip On Mojari Sandal Indian Jutt...,mojaris_men,0,0,0,0,0,0,0,0,0,0,0,0,0,0,mojaris_women,0

Some of the class_labels are incorrect for those labeled mojaris_men

In [104]:
df_nehru_jackets = df_revised[df_revised.nehru_jackets == 'nehru_jackets']
df_nehru_jackets.shape

(17, 19)

In [105]:
df_nehru_jackets.head()

,image_path,product_title,class_label,kurta,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
645,images/test/645.jpeg,KULLU Jacket Nehru Jacket Reversal Both Side U...,blouse,0,0,0,0,0,nehru_jackets,0,0,0,0,0,0,0,0,0,0
2502,images/test/2502.jpeg,Men Pink &amp; Maroon Solid Kurta with Churida...,kurta_men,0,0,0,0,0,nehru_jackets,0,0,0,0,0,0,0,0,0,0
2525,images/test/2525.jpeg,Men Teal &amp; Off-White Solid Kurta with Chur...,kurta_men,0,0,0,0,0,nehru_jackets,0,0,0,0,0,0,0,0,0,0
2534,images/test/2534.jpeg,Men Off-White &amp; Peach-Coloured Solid Kurta...,kurta_men,0,0,0,0,0,nehru_jackets,0,0,0,0,0,0,0,0,0,0
2551,images/test/2551.jpeg,Printed Full Sleeves Kurta and Churidar Set wi...,kurta_men,0,0,0,0,0,nehru_jackets,0,0,0,0,0,0,0,0,0,0

In [106]:
df_nehru_jackets.iloc[0,1]

'KULLU Jacket Nehru Jacket Reversal Both Side USABLE for Men ONE Side Grey Other Side KINGRY Black'

This label is clearly incorrect

In [107]:
df_palazzos = df_revised[df_revised.palazzos == 'palazzos']
df_palazzos.shape

(182, 19)

In [108]:
df_palazzos.head()

,image_path,product_title,class_label,kurta,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
1018,images/test/1018.jpeg,"Women's Regular Fit Full Length, Design for Mu...",dhoti_pants,0,0,0,0,palazzos,0,0,0,0,0,0,0,0,0,0,0
1034,images/test/1034.jpeg,Women Rayon Flared Garara/Sharara Palazzo Pant...,dhoti_pants,0,0,0,0,palazzos,0,0,0,0,0,0,0,0,0,0,0
1041,images/test/1041.jpeg,"Women's Regular Fit Full Length, Design for Mu...",dhoti_pants,0,0,0,0,palazzos,0,0,0,0,0,0,0,0,0,0,0
1057,images/test/1057.jpeg,R & B Enterprises Stylish Solid Pink Palazzo f...,dhoti_pants,0,0,0,0,palazzos,0,0,0,0,0,0,0,0,0,0,0
1091,images/test/1091.jpeg,Women's Viscose Palazzo Bottom Pants,dhoti_pants,0,0,0,0,palazzos,0,0,0,0,0,0,0,0,0,0,0

In [109]:
df_palazzos.iloc[0,1]

"Women's Regular Fit Full Length, Design for Multicolor Plain Solid Dhoti,Haram Pant Bottom Wear With Beautiful Flared Sarara/Garara/Palazzo/Free Size Combo (Pack Of 2)"

In [110]:
df_petticoats = df_revised[df_revised.petticoats == 'petticoats']
df_petticoats.shape

(1, 19)

In [111]:
df_petticoats.head()

,image_path,product_title,class_label,kurta,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
432,images/test/432.jpeg,Women's Rani Pink Lycra Shapewear Saree Petticoat,saree,0,0,0,0,0,0,petticoats,0,0,0,0,0,0,0,0,0

Another mislabeled item

In [112]:
df_sherwanis = df_revised[df_revised.sherwanis == 'sherwanis']
df_sherwanis.shape

(50, 19)

In [113]:
df_sherwanis.head()

,image_path,product_title,class_label,kurta,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
2686,images/test/2686.jpeg,Men's Silk Sherwani Straight Kurta,kurta_men,0,0,0,sherwanis,0,0,0,0,0,0,0,0,0,0,0,0
2726,images/test/2726.jpeg,Men's Jacquard Silk Floral Print Indowestern S...,kurta_men,0,0,0,sherwanis,0,0,0,0,0,0,0,0,0,0,0,0
4008,images/test/4008.jpeg,Black Velvet Wedding & Sherwani Mojari's,mojaris_men,0,0,0,sherwanis,0,0,0,0,0,0,0,0,0,0,0,0
4018,images/test/4018.jpeg,Jutti for Men's Mens Mojari Indian Shoes Handm...,mojaris_men,0,0,0,sherwanis,0,0,0,0,0,0,0,0,0,0,0,0
4048,images/test/4048.jpeg,Men Royal Luxury & Traditional Designing Handc...,mojaris_men,0,0,0,sherwanis,0,0,0,0,0,0,0,0,0,0,0,0

In [114]:
df_sherwanis.iloc[0,1]

"Men's Silk Sherwani Straight Kurta"

In [115]:
df_women_kurta = df_revised[df_revised.women_kurta == 'women_kurta']
df_women_kurta.shape

(163, 19)

In [116]:
df_women_kurta.head()

,image_path,product_title,class_label,kurta,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
111,images/test/111.jpeg,Women's georgette with blouse piece Kurta (Kur...,saree,kurta,0,0,0,0,0,0,0,0,0,0,women_kurta,0,0,0,0
1002,images/test/1002.jpeg,Women Cotton Floral and Embroidered Pattern St...,dhoti_pants,kurta,0,0,0,0,0,0,0,dupattas,0,0,women_kurta,0,0,0,0
1016,images/test/1016.jpeg,Women's Black Pure Cotton Straight Kurta With ...,dhoti_pants,kurta,0,0,0,0,0,0,0,0,0,0,women_kurta,0,0,0,0
1027,images/test/1027.jpeg,Rayon Kurta and Multicolor Dhoti Pant Set For ...,dhoti_pants,kurta,0,0,0,0,0,0,0,0,0,0,women_kurta,0,0,0,0
1028,images/test/1028.jpeg,Women's Sage Green Umbrella Print Rayon Kurta ...,dhoti_pants,kurta,0,0,0,0,0,0,0,0,0,0,women_kurta,0,0,0,0

In [117]:
df_women_kurta.iloc[0,1]

"Women's georgette with blouse piece Kurta (Kurtas321_ Rani_ 6 Meter)"

In [118]:
df_women_kurta.iloc[1,1]

'Women Cotton Floral and Embroidered Pattern Straight Kurta and Pant with Dupatta Set (STYLEP)'

In [ ]:
df_revised.to_csv('/data/interim/test_other_categories.csv')