In [71]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [72]:
ejscreen_2021 = 'C:/Users/butle/hp/ejscreen2021_project/data/raw/EJSCREEN_2021_StatePctile.csv'
df = pd.read_csv(ejscreen_2021)

In [73]:
df.shape

(220333, 136)

In [74]:
df.head()

,OBJECTID,ID,STATE_NAME,ST_ABBREV,REGION,ACSTOTPOP,MINORPCT,LOWINCPCT,LESSHSPCT,LINGISOPCT,...,T_PTSDF,T_PTSDF_D2,T_OZONE,T_OZONE_D2,T_PM25,T_PM25_D2,T_UST,T_UST_D2,Shape_Length,Shape_Area
0,1,1.001020e+10,Alabama,AL,4,730,0.169863,0.382192,0.207843,0.0,...,0.59 facilities/km distance (58%ile),36%ile,37 ppb (24%ile),52%ile,9.15 ug/m3 (75%ile),51%ile,1.13 facilities/sq km area (63%ile),32%ile,13443.155210,6040789.687
1,2,1.001020e+10,Alabama,AL,4,1263,0.166271,0.212985,0.073801,0.0,...,0.45 facilities/km distance (53%ile),24%ile,37 ppb (24%ile),34%ile,9.15 ug/m3 (75%ile),32%ile,0 facilities/sq km area (5%ile),61%ile,11917.089600,7834159.678
2,3,1.001020e+10,Alabama,AL,4,835,0.680240,0.546599,0.125230,0.0,...,0.65 facilities/km distance (60%ile),80%ile,37 ppb (25%ile),77%ile,9.18 ug/m3 (76%ile),78%ile,0.997 facilities/sq km area (61%ile),78%ile,7770.915121,2900773.822
3,4,1.001020e+10,Alabama,AL,4,1124,0.570285,0.339891,0.162791,0.0,...,0.96 facilities/km distance (69%ile),78%ile,37 ppb (25%ile),70%ile,9.18 ug/m3 (76%ile),70%ile,3.72 facilities/sq km area (86%ile),82%ile,6506.804784,1793331.694
4,5,1.001020e+10,Alabama,AL,4,2774,0.327325,0.214131,0.126368,0.0,...,0.95 facilities/km distance (69%ile),15%ile,37.1 ppb (26%ile),31%ile,9.21 ug/m3 (77%ile),29%ile,0.773 facilities/sq km area (55%ile),21%ile,11070.367850,5461601.630

In [75]:
df.tail()

,OBJECTID,ID,STATE_NAME,ST_ABBREV,REGION,ACSTOTPOP,MINORPCT,LOWINCPCT,LESSHSPCT,LINGISOPCT,...,T_PTSDF,T_PTSDF_D2,T_OZONE,T_OZONE_D2,T_PM25,T_PM25_D2,T_UST,T_UST_D2,Shape_Length,Shape_Area
220328,220329,7.215380e+11,Puerto Rico,PR,2,883,1.0,0.959230,0.305861,0.843882,...,0.55 facilities/km distance (56%ile),53%ile,NaN,NaN,NaN,NaN,0.49 facilities/sq km area (83%ile),83%ile,19751.958140,8.486394e+06
220329,220330,7.215380e+11,Puerto Rico,PR,2,2523,1.0,0.786365,0.113028,0.579730,...,0.78 facilities/km distance (62%ile),80%ile,NaN,NaN,NaN,NaN,0 facilities/sq km area (82%ile),82%ile,6704.079316,1.744950e+06
220330,220331,7.215380e+11,Puerto Rico,PR,2,991,1.0,0.530777,0.000000,0.351562,...,1 facilities/km distance (68%ile),58%ile,NaN,NaN,NaN,NaN,0 facilities/sq km area (82%ile),82%ile,7737.485130,1.989274e+06
220331,220332,7.215380e+11,Puerto Rico,PR,2,1577,1.0,0.856318,0.437361,0.855357,...,0.67 facilities/km distance (59%ile),67%ile,NaN,NaN,NaN,NaN,0 facilities/sq km area (82%ile),82%ile,5128.438096,1.265276e+06
220332,220333,7.215380e+11,Puerto Rico,PR,2,648,1.0,0.933642,0.101833,0.765027,...,0.41 facilities/km distance (51%ile),41%ile,NaN,NaN,NaN,NaN,0 facilities/sq km area (82%ile),82%ile,20006.384460,1.848868e+07

In [76]:
df.describe()

,OBJECTID,ID,REGION,ACSTOTPOP,MINORPCT,LOWINCPCT,LESSHSPCT,LINGISOPCT,UNDER5PCT,OVER64PCT,...,B_PTRAF_D2,B_PWDIS_D2,B_PNPL_D2,B_PRMP_D2,B_PTSDF_D2,B_OZONE_D2,B_PM25_D2,B_UST_D2,Shape_Length,Shape_Area
count,220333.000000,2.203330e+05,220333.000000,220333.000000,220333.000000,220333.000000,220333.000000,220333.000000,220333.000000,220333.000000,...,220333.000000,220333.000000,220333.000000,220333.000000,220333.000000,220333.000000,220333.000000,220333.000000,2.203330e+05,2.203330e+05
mean,110167.000000,2.863577e+11,5.167642,1488.729523,0.379880,0.328999,0.127365,0.051343,0.057683,0.169330,...,5.352575,3.835649,5.747328,5.715617,5.709190,5.691217,5.692252,5.849505,2.159649e+04,1.035940e+08
std,63604.802768,1.633201e+11,2.482247,1023.901679,0.318703,0.213851,0.119135,0.110103,0.040588,0.103726,...,3.068080,3.570613,2.760908,2.812929,2.809573,2.694286,2.697616,2.903248,6.339577e+04,3.809274e+09
min,1.000000,1.001020e+10,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,1.000000,3.015633e+02,5.494842e+03
25%,55084.000000,1.312100e+11,3.000000,887.000000,0.101504,0.157005,0.040906,0.000000,0.028949,0.100849,...,3.000000,0.000000,4.000000,3.000000,3.000000,4.000000,4.000000,3.000000,4.161918e+03,8.056294e+05
50%,110167.000000,2.816400e+11,5.000000,1266.000000,0.284227,0.294545,0.092697,0.000000,0.052587,0.154450,...,5.000000,3.000000,6.000000,6.000000,6.000000,6.000000,6.000000,6.000000,7.462489e+03,2.223483e+06
75%,165250.000000,4.200340e+11,7.000000,1822.000000,0.628221,0.468776,0.178309,0.053134,0.079669,0.216418,...,8.000000,7.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,2.034583e+04,1.521928e+07
max,220333.000000,7.215380e+11,10.000000,59947.000000,1.000000,1.000000,1.000000,1.000000,0.500000,1.000000,...,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,11.000000,8.214219e+06,1.289560e+12

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220333 entries, 0 to 220332
Columns: 136 entries, OBJECTID to Shape_Area
dtypes: float64(49), int64(53), object(34)
memory usage: 228.6+ MB

In [78]:
df.dtypes

OBJECTID          int64
ID              float64
STATE_NAME       object
ST_ABBREV        object
REGION            int64
                 ...
T_PM25_D2        object
T_UST            object
T_UST_D2         object
Shape_Length    float64
Shape_Area      float64
Length: 136, dtype: object

In [79]:
df['ACSTOTPOP'].dtypes

dtype('int64')

In [80]:
df['MINORPCT'].dtypes

dtype('float64')

In [81]:
df['PRE1960PCT'].dtypes

dtype('float64')

In [82]:
df['P_MINORPCT'].dtypes

dtype('int64')

In [83]:
df['D_UST_2'].dtypes

dtype('float64')

In [84]:
pol = df.astype({"ID":'int64'})

In [85]:
pol.head()

,OBJECTID,ID,STATE_NAME,ST_ABBREV,REGION,ACSTOTPOP,MINORPCT,LOWINCPCT,LESSHSPCT,LINGISOPCT,...,T_PTSDF,T_PTSDF_D2,T_OZONE,T_OZONE_D2,T_PM25,T_PM25_D2,T_UST,T_UST_D2,Shape_Length,Shape_Area
0,1,10010201001,Alabama,AL,4,730,0.169863,0.382192,0.207843,0.0,...,0.59 facilities/km distance (58%ile),36%ile,37 ppb (24%ile),52%ile,9.15 ug/m3 (75%ile),51%ile,1.13 facilities/sq km area (63%ile),32%ile,13443.155210,6040789.687
1,2,10010201002,Alabama,AL,4,1263,0.166271,0.212985,0.073801,0.0,...,0.45 facilities/km distance (53%ile),24%ile,37 ppb (24%ile),34%ile,9.15 ug/m3 (75%ile),32%ile,0 facilities/sq km area (5%ile),61%ile,11917.089600,7834159.678
2,3,10010202001,Alabama,AL,4,835,0.680240,0.546599,0.125230,0.0,...,0.65 facilities/km distance (60%ile),80%ile,37 ppb (25%ile),77%ile,9.18 ug/m3 (76%ile),78%ile,0.997 facilities/sq km area (61%ile),78%ile,7770.915121,2900773.822
3,4,10010202002,Alabama,AL,4,1124,0.570285,0.339891,0.162791,0.0,...,0.96 facilities/km distance (69%ile),78%ile,37 ppb (25%ile),70%ile,9.18 ug/m3 (76%ile),70%ile,3.72 facilities/sq km area (86%ile),82%ile,6506.804784,1793331.694
4,5,10010203001,Alabama,AL,4,2774,0.327325,0.214131,0.126368,0.0,...,0.95 facilities/km distance (69%ile),15%ile,37.1 ppb (26%ile),31%ile,9.21 ug/m3 (77%ile),29%ile,0.773 facilities/sq km area (55%ile),21%ile,11070.367850,5461601.630

To prepare this for concatenation with health data, need to make health LocationName and df ID the same. ID has one extra digit for the block group, while LocationName only includes census tracts. Combining the block groups into census tracts by averaging the features scaled by population.

In [86]:
pol['LocationName'] = pol['ID'] // 10
poll = pol.copy()
poll.head()

C:\Users\butle\AppData\Local\Temp\ipykernel_2992\3921973867.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  pol['LocationName'] = pol['ID'] // 10

,OBJECTID,ID,STATE_NAME,ST_ABBREV,REGION,ACSTOTPOP,MINORPCT,LOWINCPCT,LESSHSPCT,LINGISOPCT,...,T_PTSDF_D2,T_OZONE,T_OZONE_D2,T_PM25,T_PM25_D2,T_UST,T_UST_D2,Shape_Length,Shape_Area,LocationName
0,1,10010201001,Alabama,AL,4,730,0.169863,0.382192,0.207843,0.0,...,36%ile,37 ppb (24%ile),52%ile,9.15 ug/m3 (75%ile),51%ile,1.13 facilities/sq km area (63%ile),32%ile,13443.155210,6040789.687,1001020100
1,2,10010201002,Alabama,AL,4,1263,0.166271,0.212985,0.073801,0.0,...,24%ile,37 ppb (24%ile),34%ile,9.15 ug/m3 (75%ile),32%ile,0 facilities/sq km area (5%ile),61%ile,11917.089600,7834159.678,1001020100
2,3,10010202001,Alabama,AL,4,835,0.680240,0.546599,0.125230,0.0,...,80%ile,37 ppb (25%ile),77%ile,9.18 ug/m3 (76%ile),78%ile,0.997 facilities/sq km area (61%ile),78%ile,7770.915121,2900773.822,1001020200
3,4,10010202002,Alabama,AL,4,1124,0.570285,0.339891,0.162791,0.0,...,78%ile,37 ppb (25%ile),70%ile,9.18 ug/m3 (76%ile),70%ile,3.72 facilities/sq km area (86%ile),82%ile,6506.804784,1793331.694,1001020200
4,5,10010203001,Alabama,AL,4,2774,0.327325,0.214131,0.126368,0.0,...,15%ile,37.1 ppb (26%ile),31%ile,9.21 ug/m3 (77%ile),29%ile,0.773 facilities/sq km area (55%ile),21%ile,11070.367850,5461601.630,1001020300

Getting rid of any rows with zero population

In [87]:
poll = pol[pol['ACSTOTPOP'] != 0]

Dropping columns not needed

In [88]:
poll = poll.drop(["OBJECTID", 'STATE_NAME', 'ID', 'REGION', 'Shape_Length', 'Shape_Area'], axis=1)
poll.head()

,ST_ABBREV,ACSTOTPOP,MINORPCT,LOWINCPCT,LESSHSPCT,LINGISOPCT,UNDER5PCT,OVER64PCT,PRE1960PCT,UNEMPPCT,...,T_PRMP_D2,T_PTSDF,T_PTSDF_D2,T_OZONE,T_OZONE_D2,T_PM25,T_PM25_D2,T_UST,T_UST_D2,LocationName
0,AL,730,0.169863,0.382192,0.207843,0.0,0.023288,0.180822,0.165079,0.028125,...,54%ile,0.59 facilities/km distance (58%ile),36%ile,37 ppb (24%ile),52%ile,9.15 ug/m3 (75%ile),51%ile,1.13 facilities/sq km area (63%ile),32%ile,1001020100
1,AL,1263,0.166271,0.212985,0.073801,0.0,0.077593,0.104513,0.190244,0.028788,...,43%ile,0.45 facilities/km distance (53%ile),24%ile,37 ppb (24%ile),34%ile,9.15 ug/m3 (75%ile),32%ile,0 facilities/sq km area (5%ile),61%ile,1001020100
2,AL,835,0.680240,0.546599,0.125230,0.0,0.062275,0.196407,0.122283,0.000000,...,70%ile,0.65 facilities/km distance (60%ile),80%ile,37 ppb (25%ile),77%ile,9.18 ug/m3 (76%ile),78%ile,0.997 facilities/sq km area (61%ile),78%ile,1001020200
3,AL,1124,0.570285,0.339891,0.162791,0.0,0.041815,0.106762,0.256356,0.065606,...,66%ile,0.96 facilities/km distance (69%ile),78%ile,37 ppb (25%ile),70%ile,9.18 ug/m3 (76%ile),70%ile,3.72 facilities/sq km area (86%ile),82%ile,1001020200
4,AL,2774,0.327325,0.214131,0.126368,0.0,0.019827,0.140952,0.058501,0.038360,...,39%ile,0.95 facilities/km distance (69%ile),15%ile,37.1 ppb (26%ile),31%ile,9.21 ug/m3 (77%ile),29%ile,0.773 facilities/sq km area (55%ile),21%ile,1001020300

In [89]:

poll.head()

,ST_ABBREV,ACSTOTPOP,MINORPCT,LOWINCPCT,LESSHSPCT,LINGISOPCT,UNDER5PCT,OVER64PCT,PRE1960PCT,UNEMPPCT,...,T_PRMP_D2,T_PTSDF,T_PTSDF_D2,T_OZONE,T_OZONE_D2,T_PM25,T_PM25_D2,T_UST,T_UST_D2,LocationName
0,AL,730,0.169863,0.382192,0.207843,0.0,0.023288,0.180822,0.165079,0.028125,...,54%ile,0.59 facilities/km distance (58%ile),36%ile,37 ppb (24%ile),52%ile,9.15 ug/m3 (75%ile),51%ile,1.13 facilities/sq km area (63%ile),32%ile,1001020100
1,AL,1263,0.166271,0.212985,0.073801,0.0,0.077593,0.104513,0.190244,0.028788,...,43%ile,0.45 facilities/km distance (53%ile),24%ile,37 ppb (24%ile),34%ile,9.15 ug/m3 (75%ile),32%ile,0 facilities/sq km area (5%ile),61%ile,1001020100
2,AL,835,0.680240,0.546599,0.125230,0.0,0.062275,0.196407,0.122283,0.000000,...,70%ile,0.65 facilities/km distance (60%ile),80%ile,37 ppb (25%ile),77%ile,9.18 ug/m3 (76%ile),78%ile,0.997 facilities/sq km area (61%ile),78%ile,1001020200
3,AL,1124,0.570285,0.339891,0.162791,0.0,0.041815,0.106762,0.256356,0.065606,...,66%ile,0.96 facilities/km distance (69%ile),78%ile,37 ppb (25%ile),70%ile,9.18 ug/m3 (76%ile),70%ile,3.72 facilities/sq km area (86%ile),82%ile,1001020200
4,AL,2774,0.327325,0.214131,0.126368,0.0,0.019827,0.140952,0.058501,0.038360,...,39%ile,0.95 facilities/km distance (69%ile),15%ile,37.1 ppb (26%ile),31%ile,9.21 ug/m3 (77%ile),29%ile,0.773 facilities/sq km area (55%ile),21%ile,1001020300

Getting rid of map data

In [90]:
df = poll
pop = df.ACSTOTPOP
loc = df.LocationName
df = df.iloc[:, 1:65]

Multiplying numerical columns, except ACSTOTPOP, by population (ACSTOTPOP), as a step in the process of combining rows with same LocationName by a weighted average

In [91]:
for column in df:
    if column != 'ACSTOTPOP':
        df[column] *= df['ACSTOTPOP']

Adding back in LocationName

In [92]:
df['LocationName'] = loc

Grouping rows with same LocationName. Each numerical value is given the population-weighted mean

In [93]:
def mean_normed_by_pop(x):
    x = x.sum() / x['ACSTOTPOP'].sum()
    return x

df = df.groupby('LocationName', group_keys=False).apply(mean_normed_by_pop)

LocationName and ACSTOPOP were also normed, so they need to be dropped. The LocationName as the index is made into a column

In [94]:
df.drop(['LocationName', 'ACSTOTPOP'], axis=1, inplace=True)
df.reset_index(inplace=True)
df = df.rename(columns = {'index':'LocationName'})
df.head()

,LocationName,MINORPCT,LOWINCPCT,LESSHSPCT,LINGISOPCT,UNDER5PCT,OVER64PCT,PRE1960PCT,UNEMPPCT,VULEOPCT,...,P_DSLPM_D2,P_CANCR_D2,P_RESP_D2,P_PTRAF_D2,P_PWDIS_D2,P_PNPL_D2,P_PRMP_D2,P_PTSDF_D2,P_OZONE_D2,P_PM25_D2
0,1001020100,0.167587,0.274962,0.122898,0.000000,0.057702,0.132464,0.181027,0.028545,0.221274,...,36.959358,35.691922,37.325640,45.872052,0.000000,26.325640,47.029102,28.395384,40.593076,38.959358
1,1001020200,0.617152,0.427998,0.146781,0.000000,0.050536,0.144972,0.199209,0.037642,0.522575,...,73.983665,74.409903,73.409903,72.180194,0.000000,83.131189,67.704952,78.852476,72.983665,73.409903
2,1001020300,0.348446,0.293128,0.151047,0.000000,0.027659,0.160251,0.059415,0.034101,0.320787,...,33.450528,34.614485,36.196464,40.495580,0.000000,29.003707,44.852295,29.421728,39.151411,37.569433
3,1001020400,0.103146,0.216864,0.080968,0.022387,0.041774,0.244714,0.120926,0.027308,0.160005,...,22.281073,27.240330,28.916452,6.322589,0.000000,15.649046,39.556730,9.244714,32.634090,30.112687
4,1001020500,0.290959,0.202810,0.079311,0.018190,0.047659,0.138071,0.000000,0.031944,0.246885,...,13.179407,14.983956,15.797848,11.066346,20.631748,10.630427,29.649113,10.895338,18.671857,17.044073

In [95]:
df.head()

,LocationName,MINORPCT,LOWINCPCT,LESSHSPCT,LINGISOPCT,UNDER5PCT,OVER64PCT,PRE1960PCT,UNEMPPCT,VULEOPCT,...,P_DSLPM_D2,P_CANCR_D2,P_RESP_D2,P_PTRAF_D2,P_PWDIS_D2,P_PNPL_D2,P_PRMP_D2,P_PTSDF_D2,P_OZONE_D2,P_PM25_D2
0,1001020100,0.167587,0.274962,0.122898,0.000000,0.057702,0.132464,0.181027,0.028545,0.221274,...,36.959358,35.691922,37.325640,45.872052,0.000000,26.325640,47.029102,28.395384,40.593076,38.959358
1,1001020200,0.617152,0.427998,0.146781,0.000000,0.050536,0.144972,0.199209,0.037642,0.522575,...,73.983665,74.409903,73.409903,72.180194,0.000000,83.131189,67.704952,78.852476,72.983665,73.409903
2,1001020300,0.348446,0.293128,0.151047,0.000000,0.027659,0.160251,0.059415,0.034101,0.320787,...,33.450528,34.614485,36.196464,40.495580,0.000000,29.003707,44.852295,29.421728,39.151411,37.569433
3,1001020400,0.103146,0.216864,0.080968,0.022387,0.041774,0.244714,0.120926,0.027308,0.160005,...,22.281073,27.240330,28.916452,6.322589,0.000000,15.649046,39.556730,9.244714,32.634090,30.112687
4,1001020500,0.290959,0.202810,0.079311,0.018190,0.047659,0.138071,0.000000,0.031944,0.246885,...,13.179407,14.983956,15.797848,11.066346,20.631748,10.630427,29.649113,10.895338,18.671857,17.044073

In [96]:
df.shape

(16781, 64)

In [97]:
df.tail()

,LocationName,MINORPCT,LOWINCPCT,LESSHSPCT,LINGISOPCT,UNDER5PCT,OVER64PCT,PRE1960PCT,UNEMPPCT,VULEOPCT,...,P_DSLPM_D2,P_CANCR_D2,P_RESP_D2,P_PTRAF_D2,P_PWDIS_D2,P_PNPL_D2,P_PRMP_D2,P_PTSDF_D2,P_OZONE_D2,P_PM25_D2
16776,72145600000,0.970359,0.743217,0.280997,0.648518,0.045122,0.194628,0.097770,0.178195,0.856788,...,67.644831,51.818938,50.580472,49.706028,45.372873,89.187404,35.681024,48.356357,0.0,0.0
16777,72148000000,0.949317,0.753636,0.292443,0.710081,0.050336,0.213955,0.107982,0.080410,0.851477,...,1.792409,51.182481,50.317982,6.909512,0.000000,42.352349,5.490627,3.933349,0.0,0.0
16778,72149700000,0.998304,0.805126,0.215880,0.755289,0.051243,0.167165,0.095808,0.217987,0.901715,...,15.437575,57.409856,51.222872,18.620631,23.826005,24.912869,33.200732,16.652547,0.0,0.0
16779,72152000000,0.999522,0.804061,0.288115,0.716471,0.039553,0.198006,0.085227,0.185099,0.901792,...,25.815457,55.571778,54.373713,24.807278,25.022508,69.821845,52.785815,42.815636,0.0,0.0
16780,72153800000,0.996698,0.835629,0.253286,0.730279,0.041549,0.212600,0.070210,0.200005,0.916163,...,18.186180,51.253726,49.946427,32.959270,49.992718,37.474258,57.411087,70.680281,0.0,0.0

In [98]:
df.to_csv('C:/Users/butle/hp/ejscreen2021_project/data/interim/EJSCREEN_2021_interim.csv')

In [99]:
health_2022 = 'C:/Users/butle/hp/ejscreen2021_project/data/raw/PLACES__Local_Data_for_Better_Health__Census_Tract_Data_2022_release.csv'
df2 = pd.read_csv(health_2022)

In [100]:
df2.head()

,Year,StateAbbr,StateDesc,CountyName,CountyFIPS,LocationName,DataSource,Category,Measure,Data_Value_Unit,...,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text
0,2020,AL,Alabama,Autauga,1001,1001020200,BRFSS,Health Outcomes,Chronic obstructive pulmonary disease among ad...,%,...,NaN,6.8,8.5,2170,POINT (-86.47338874 32.47425254),1001020200,HLTHOUT,COPD,CrdPrv,COPD
1,2020,AL,Alabama,Autauga,1001,1001020400,BRFSS,Health Outcomes,Obesity among adults aged >=18 years,%,...,NaN,31.5,35.0,4386,POINT (-86.44370417 32.47203959),1001020400,HLTHOUT,OBESITY,CrdPrv,Obesity
2,2020,AL,Alabama,Autauga,1001,1001021000,BRFSS,Health Outcomes,Obesity among adults aged >=18 years,%,...,NaN,39.3,41.2,2894,POINT (-86.75607371 32.60894544),1001021000,HLTHOUT,OBESITY,CrdPrv,Obesity
3,2020,AL,Alabama,Baldwin,1003,1003010905,BRFSS,Health Outcomes,Stroke among adults aged >=18 years,%,...,NaN,2.7,3.2,8011,POINT (-87.75682132 30.53592075),1003010905,HLTHOUT,STROKE,CrdPrv,Stroke
4,2020,AL,Alabama,Baldwin,1003,1003010906,BRFSS,Health Outcomes,Depression among adults aged >=18 years,%,...,NaN,26.3,28.9,4302,POINT (-87.68753351 30.56418914),1003010906,HLTHOUT,DEPRESSION,CrdPrv,Depression

In [101]:
df.shape

(16781, 64)

In [102]:
df2.tail()

,Year,StateAbbr,StateDesc,CountyName,CountyFIPS,LocationName,DataSource,Category,Measure,Data_Value_Unit,...,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text
2161538,2020,WI,Wisconsin,Waukesha,55133,55133204002,BRFSS,Prevention,"Fecal occult blood test, sigmoidoscopy, or col...",%,...,NaN,59.0,64.9,5479,POINT (-88.4824858 42.88723077),55133204002,PREVENT,COLON_SCREEN,CrdPrv,Colorectal Cancer Screening
2161539,2020,WI,Wisconsin,Rock,55105,55105002700,BRFSS,Health Status,Physical health not good for >=14 days among a...,%,...,NaN,9.6,11.6,2571,POINT (-89.24626648 42.548431),55105002700,HLTHSTAT,PHLTH,CrdPrv,Physical Health
2161540,2020,WI,Wisconsin,Waukesha,55133,55133203200,BRFSS,Health Outcomes,Cancer (excluding skin cancer) among adults ag...,%,...,NaN,7.0,7.8,4106,POINT (-88.31331246 43.07069963),55133203200,HLTHOUT,CANCER,CrdPrv,Cancer (except skin)
2161541,2020,WI,Wisconsin,Waukesha,55133,55133203101,BRFSS,Prevention,Visits to dentist or dental clinic among adult...,%,...,NaN,74.7,80.6,6536,POINT (-88.27895206 43.04127835),55133203101,PREVENT,DENTAL,CrdPrv,Dental Visit
2161542,2020,WI,Wisconsin,Waukesha,55133,55133200400,BRFSS,Health Outcomes,Chronic kidney disease among adults aged >=18 ...,%,...,NaN,2.1,2.5,6582,POINT (-88.10191212 43.13413751),55133200400,HLTHOUT,KIDNEY,CrdPrv,Chronic Kidney Disease

In [103]:
df[df['LocationName'] == 1001020200]

,LocationName,MINORPCT,LOWINCPCT,LESSHSPCT,LINGISOPCT,UNDER5PCT,OVER64PCT,PRE1960PCT,UNEMPPCT,VULEOPCT,...,P_DSLPM_D2,P_CANCR_D2,P_RESP_D2,P_PTRAF_D2,P_PWDIS_D2,P_PNPL_D2,P_PRMP_D2,P_PTSDF_D2,P_OZONE_D2,P_PM25_D2
1,1001020200,0.617152,0.427998,0.146781,0.0,0.050536,0.144972,0.199209,0.037642,0.522575,...,73.983665,74.409903,73.409903,72.180194,0.0,83.131189,67.704952,78.852476,72.983665,73.409903

In [104]:
df[df['LocationName'] == 55133200400]

Empty DataFrame
Columns: [LocationName, MINORPCT, LOWINCPCT, LESSHSPCT, LINGISOPCT, UNDER5PCT, OVER64PCT, PRE1960PCT, UNEMPPCT, VULEOPCT, DSLPM, CANCER, RESP, PTRAF, PWDIS, PNPL, PRMP, PTSDF, OZONE, PM25, UST, D_LDPNT_2, D_DSLPM_2, D_CANCR_2, D_RESP_2, D_PTRAF_2, D_PWDIS_2, D_PNPL_2, D_PRMP_2, D_PTSDF_2, D_OZONE_2, D_PM25_2, D_UST_2, P_MINORPCT, P_LWINCPCT, P_LESHSPCT, P_LNGISPCT, P_UNDR5PCT, P_OVR64PCT, P_LDPNT, P_UNEMPPCT, P_VULEOPCT, P_DSLPM, P_CANCR, P_RESP, P_PTRAF, P_PWDIS, P_PNPL, P_PRMP, P_PTSDF, P_OZONE, P_PM25, P_UST, P_LDPNT_D2, P_DSLPM_D2, P_CANCR_D2, P_RESP_D2, P_PTRAF_D2, P_PWDIS_D2, P_PNPL_D2, P_PRMP_D2, P_PTSDF_D2, P_OZONE_D2, P_PM25_D2]
Index: []

[0 rows x 64 columns]

In [105]:
df2['LocationName'].isin(df['LocationName']).value_counts()

False    1753050
True      408493
Name: LocationName, dtype: int64

In [106]:
df['LocationName'].isin(df2['LocationName']).value_counts()

True     13620
False     3161
Name: LocationName, dtype: int64

Not all of the LocationNames in the health data are present in the environmental data. Slicing the health database

In [107]:
common_rows_health = df2.loc[df2['LocationName'].isin(df['LocationName'])]
common_rows_health.head()

,Year,StateAbbr,StateDesc,CountyName,CountyFIPS,LocationName,DataSource,Category,Measure,Data_Value_Unit,...,Data_Value_Footnote,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,Geolocation,LocationID,CategoryID,MeasureId,DataValueTypeID,Short_Question_Text
0,2020,AL,Alabama,Autauga,1001,1001020200,BRFSS,Health Outcomes,Chronic obstructive pulmonary disease among ad...,%,...,NaN,6.8,8.5,2170,POINT (-86.47338874 32.47425254),1001020200,HLTHOUT,COPD,CrdPrv,COPD
1,2020,AL,Alabama,Autauga,1001,1001020400,BRFSS,Health Outcomes,Obesity among adults aged >=18 years,%,...,NaN,31.5,35.0,4386,POINT (-86.44370417 32.47203959),1001020400,HLTHOUT,OBESITY,CrdPrv,Obesity
2,2020,AL,Alabama,Autauga,1001,1001021000,BRFSS,Health Outcomes,Obesity among adults aged >=18 years,%,...,NaN,39.3,41.2,2894,POINT (-86.75607371 32.60894544),1001021000,HLTHOUT,OBESITY,CrdPrv,Obesity
3,2020,AL,Alabama,Baldwin,1003,1003010905,BRFSS,Health Outcomes,Stroke among adults aged >=18 years,%,...,NaN,2.7,3.2,8011,POINT (-87.75682132 30.53592075),1003010905,HLTHOUT,STROKE,CrdPrv,Stroke
4,2020,AL,Alabama,Baldwin,1003,1003010906,BRFSS,Health Outcomes,Depression among adults aged >=18 years,%,...,NaN,26.3,28.9,4302,POINT (-87.68753351 30.56418914),1003010906,HLTHOUT,DEPRESSION,CrdPrv,Depression

In [109]:
common_rows_health.shape

(408493, 23)

In [110]:
df3 = common_rows_health
df3.Category.nunique()

4

In [111]:
df3.Category.unique()

array(['Health Outcomes', 'Health Risk Behaviors', 'Prevention',
       'Health Status'], dtype=object)

In [112]:
df3.DataSource.nunique()

1

In [113]:
df3.DataSource.unique()

array(['BRFSS'], dtype=object)

In [114]:
df3.Data_Value_Footnote_Symbol.nunique()

0

In [115]:
df3.Data_Value_Footnote.nunique()

0

In [116]:
df3.DataValueTypeID.unique()

array(['CrdPrv'], dtype=object)

In [117]:
df3.DataValueTypeID.nunique()

1

Getting rid of unnecessary columns

In [118]:
common_rows_health.drop(['StateDesc', 'Year', 'CountyFIPS', 'Geolocation', 'DataValueTypeID', 'Data_Value_Footnote','Data_Value_Footnote_Symbol', 'DataSource'], axis=1, inplace=True)

C:\Users\butle\AppData\Local\Temp\ipykernel_2992\118357376.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  common_rows_health.drop(['StateDesc', 'Year', 'CountyFIPS', 'Geolocation', 'DataValueTypeID', 'Data_Value_Footnote','Data_Value_Footnote_Symbol', 'DataSource'], axis=1, inplace=True)

In [119]:
df3[df3['MeasureId'] == 'COPD'].shape

(13620, 15)

In [120]:
df3[df3['MeasureId'] == 'OBESITY'].shape

(13620, 15)

In [121]:
df3.MeasureId.unique()

array(['COPD', 'OBESITY', 'STROKE', 'DEPRESSION', 'LPA', 'CASTHMA',
       'MAMMOUSE', 'TEETHLOST', 'ARTHRITIS', 'COREM', 'DIABETES', 'BINGE',
       'SLEEP', 'ACCESS2', 'BPMED', 'PHLTH', 'DENTAL', 'MHLTH', 'BPHIGH',
       'CANCER', 'CHOLSCREEN', 'CHD', 'GHLTH', 'CHECKUP', 'CSMOKING',
       'CERVICAL', 'COLON_SCREEN', 'KIDNEY', 'HIGHCHOL', 'COREW'],
      dtype=object)

Focus on health outcomes

In [122]:
outcomes = df3[df3['CategoryID'] == 'HLTHOUT']
outcomes.MeasureId.unique()

array(['COPD', 'OBESITY', 'STROKE', 'DEPRESSION', 'CASTHMA', 'TEETHLOST',
       'ARTHRITIS', 'DIABETES', 'BPHIGH', 'CANCER', 'CHD', 'KIDNEY',
       'HIGHCHOL'], dtype=object)

In [123]:
outcomes.shape

(177045, 15)

Focus on asthma and cancer

In [124]:
asthma = outcomes[outcomes['MeasureId'] == 'CASTHMA']
cancer = outcomes[outcomes['MeasureId'] == 'CANCER']
concerns = pd.concat([asthma, cancer], axis=0)
concerns.shape

(27240, 15)

In [125]:
concerns.head()

,StateAbbr,CountyName,LocationName,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,TotalPopulation,LocationID,CategoryID,MeasureId,Short_Question_Text
8,AL,Butler,1013953200,Health Outcomes,Current asthma among adults aged >=18 years,%,Crude prevalence,10.3,10.0,10.7,4327,1013953200,HLTHOUT,CASTHMA,Current Asthma
21,AL,Cleburne,1029959500,Health Outcomes,Current asthma among adults aged >=18 years,%,Crude prevalence,10.1,9.6,10.5,2684,1029959500,HLTHOUT,CASTHMA,Current Asthma
30,AL,Dallas,1047956600,Health Outcomes,Current asthma among adults aged >=18 years,%,Crude prevalence,12.3,11.6,13.0,3811,1047956600,HLTHOUT,CASTHMA,Current Asthma
61,AL,Jefferson,1073012912,Health Outcomes,Current asthma among adults aged >=18 years,%,Crude prevalence,8.9,8.5,9.3,5473,1073012912,HLTHOUT,CASTHMA,Current Asthma
132,AK,Bethel,2050000300,Health Outcomes,Current asthma among adults aged >=18 years,%,Crude prevalence,12.9,12.5,13.4,1450,2050000300,HLTHOUT,CASTHMA,Current Asthma

In [126]:
combined = pd.merge(concerns, df, on="LocationName")
combined.shape

(27240, 78)

In [127]:
combined.head()

,StateAbbr,CountyName,LocationName,Category,Measure,Data_Value_Unit,Data_Value_Type,Data_Value,Low_Confidence_Limit,High_Confidence_Limit,...,P_DSLPM_D2,P_CANCR_D2,P_RESP_D2,P_PTRAF_D2,P_PWDIS_D2,P_PNPL_D2,P_PRMP_D2,P_PTSDF_D2,P_OZONE_D2,P_PM25_D2
0,AL,Butler,1013953200,Health Outcomes,Current asthma among adults aged >=18 years,%,Crude prevalence,10.3,10.0,10.7,...,61.875069,61.980609,62.200554,54.821884,51.660665,61.921607,60.029640,60.672022,62.606094,62.466759
1,AL,Butler,1013953200,Health Outcomes,Cancer (excluding skin cancer) among adults ag...,%,Crude prevalence,6.8,6.6,7.1,...,61.875069,61.980609,62.200554,54.821884,51.660665,61.921607,60.029640,60.672022,62.606094,62.466759
2,AL,Cleburne,1029959500,Health Outcomes,Current asthma among adults aged >=18 years,%,Crude prevalence,10.1,9.6,10.5,...,49.943384,46.943384,46.943384,58.118593,38.840871,42.180570,54.943384,54.530988,45.943384,46.649581
3,AL,Cleburne,1029959500,Health Outcomes,Cancer (excluding skin cancer) among adults ag...,%,Crude prevalence,6.8,6.6,7.0,...,49.943384,46.943384,46.943384,58.118593,38.840871,42.180570,54.943384,54.530988,45.943384,46.649581
4,AL,Dallas,1047956600,Health Outcomes,Current asthma among adults aged >=18 years,%,Crude prevalence,12.3,11.6,13.0,...,78.048556,81.485140,80.071997,83.987861,70.077438,73.602763,82.245710,63.746337,78.959397,79.461699

In [128]:
combined.columns.values

array(['StateAbbr', 'CountyName', 'LocationName', 'Category', 'Measure',
       'Data_Value_Unit', 'Data_Value_Type', 'Data_Value',
       'Low_Confidence_Limit', 'High_Confidence_Limit', 'TotalPopulation',
       'LocationID', 'CategoryID', 'MeasureId', 'Short_Question_Text',
       'MINORPCT', 'LOWINCPCT', 'LESSHSPCT', 'LINGISOPCT', 'UNDER5PCT',
       'OVER64PCT', 'PRE1960PCT', 'UNEMPPCT', 'VULEOPCT', 'DSLPM',
       'CANCER', 'RESP', 'PTRAF', 'PWDIS', 'PNPL', 'PRMP', 'PTSDF',
       'OZONE', 'PM25', 'UST', 'D_LDPNT_2', 'D_DSLPM_2', 'D_CANCR_2',
       'D_RESP_2', 'D_PTRAF_2', 'D_PWDIS_2', 'D_PNPL_2', 'D_PRMP_2',
       'D_PTSDF_2', 'D_OZONE_2', 'D_PM25_2', 'D_UST_2', 'P_MINORPCT',
       'P_LWINCPCT', 'P_LESHSPCT', 'P_LNGISPCT', 'P_UNDR5PCT',
       'P_OVR64PCT', 'P_LDPNT', 'P_UNEMPPCT', 'P_VULEOPCT', 'P_DSLPM',
       'P_CANCR', 'P_RESP', 'P_PTRAF', 'P_PWDIS', 'P_PNPL', 'P_PRMP',
       'P_PTSDF', 'P_OZONE', 'P_PM25', 'P_UST', 'P_LDPNT_D2',
       'P_DSLPM_D2', 'P_CANCR_D2', 'P_RESP_D2', 'P_PTRAF_D2',
       'P_PWDIS_D2', 'P_PNPL_D2', 'P_PRMP_D2', 'P_PTSDF_D2', 'P_OZONE_D2',
       'P_PM25_D2'], dtype=object)

In [129]:
df.to_csv('C:/Users/butle/hp/ejscreen2021_project/data/interim/combined_health_ejscreen.csv')