In [253]:
import pandas as pd
import numpy as np
import re

In [254]:
dfvr = pd.read_csv('/Users/butler/Documents/springboard_bootcamp/Classification_of_Indian_clothing_images/data/interim/dfvr1.csv')
dfvr.columns

Index(['Unnamed: 0', 'number', 'image_url', 'image_path', 'brand',
       'product_title', 'class_label', 'color', 'kurta', 'women', ' men',
       'dhoti', 'saree', 'sherwani', 'palazzo', 'mojari', 'nehru', 'legging',
       'salwar', 'petticoat', 'blouse', 'dupatta', 'gown', 'lehenga',
       'other_label'],
      dtype='object')

In [255]:
df.head()

,Unnamed: 0,number,image_url,image_path,brand,product_title,class_label,color,kurta,women,...,palazzo,mojari,nehru,legging,salwar,petticoat,blouse,dupatta,gown,lehenga
0,0,0,https://m.media-amazon.com/images/I/81LOPbFPiQ...,images/val/0.jpeg,Generic,Women's Khadi Cotton Saree With Blouse Piece (...,saree,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,1,https://m.media-amazon.com/images/I/81Q8Oktw4s...,images/val/1.jpeg,Yashvi Designer,Women's Net Saree With Unstitched Blouse Piece,saree,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,2,https://m.media-amazon.com/images/I/613S1YGCmo...,images/val/2.jpeg,Aarrah,Georgette Strip Print Saree[S_SHIKHA30021SR02_...,saree,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,3,https://m.media-amazon.com/images/I/819budhQl1...,images/val/3.jpeg,MIMOSA,Women's Patola Style Art Silk Saree (Green),saree,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,4,https://m.media-amazon.com/images/I/61cAZ94ZQV...,images/val/4.jpeg,Generic,Women's Pure Hand Block Patola Printed Cotton ...,saree,NaN,0,0,...,0,0,0,0,0,0,0,0,0,0

In [256]:
columns = ['dhoti', 'saree', 'sherwani', 'palazzo', 
           'mojari', 'nehru', 'legging', 'salwar', 'petticoat', 'blouse', 
           'dupatta', 'gown','lehenga']

dhoti = dfvr.index[dfvr['dhoti'] == True]
saree = dfvr.index[dfvr['saree'] == True]
sherwani = dfvr.index[dfvr['sherwani'] == True]
palazzo = dfvr.index[dfvr['palazzo'] == True]
nehru = dfvr.index[dfvr['nehru'] == True]
legging = dfvr.index[dfvr['legging'] == True]
salwar = dfvr.index[dfvr['salwar'] == True]
petticoat = dfvr.index[dfvr['petticoat'] == True]
blouse = dfvr.index[dfvr['blouse'] == True]
dupatta = dfvr.index[dfvr['dupatta'] == True]
gown = dfvr.index[dfvr['gown'] == True]
lehenga = dfvr.index[dfvr['lehenga'] == True]
women = dfvr.index[dfvr['women'] == True]
men = dfvr.index[dfvr[' men'] == True]
kurta = dfvr.index[dfvr['kurta'] == True]
mojari = dfvr.index[dfvr['mojari'] == True]

In [258]:
dfvr.loc[3000]

Unnamed: 0                                                    3000
number                                                        3000
image_url        https://m.media-amazon.com/images/I/31ZKFkUvR1...
image_path                                    images/val/3000.jpeg
brand                                                  Happy Bunny
product_title          Women's Cotton Salwar Bottom Pant (MUSTARD)
class_label                                   leggings_and_salwars
color                                                          NaN
kurta                                                        False
women                                                         True
 men                                                         False
dhoti                                                        False
saree                                                        False
sherwani                                                     False
palazzo                                                      False
mojari                                                       False
nehru                                                        False
legging                                                      False
salwar                                                        True
petticoat                                                    False
blouse                                                       False
dupatta                                                      False
gown                                                         False
lehenga                                                      False
other_label                                   leggings_and_salwars
Name: 3000, dtype: object

In [207]:
df.loc[3000]

Unnamed: 0                                                    3000
number                                                        3000
image_url        https://m.media-amazon.com/images/I/31ZKFkUvR1...
image_path                                    images/val/3000.jpeg
brand                                                  Happy Bunny
product_title          Women's Cotton Salwar Bottom Pant (MUSTARD)
class_label                                   leggings_and_salwars
color                                                          NaN
kurta                                                            0
women                                                        women
 men                                                             0
dhoti                                                            0
saree                                                            0
sherwani                                                         0
palazzo                                                          0
mojari                                                           0
nehru                                                            0
legging                                                          0
salwar                                                      salwar
petticoat                                                        0
blouse                                                           0
dupatta                                                          0
gown                                                             0
lehenga                                                          0
Name: 3000, dtype: object

In [ ]:
columns = ['kurta', 'dhoti', 'saree', 'sherwani', 'palazzo', 
           'mojari', 'nehru', 'legging', 'salwar', 'petticoat', 'blouse', 
           'dupatta', 'gown','lehenga']

In [159]:

def func(x):
    if x == str(column):
        return str(column)
    
    
for column in columns:   
    df['other_label'] = df[column].apply(lambda x: func(x))

In [160]:
df.loc[3000]

Unnamed: 0                                                    3000
number                                                        3000
image_url        https://m.media-amazon.com/images/I/31ZKFkUvR1...
image_path                                    images/val/3000.jpeg
brand                                                  Happy Bunny
product_title          Women's Cotton Salwar Bottom Pant (MUSTARD)
class_label                                   leggings_and_salwars
color                                                          NaN
kurta                                                            0
women                                                        women
 men                                                             0
dhoti                                                            0
saree                                                            0
sherwani                                                         0
palazzo                                                          0
mojari                                                           0
nehru                                                            0
legging                                                          0
salwar                                                      salwar
petticoat                                                        0
blouse                                                           0
dupatta                                                          0
gown                                                             0
lehenga                                                          0
other_label                                                   None
Name: 3000, dtype: object

In [148]:
def func(x):
    if x == str(column):
        return str(column)
        
for column in columns:
    dfvr['other_label'] = dfvr[str(column)].apply(lambda x: func(x))

In [149]:
df.head()

,Unnamed: 0,number,image_url,image_path,brand,product_title,class_label,color,kurta,women,...,mojari,nehru,legging,salwar,petticoat,blouse,dupatta,gown,lehenga,other_label
0,0,0,https://m.media-amazon.com/images/I/81LOPbFPiQ...,images/val/0.jpeg,Generic,Women's Khadi Cotton Saree With Blouse Piece (...,saree,NaN,0,women,...,0,0,0,0,0,blouse,0,0,0,lehenga
1,1,1,https://m.media-amazon.com/images/I/81Q8Oktw4s...,images/val/1.jpeg,Yashvi Designer,Women's Net Saree With Unstitched Blouse Piece,saree,NaN,0,women,...,0,0,0,0,0,blouse,0,0,0,lehenga
2,2,2,https://m.media-amazon.com/images/I/613S1YGCmo...,images/val/2.jpeg,Aarrah,Georgette Strip Print Saree[S_SHIKHA30021SR02_...,saree,NaN,0,0,...,0,0,0,0,0,0,0,0,0,lehenga
3,3,3,https://m.media-amazon.com/images/I/819budhQl1...,images/val/3.jpeg,MIMOSA,Women's Patola Style Art Silk Saree (Green),saree,NaN,0,women,...,0,0,0,0,0,0,0,0,0,lehenga
4,4,4,https://m.media-amazon.com/images/I/61cAZ94ZQV...,images/val/4.jpeg,Generic,Women's Pure Hand Block Patola Printed Cotton ...,saree,NaN,0,women,...,0,0,0,0,0,blouse,0,0,0,lehenga

In [7]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [8]:
df.loc[0]

number                                                           0
image_url        https://m.media-amazon.com/images/I/81LOPbFPiQ...
image_path                                       images/val/0.jpeg
brand                                                      Generic
product_title    Women's Khadi Cotton Saree With Blouse Piece (...
class_label                                                  saree
color                                                          NaN
kurta                                                            0
women                                                            0
men                                                              0
dhoti_pants                                                      0
saree                                                            0
sherwanis                                                        0
palazzos                                                         0
mojaris                                                          0
nehru                                                            0
leggings                                                         0
salwars                                                          0
petticoats                                                       0
blouse                                                           0
dupattas                                                         0
gowns                                                            0
lehenga                                                          0
Name: 0, dtype: object

In [9]:
df.saree

0       0
1       0
2       0
3       0
4       0
       ..
7495    0
7496    0
7497    0
7498    0
7499    0
Name: saree, Length: 7500, dtype: int64

In [13]:
df.loc[1000]

number                                                        1000
image_url        https://rukminim1.flixcart.com/image/309/371/k...
image_path                                    images/val/1000.jpeg
brand                                                          NaN
product_title    MK Fashion Hub Red Rayon Fabric Floral Print W...
class_label                                            dhoti_pants
color                                                          NaN
kurta                                                            0
women                                                            0
men                                                              0
dhoti_pants                                                      0
saree                                                            0
sherwanis                                                        0
palazzos                                                         0
mojaris                                                          0
nehru                                                            0
leggings                                                         0
salwars                                                          0
petticoats                                                       0
blouse                                                           0
dupattas                                                         0
gowns                                                            0
lehenga                                                          0
Name: 1000, dtype: object