In [284]:
import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib.pyplot as plt

In [285]:
df = pd.read_json('/Users/butler/Documents/springboard_bootcamp/Classification_of_Indian_clothing_images/data/raw/val_data.json', lines=True)

In [286]:
df.head()

,image_url,image_path,brand,product_title,class_label,color
0,https://m.media-amazon.com/images/I/81LOPbFPiQ...,images/val/0.jpeg,Generic,Women's Khadi Cotton Saree With Blouse Piece (...,saree,NaN
1,https://m.media-amazon.com/images/I/81Q8Oktw4s...,images/val/1.jpeg,Yashvi Designer,Women's Net Saree With Unstitched Blouse Piece,saree,NaN
2,https://m.media-amazon.com/images/I/613S1YGCmo...,images/val/2.jpeg,Aarrah,Georgette Strip Print Saree[S_SHIKHA30021SR02_...,saree,NaN
3,https://m.media-amazon.com/images/I/819budhQl1...,images/val/3.jpeg,MIMOSA,Women's Patola Style Art Silk Saree (Green),saree,NaN
4,https://m.media-amazon.com/images/I/61cAZ94ZQV...,images/val/4.jpeg,Generic,Women's Pure Hand Block Patola Printed Cotton ...,saree,NaN

In [287]:
df.tail()

,image_url,image_path,brand,product_title,class_label,color
7495,https://m.media-amazon.com/images/I/614GvuaIJu...,images/val/7495.jpeg,ishin,Women's Rayon Pink Printed A-Line Kurta Palazz...,women_kurta,NaN
7496,https://m.media-amazon.com/images/I/81WAbf4-ao...,images/val/7496.jpeg,Cotton Culture,Women's Kesar Pink Cotton Straight Kurta,women_kurta,NaN
7497,https://m.media-amazon.com/images/I/61unbmOA7k...,images/val/7497.jpeg,Bae's Wardrobe,Printed Rayon Anarkali Kurti with Plazzo Pant ...,women_kurta,NaN
7498,https://m.media-amazon.com/images/I/71zULAnVNY...,images/val/7498.jpeg,Aarika,Girl's Regular Dress,women_kurta,NaN
7499,https://m.media-amazon.com/images/I/71mhB7xFHt...,images/val/7499.jpeg,Aurelia,Women's Straight Kurta,women_kurta,NaN

In [288]:
df.shape

(7500, 6)

In [289]:
df.class_label.unique()

array(['saree', 'blouse', 'dhoti_pants', 'dupattas', 'gowns', 'kurta_men',
       'leggings_and_salwars', 'lehenga', 'mojaris_men', 'mojaris_women',
       'nehru_jackets', 'palazzos', 'petticoats', 'sherwanis',
       'women_kurta'], dtype=object)

In [290]:
dfr = df.copy()

In [291]:
dfr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7500 entries, 0 to 7499
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   image_url      7500 non-null   object
 1   image_path     7500 non-null   object
 2   brand          7500 non-null   object
 3   product_title  7500 non-null   object
 4   class_label    7500 non-null   object
 5   color          947 non-null    object
dtypes: object(6)
memory usage: 351.7+ KB

In [292]:
dfr = dfr.reset_index(names='number')

In [293]:
dfr.tail()

,number,image_url,image_path,brand,product_title,class_label,color
7495,7495,https://m.media-amazon.com/images/I/614GvuaIJu...,images/val/7495.jpeg,ishin,Women's Rayon Pink Printed A-Line Kurta Palazz...,women_kurta,NaN
7496,7496,https://m.media-amazon.com/images/I/81WAbf4-ao...,images/val/7496.jpeg,Cotton Culture,Women's Kesar Pink Cotton Straight Kurta,women_kurta,NaN
7497,7497,https://m.media-amazon.com/images/I/61unbmOA7k...,images/val/7497.jpeg,Bae's Wardrobe,Printed Rayon Anarkali Kurti with Plazzo Pant ...,women_kurta,NaN
7498,7498,https://m.media-amazon.com/images/I/71zULAnVNY...,images/val/7498.jpeg,Aarika,Girl's Regular Dress,women_kurta,NaN
7499,7499,https://m.media-amazon.com/images/I/71mhB7xFHt...,images/val/7499.jpeg,Aurelia,Women's Straight Kurta,women_kurta,NaN

In [294]:
dfr.tail()

,number,image_url,image_path,brand,product_title,class_label,color
7495,7495,https://m.media-amazon.com/images/I/614GvuaIJu...,images/val/7495.jpeg,ishin,Women's Rayon Pink Printed A-Line Kurta Palazz...,women_kurta,NaN
7496,7496,https://m.media-amazon.com/images/I/81WAbf4-ao...,images/val/7496.jpeg,Cotton Culture,Women's Kesar Pink Cotton Straight Kurta,women_kurta,NaN
7497,7497,https://m.media-amazon.com/images/I/61unbmOA7k...,images/val/7497.jpeg,Bae's Wardrobe,Printed Rayon Anarkali Kurti with Plazzo Pant ...,women_kurta,NaN
7498,7498,https://m.media-amazon.com/images/I/71zULAnVNY...,images/val/7498.jpeg,Aarika,Girl's Regular Dress,women_kurta,NaN
7499,7499,https://m.media-amazon.com/images/I/71mhB7xFHt...,images/val/7499.jpeg,Aurelia,Women's Straight Kurta,women_kurta,NaN

In [295]:
columns = ['kurta', 'women', 'men', 'dhoti', 'saree', 'sherwani', 'palazzo', 
           'mojari', 'nehru', 'legging', 'salwar', 'petticoat', 'blouse', 
           'dupatta', 'gown','lehenga']

In [296]:
for column in columns:
    dfr[str(column)] = dfr.product_title.str.contains(str(column), flags=re.IGNORECASE)

In [297]:
dfr.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,women,men,...,palazzo,mojari,nehru,legging,salwar,petticoat,blouse,dupatta,gown,lehenga
0,0,https://m.media-amazon.com/images/I/81LOPbFPiQ...,images/val/0.jpeg,Generic,Women's Khadi Cotton Saree With Blouse Piece (...,saree,NaN,False,True,True,...,False,False,False,False,False,False,True,False,False,False
1,1,https://m.media-amazon.com/images/I/81Q8Oktw4s...,images/val/1.jpeg,Yashvi Designer,Women's Net Saree With Unstitched Blouse Piece,saree,NaN,False,True,True,...,False,False,False,False,False,False,True,False,False,False
2,2,https://m.media-amazon.com/images/I/613S1YGCmo...,images/val/2.jpeg,Aarrah,Georgette Strip Print Saree[S_SHIKHA30021SR02_...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/819budhQl1...,images/val/3.jpeg,MIMOSA,Women's Patola Style Art Silk Saree (Green),saree,NaN,False,True,True,...,False,False,False,False,False,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/61cAZ94ZQV...,images/val/4.jpeg,Generic,Women's Pure Hand Block Patola Printed Cotton ...,saree,NaN,False,True,True,...,False,False,False,False,False,False,True,False,False,False

In [298]:
dfrm1 = dfr[dfr.men == True]
dfrm1.shape

(5502, 23)

In [299]:
dfrm1.loc[0]

number                                                           0
image_url        https://m.media-amazon.com/images/I/81LOPbFPiQ...
image_path                                       images/val/0.jpeg
brand                                                      Generic
product_title    Women's Khadi Cotton Saree With Blouse Piece (...
class_label                                                  saree
color                                                          NaN
kurta                                                        False
women                                                         True
men                                                           True
dhoti                                                        False
saree                                                         True
sherwani                                                     False
palazzo                                                      False
mojari                                                       False
nehru                                                        False
legging                                                      False
salwar                                                       False
petticoat                                                    False
blouse                                                        True
dupatta                                                      False
gown                                                         False
lehenga                                                      False
Name: 0, dtype: object

In [300]:
dfr.columns

Index(['number', 'image_url', 'image_path', 'brand', 'product_title',
       'class_label', 'color', 'kurta', 'women', 'men', 'dhoti', 'saree',
       'sherwani', 'palazzo', 'mojari', 'nehru', 'legging', 'salwar',
       'petticoat', 'blouse', 'dupatta', 'gown', 'lehenga'],
      dtype='object')

In [301]:
con1 = (dfr['men'] == True) 
con2 = (dfr['women'] == True)


dfr.loc[con1 & con2, 'men'] = False

In [302]:
dfrm = dfr[dfr.men == True]

In [303]:
dfrm.shape

(1594, 23)

In [304]:
dfrm.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,women,men,...,palazzo,mojari,nehru,legging,salwar,petticoat,blouse,dupatta,gown,lehenga
1002,1002,"https://assets.myntassets.com/h_720,q_90,w_540...",images/val/1002.jpeg,VASTRAMAY,Men Black Solid Dhoti,dhoti_pants,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1013,1013,https://m.media-amazon.com/images/I/61GA6b9scm...,images/val/1013.jpeg,Larwa,Men's Embroidery Kurta & Salwar Dhoti Set Spec...,dhoti_pants,NaN,True,False,True,...,False,False,False,False,True,False,False,False,False,False
1016,1016,"https://assets.myntassets.com/h_720,q_90,w_540...",images/val/1016.jpeg,Nakshi,Men Black &amp; Gold-coloured Hand Block Print...,dhoti_pants,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1021,1021,https://rukminim1.flixcart.com/image/309/371/k...,images/val/1021.jpeg,N/A,GREEN TEE Solid Men Dhoti,dhoti_pants,N/A,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1023,1023,https://rukminim1.flixcart.com/image/309/371/j...,images/val/1023.jpeg,N/A,GREEN TEE Solid Men Dhoti,dhoti_pants,N/A,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [305]:
dfr.iloc[2,4]

'Georgette Strip Print Saree[S_SHIKHA30021SR02_perent_Red & Yellow]'

In [306]:
dfr.iloc[1,4]

"Women's Net Saree With Unstitched Blouse Piece"

In [307]:
dfr.loc[1000]

number                                                        1000
image_url        https://rukminim1.flixcart.com/image/309/371/k...
image_path                                    images/val/1000.jpeg
brand                                                          N/A
product_title    MK Fashion Hub Red Rayon Fabric Floral Print W...
class_label                                            dhoti_pants
color                                                          N/A
kurta                                                        False
women                                                         True
men                                                          False
dhoti                                                         True
saree                                                        False
sherwani                                                     False
palazzo                                                      False
mojari                                                       False
nehru                                                        False
legging                                                      False
salwar                                                       False
petticoat                                                    False
blouse                                                       False
dupatta                                                      False
gown                                                         False
lehenga                                                      False
Name: 1000, dtype: object

In [308]:
dfr.iloc[1000,4]

'MK Fashion Hub Red Rayon Fabric Floral Print Women Dhoti'

In [309]:
dfr['women_kurta'] = [False]* 7500

In [310]:
dfr['kurta_men'] = [False]* 7500

In [311]:
dfr.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,women,men,...,nehru,legging,salwar,petticoat,blouse,dupatta,gown,lehenga,women_kurta,kurta_men
0,0,https://m.media-amazon.com/images/I/81LOPbFPiQ...,images/val/0.jpeg,Generic,Women's Khadi Cotton Saree With Blouse Piece (...,saree,NaN,False,True,False,...,False,False,False,False,True,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81Q8Oktw4s...,images/val/1.jpeg,Yashvi Designer,Women's Net Saree With Unstitched Blouse Piece,saree,NaN,False,True,False,...,False,False,False,False,True,False,False,False,False,False
2,2,https://m.media-amazon.com/images/I/613S1YGCmo...,images/val/2.jpeg,Aarrah,Georgette Strip Print Saree[S_SHIKHA30021SR02_...,saree,NaN,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/819budhQl1...,images/val/3.jpeg,MIMOSA,Women's Patola Style Art Silk Saree (Green),saree,NaN,False,True,False,...,False,False,False,False,False,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/61cAZ94ZQV...,images/val/4.jpeg,Generic,Women's Pure Hand Block Patola Printed Cotton ...,saree,NaN,False,True,False,...,False,False,False,False,True,False,False,False,False,False

In [312]:
con1 = (dfr['kurta'] == True) 
con2 = (dfr['women'] == True)


dfr.loc[con1 & con2, 'women_kurta'] = True

In [313]:
df = dfr[dfr.women_kurta == True]

In [314]:
df.shape

(500, 25)

In [315]:
con1 = (dfr['kurta'] == True) 
con2 = (dfr['men'] == True)


dfr.loc[con1 & con2, 'kurta_men'] = True

In [316]:
dfr['mojaris_men'] = [False]*7500
dfr['mojaris_women'] = [False]*7500
dfr['leggings_and_salwars'] = [False]*7500

In [317]:
con1 = (dfr['mojari'] == True) 
con2 = (dfr['women'] == True)


dfr.loc[con1 & con2, 'mojaris_women'] = True

In [318]:
con1 = (dfr['mojari'] == True) 
con2 = (dfr['men'] == True)


dfr.loc[con1 & con2, 'mojaris_men'] = True

In [319]:
con1 = (dfr['legging'] == True) 
con2 = (dfr['salwar'] == True)


dfr.loc[con1 | con2, 'leggings_and_salwars'] = True

In [320]:
dfr.leggings_and_salwars.nunique()

2

In [321]:
dfr.drop(['men', 'women', 'legging','salwar','mojari'], axis=1, inplace=True)

In [322]:
dfr.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti,saree,...,petticoat,blouse,dupatta,gown,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,0,https://m.media-amazon.com/images/I/81LOPbFPiQ...,images/val/0.jpeg,Generic,Women's Khadi Cotton Saree With Blouse Piece (...,saree,NaN,False,False,True,...,False,True,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81Q8Oktw4s...,images/val/1.jpeg,Yashvi Designer,Women's Net Saree With Unstitched Blouse Piece,saree,NaN,False,False,True,...,False,True,False,False,False,False,False,False,False,False
2,2,https://m.media-amazon.com/images/I/613S1YGCmo...,images/val/2.jpeg,Aarrah,Georgette Strip Print Saree[S_SHIKHA30021SR02_...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/819budhQl1...,images/val/3.jpeg,MIMOSA,Women's Patola Style Art Silk Saree (Green),saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/61cAZ94ZQV...,images/val/4.jpeg,Generic,Women's Pure Hand Block Patola Printed Cotton ...,saree,NaN,False,False,True,...,False,True,False,False,False,False,False,False,False,False

In [323]:
con1 = (dfr['class_label'] == 'saree') 
con2 = (dfr['blouse'] == True)


dfr.loc[con1 & con2, 'blouse'] = False

In [324]:
dfr.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti,saree,...,petticoat,blouse,dupatta,gown,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,0,https://m.media-amazon.com/images/I/81LOPbFPiQ...,images/val/0.jpeg,Generic,Women's Khadi Cotton Saree With Blouse Piece (...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81Q8Oktw4s...,images/val/1.jpeg,Yashvi Designer,Women's Net Saree With Unstitched Blouse Piece,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,2,https://m.media-amazon.com/images/I/613S1YGCmo...,images/val/2.jpeg,Aarrah,Georgette Strip Print Saree[S_SHIKHA30021SR02_...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/819budhQl1...,images/val/3.jpeg,MIMOSA,Women's Patola Style Art Silk Saree (Green),saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/61cAZ94ZQV...,images/val/4.jpeg,Generic,Women's Pure Hand Block Patola Printed Cotton ...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [325]:
dfr.loc[1]

number                                                                  1
image_url               https://m.media-amazon.com/images/I/81Q8Oktw4s...
image_path                                              images/val/1.jpeg
brand                                                     Yashvi Designer
product_title              Women's Net Saree With Unstitched Blouse Piece
class_label                                                         saree
color                                                                 NaN
kurta                                                               False
dhoti                                                               False
saree                                                                True
sherwani                                                            False
palazzo                                                             False
nehru                                                               False
petticoat                                                           False
blouse                                                              False
dupatta                                                             False
gown                                                                False
lehenga                                                             False
women_kurta                                                         False
kurta_men                                                           False
mojaris_men                                                         False
mojaris_women                                                       False
leggings_and_salwars                                                False
Name: 1, dtype: object

In [326]:
dfk = dfr[dfr.kurta == True]

In [327]:
dfk1 = dfk[dfk.kurta_men == False]

In [328]:
dfk2 = dfk1[dfk1.women_kurta == False]

In [329]:
dfk2.shape

(66, 23)

In [330]:
dfk2m = dfk2[dfk2.class_label == 'kurta_men']

In [331]:
dfk2w = dfk2[dfk2.class_label == 'women_kurta']

In [332]:
dfk2n = dfk2[dfk2.class_label != 'kurta_men']

In [333]:
dfk2n = dfk2n[dfk2.class_label != 'women_kurta']

/var/folders/nv/lggm200n09vgfy5n8_6lcz6c0000gn/T/ipykernel_5323/1037558784.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  dfk2n = dfk2n[dfk2.class_label != 'women_kurta']

In [334]:
dfk2n.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti,saree,...,petticoat,blouse,dupatta,gown,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
1058,1058,https://m.media-amazon.com/images/I/71GkvrScZ9...,images/val/1058.jpeg,BHARATASYA,Brown Block Printed Cotton Slub Short Kurta,dhoti_pants,NaN,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1437,1437,https://m.media-amazon.com/images/I/61OzzjttQr...,images/val/1437.jpeg,Generic,Taani Creations Kurta Dhoti Set Red,dhoti_pants,NaN,True,True,False,...,False,False,False,False,False,False,False,False,False,False
1539,1539,https://m.media-amazon.com/images/I/51p1lMGseG...,images/val/1539.jpeg,KSUT,Black Yoke and Cuff Embroidered Straight Kurta...,dupattas,NaN,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1814,1814,https://m.media-amazon.com/images/I/71EmdSjsNo...,images/val/1814.jpeg,Divyank,Straight Kurta Pant Dupatta Set with Details K...,dupattas,NaN,True,False,False,...,False,False,True,False,False,False,False,False,False,False
1951,1951,https://m.media-amazon.com/images/I/51PhpNj1a9...,images/val/1951.jpeg,Stylum,Solid Rayon Straight Kurta Pant & Dupatta Set,dupattas,NaN,True,False,False,...,False,False,True,False,False,False,False,False,False,False

In [335]:
dfk2n.shape

(19, 23)

In [336]:
dfr.iloc[6948, 4]

'Tamer Brown Printed Dupion Silk Bandi with White Printed Silkmul Kurta and Churidar'

In [337]:
dfr.columns

Index(['number', 'image_url', 'image_path', 'brand', 'product_title',
       'class_label', 'color', 'kurta', 'dhoti', 'saree', 'sherwani',
       'palazzo', 'nehru', 'petticoat', 'blouse', 'dupatta', 'gown', 'lehenga',
       'women_kurta', 'kurta_men', 'mojaris_men', 'mojaris_women',
       'leggings_and_salwars'],
      dtype='object')

In [338]:
dfr.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti,saree,...,petticoat,blouse,dupatta,gown,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,0,https://m.media-amazon.com/images/I/81LOPbFPiQ...,images/val/0.jpeg,Generic,Women's Khadi Cotton Saree With Blouse Piece (...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81Q8Oktw4s...,images/val/1.jpeg,Yashvi Designer,Women's Net Saree With Unstitched Blouse Piece,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,2,https://m.media-amazon.com/images/I/613S1YGCmo...,images/val/2.jpeg,Aarrah,Georgette Strip Print Saree[S_SHIKHA30021SR02_...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/819budhQl1...,images/val/3.jpeg,MIMOSA,Women's Patola Style Art Silk Saree (Green),saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/61cAZ94ZQV...,images/val/4.jpeg,Generic,Women's Pure Hand Block Patola Printed Cotton ...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [339]:
dfr = dfr.rename({'dhoti':'dhoti_pants', 'sherwani':'sherwanis', 'palazzo':'palazzos', 
             'nehru':'nehru_jackets', 'petticoat':'petticoats', 'dupatta':'dupattas', 
             'gown':'gowns'},axis=1)
dfr.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,0,https://m.media-amazon.com/images/I/81LOPbFPiQ...,images/val/0.jpeg,Generic,Women's Khadi Cotton Saree With Blouse Piece (...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
1,1,https://m.media-amazon.com/images/I/81Q8Oktw4s...,images/val/1.jpeg,Yashvi Designer,Women's Net Saree With Unstitched Blouse Piece,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
2,2,https://m.media-amazon.com/images/I/613S1YGCmo...,images/val/2.jpeg,Aarrah,Georgette Strip Print Saree[S_SHIKHA30021SR02_...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
3,3,https://m.media-amazon.com/images/I/819budhQl1...,images/val/3.jpeg,MIMOSA,Women's Patola Style Art Silk Saree (Green),saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,4,https://m.media-amazon.com/images/I/61cAZ94ZQV...,images/val/4.jpeg,Generic,Women's Pure Hand Block Patola Printed Cotton ...,saree,NaN,False,False,True,...,False,False,False,False,False,False,False,False,False,False

In [340]:
columns = ['dhoti_pants', 'saree', 'sherwanis', 'palazzos', 'nehru_jackets', 'petticoats',
           'blouse','dupattas', 'gowns', 'lehenga', 'women_kurta', 'kurta_men', 
           'mojaris_men', 'mojaris_women', 'leggings_and_salwars']

def func(x):
    if x == True:
        return 1
    else:
        return 0
for column in columns:    
    dfr[str(column)] = dfr[str(column)].apply(lambda x: func(x))

In [341]:
#dfw = dfvr[dfvr.class_label == 'women_kurta']

In [342]:
dfr.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,0,https://m.media-amazon.com/images/I/81LOPbFPiQ...,images/val/0.jpeg,Generic,Women's Khadi Cotton Saree With Blouse Piece (...,saree,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,https://m.media-amazon.com/images/I/81Q8Oktw4s...,images/val/1.jpeg,Yashvi Designer,Women's Net Saree With Unstitched Blouse Piece,saree,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,0
2,2,https://m.media-amazon.com/images/I/613S1YGCmo...,images/val/2.jpeg,Aarrah,Georgette Strip Print Saree[S_SHIKHA30021SR02_...,saree,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,0
3,3,https://m.media-amazon.com/images/I/819budhQl1...,images/val/3.jpeg,MIMOSA,Women's Patola Style Art Silk Saree (Green),saree,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,0
4,4,https://m.media-amazon.com/images/I/61cAZ94ZQV...,images/val/4.jpeg,Generic,Women's Pure Hand Block Patola Printed Cotton ...,saree,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,0

In [343]:
dfr.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
7495,7495,https://m.media-amazon.com/images/I/614GvuaIJu...,images/val/7495.jpeg,ishin,Women's Rayon Pink Printed A-Line Kurta Palazz...,women_kurta,NaN,True,0,0,...,0,0,0,0,0,1,0,0,0,0
7496,7496,https://m.media-amazon.com/images/I/81WAbf4-ao...,images/val/7496.jpeg,Cotton Culture,Women's Kesar Pink Cotton Straight Kurta,women_kurta,NaN,True,0,0,...,0,0,0,0,0,1,0,0,0,0
7497,7497,https://m.media-amazon.com/images/I/61unbmOA7k...,images/val/7497.jpeg,Bae's Wardrobe,Printed Rayon Anarkali Kurti with Plazzo Pant ...,women_kurta,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,0
7498,7498,https://m.media-amazon.com/images/I/71zULAnVNY...,images/val/7498.jpeg,Aarika,Girl's Regular Dress,women_kurta,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,0
7499,7499,https://m.media-amazon.com/images/I/71mhB7xFHt...,images/val/7499.jpeg,Aurelia,Women's Straight Kurta,women_kurta,NaN,True,0,0,...,0,0,0,0,0,1,0,0,0,0

In [344]:
dfr.iloc[7498,4]

"Girl's Regular Dress"

In [345]:
dfr.iloc[1001,4]

'Sweet Threadz Cotton Viscose Lycra Dhoti Patiyala Salwar Harem Bottoms Pants Light Skin Yellow Combo Pack of 2'

In [346]:
dfr.iloc[1001]

number                                                               1001
image_url               https://m.media-amazon.com/images/I/41MEH6wJ2v...
image_path                                           images/val/1001.jpeg
brand                                                             Generic
product_title           Sweet Threadz Cotton Viscose Lycra Dhoti Patiy...
class_label                                                   dhoti_pants
color                                                                 NaN
kurta                                                               False
dhoti_pants                                                             1
saree                                                                   0
sherwanis                                                               0
palazzos                                                                0
nehru_jackets                                                           0
petticoats                                                              0
blouse                                                                  0
dupattas                                                                0
gowns                                                                   0
lehenga                                                                 0
women_kurta                                                             0
kurta_men                                                               0
mojaris_men                                                             0
mojaris_women                                                           0
leggings_and_salwars                                                    1
Name: 1001, dtype: object

In [347]:
dfr.columns

Index(['number', 'image_url', 'image_path', 'brand', 'product_title',
       'class_label', 'color', 'kurta', 'dhoti_pants', 'saree', 'sherwanis',
       'palazzos', 'nehru_jackets', 'petticoats', 'blouse', 'dupattas',
       'gowns', 'lehenga', 'women_kurta', 'kurta_men', 'mojaris_men',
       'mojaris_women', 'leggings_and_salwars'],
      dtype='object')

In [348]:
c1 = (dfr.saree == 0)
c2 = (dfr.dhoti_pants == 0)
c3 = (dfr.sherwanis == 0)
c4 = (dfr.palazzos == 0)
c5 = (dfr.nehru_jackets == 0)
c6 = (dfr.petticoats == 0)
c7 = (dfr.blouse == 0)
c8 = (dfr.dupattas == 0)
c9 = (dfr.gowns == 0)
c10 = (dfr.lehenga == 0)
c11 = (dfr.women_kurta == 0)
c12 = (dfr.kurta_men == 0)
c13 = (dfr.leggings_and_salwars == 0)
c14 = (dfr.mojaris_men == 0)
c15 = (dfr.mojaris_women == 0)


dfr.loc[c1 & c2 & c3 & c4 & c5 & c6 & c7 & c8 & c9 & c10 & c11 & c12 & c13 & c14 & c15,'none'] = 1

In [349]:
df_none = dfr[dfr.none == 1]

In [350]:
df_none.shape

(1925, 24)

In [351]:
df_none.class_label.unique()

array(['saree', 'blouse', 'dhoti_pants', 'dupattas', 'gowns', 'kurta_men',
       'leggings_and_salwars', 'lehenga', 'mojaris_men', 'mojaris_women',
       'nehru_jackets', 'palazzos', 'petticoats', 'sherwanis',
       'women_kurta'], dtype=object)

In [352]:
df_none.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
24,24,https://m.media-amazon.com/images/I/81mBodx4HO...,images/val/24.jpeg,S Kiran's,"Women's Plain Weave Art Silk Mekhela, Chador W...",saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
264,264,https://m.media-amazon.com/images/I/416T+6-lrp...,images/val/264.jpeg,Handloomz,Aambal® Kuthampully Kasavu Hand worked Silver ...,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
317,317,https://m.media-amazon.com/images/I/811gye-WV5...,images/val/317.jpeg,Rekha enterprise,kashmiri mirror,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
387,387,https://m.media-amazon.com/images/I/71uEPWMtf-...,images/val/387.jpeg,Vastrangam,Women's Nylon Art Silk Sibori Print Sari With ...,saree,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
716,716,https://m.media-amazon.com/images/I/71OUyPt6nb...,images/val/716.jpeg,Prapti Fashion,vel-Maroon,blouse,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [353]:
df_none.loc[24]

number                                                                 24
image_url               https://m.media-amazon.com/images/I/81mBodx4HO...
image_path                                             images/val/24.jpeg
brand                                                           S Kiran's
product_title           Women's Plain Weave Art Silk Mekhela, Chador W...
class_label                                                         saree
color                                                                 NaN
kurta                                                               False
dhoti_pants                                                             0
saree                                                                   0
sherwanis                                                               0
palazzos                                                                0
nehru_jackets                                                           0
petticoats                                                              0
blouse                                                                  0
dupattas                                                                0
gowns                                                                   0
lehenga                                                                 0
women_kurta                                                             0
kurta_men                                                               0
mojaris_men                                                             0
mojaris_women                                                           0
leggings_and_salwars                                                    0
none                                                                  1.0
Name: 24, dtype: object

In [354]:
df_none.iloc[0,4]

"Women's Plain Weave Art Silk Mekhela, Chador With Blouse Piece (PolyGold5089Yellow_Yellow)"

In [355]:
df_none.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
7478,7478,https://m.media-amazon.com/images/I/312YqiTF9L...,images/val/7478.jpeg,House Of Libaaz,Women's Kurti Pants Set in Premium Cotton Fabr...,women_kurta,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
7479,7479,https://m.media-amazon.com/images/I/81R5S9PekS...,images/val/7479.jpeg,JPM brothers,Women’s Cotton A-Line Kurti with Shrug,women_kurta,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
7492,7492,https://m.media-amazon.com/images/I/81vg2JI6-x...,images/val/7492.jpeg,Women Touch,Designer Anarkali Dress for Women,women_kurta,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
7497,7497,https://m.media-amazon.com/images/I/61unbmOA7k...,images/val/7497.jpeg,Bae's Wardrobe,Printed Rayon Anarkali Kurti with Plazzo Pant ...,women_kurta,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
7498,7498,https://m.media-amazon.com/images/I/71zULAnVNY...,images/val/7498.jpeg,Aarika,Girl's Regular Dress,women_kurta,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [356]:
c1 = (dfr.class_label == 'saree')
c2 = (dfr.none == 1)

dfr.loc[c1 & c2,'saree'] = 1
dfr.loc[c1 & c2,'none'] = 0

In [357]:
dfs = dfr[dfr.class_label == 'saree']

In [358]:
dfsn = dfs[dfs.none == 1]
dfsn.shape

(0, 24)

In [359]:
c1 = (dfr.class_label == 'women_kurta')
c2 = (dfr.kurta == 1)
c3 = (dfr.none == 1)

dfr.loc[c1 & c2 & c3,'women_kurta'] = 1
dfr.loc[c1 & c2 & c3,'none'] = 0

In [360]:
c1 = (dfr.class_label == 'kurta_men')
c2 = (dfr.kurta == 1)
c3 = (dfr.none == 1)

dfr.loc[c1 & c2 & c3,'kurta_men'] = 1
dfr.loc[c1 & c2 & c3,'none'] = 0

In [361]:
df_none = dfr[dfr.none == 1]

In [362]:
df_none.shape

(1878, 24)

In [363]:
df_none.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
716,716,https://m.media-amazon.com/images/I/71OUyPt6nb...,images/val/716.jpeg,Prapti Fashion,vel-Maroon,blouse,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
745,745,https://m.media-amazon.com/images/I/61wTq9Jkaw...,images/val/745.jpeg,SP ENTERPRISE,Designer Lycra Blause For Women(Red),blouse,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
800,800,https://m.media-amazon.com/images/I/610CA2pEYm...,images/val/800.jpeg,SP ENTERPRISE,Designer Lycra Blause For Women(Pink),blouse,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
839,839,https://m.media-amazon.com/images/I/71HAbkwaII...,images/val/839.jpeg,Mesmore,Women's Phantom Silk Floral Design Hand Embroi...,blouse,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
846,846,https://m.media-amazon.com/images/I/81KPFHhceI...,images/val/846.jpeg,Yogeshwar creation,Radha Krishna,blouse,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [364]:
df_none.class_label.unique()

array(['blouse', 'dhoti_pants', 'dupattas', 'gowns', 'kurta_men',
       'leggings_and_salwars', 'lehenga', 'mojaris_men', 'mojaris_women',
       'nehru_jackets', 'palazzos', 'petticoats', 'sherwanis',
       'women_kurta'], dtype=object)

In [365]:
df_none.iloc[0,4]

'vel-Maroon'

In [366]:
df_none_dupattas = df_none[df_none.class_label == 'dupattas']

In [367]:
df_none_dupattas.shape

(38, 24)

In [368]:
df_none_dupattas.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
1501,1501,https://m.media-amazon.com/images/I/41pWWjX8hf...,images/val/1501.jpeg,Monika Collection,Women's Black Printed Rayon Soft Stole Size 70...,dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1520,1520,https://m.media-amazon.com/images/I/819coPVpZN...,images/val/1520.jpeg,Fabwomen Cotton Blend Printed Dupatta for Women,(Free Size),dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1522,1522,https://m.media-amazon.com/images/I/81+WH346Ym...,images/val/1522.jpeg,Monte Carlo,Women's Cotton Winter Accessory Set (220STL304...,dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1524,1524,https://m.media-amazon.com/images/I/71dbRatOby...,images/val/1524.jpeg,Linen Club,"Women's Linen Printed Stole (BBAPLLC88897, Red)",dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1538,1538,https://m.media-amazon.com/images/I/81DAtizC2U...,images/val/1538.jpeg,Nivah Fashion,Women's Georgette Embroidery Dress Material,dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [369]:
dupattas = dfr[dfr.class_label == 'dupattas']

In [370]:
dupattas.shape

(500, 24)

In [371]:
dfr.shape

(7500, 24)

In [372]:
dup = df_none_dupattas.index

In [373]:
dfr = dfr.drop(dup)

In [374]:
dfr.shape

(7462, 24)

In [375]:
df_none = dfr[dfr.none == 1]

In [376]:
df_none.shape

(1840, 24)

In [377]:
df_none_dupattas.iloc[0,4]

"Women's Black Printed Rayon Soft Stole Size 70x180cm"

In [378]:
df_none_dupattas.iloc[4,4]

"Women's Georgette Embroidery Dress Material"

In [379]:
dfg = df_none[df_none.class_label == 'gowns' ]
dfg.shape

(100, 24)

In [380]:
dfg.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
2001,2001,https://m.media-amazon.com/images/I/51bhwOouGo...,images/val/2001.jpeg,Trendy Fab,Silver Organisation Women's Rayon Traditional ...,gowns,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
2011,2011,https://m.media-amazon.com/images/I/71scd7ZJvT...,images/val/2011.jpeg,Silver Organisation,Womens Cotton Dress Material(Son_674_Multi-Col...,gowns,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
2012,2012,https://m.media-amazon.com/images/I/61Mq1Z+AMY...,images/val/2012.jpeg,Generic,Women Rayon Printed Kurti Rama,gowns,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
2019,2019,https://m.media-amazon.com/images/I/81yTtVTiAN...,images/val/2019.jpeg,6TH AVENUE STREETWEAR,VAASTRA 6TH Avenue Streetwear Women's Cotton D...,gowns,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
2025,2025,https://m.media-amazon.com/images/I/71+QBB59+S...,images/val/2025.jpeg,Lavina,Women Peacock blue Rayon Casual Short Kurti.,gowns,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [381]:
dfg.iloc[0,4]

"Silver Organisation Women's Rayon Traditional Jaipuri Print Semi-StitchedTrendy Trendy Fabric (FRK_481, Multicolour, Free Size)"

In [382]:
dfg.iloc[1,4]

'Womens Cotton Dress Material(Son_674_Multi-Coloured_)'

In [383]:
dfg.iloc[2,4]

'Women Rayon Printed Kurti Rama'

In [384]:
dfg.iloc[3,4]

"VAASTRA 6TH Avenue Streetwear Women's Cotton Dress (Blue; Free Size)"

In [385]:
dfg['gowns'] = dfr.product_title.str.contains('dress', flags=re.IGNORECASE)

/var/folders/nv/lggm200n09vgfy5n8_6lcz6c0000gn/T/ipykernel_5323/2467206437.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfg['gowns'] = dfr.product_title.str.contains('dress', flags=re.IGNORECASE)

In [386]:
dfgd = dfg[dfg['gowns'] == True]

In [387]:
dfgd.shape

(58, 24)

In [388]:
c1 = (dfg.gowns == True)
c2 = (dfr.none == 1)
dfr.loc[c1 & c2,'gowns'] = 1
dfr.loc[c1 & c2,'none'] = 0

In [389]:
dfkm = df_none[df_none.class_label == 'kurta_men']
dfkm.shape

(25, 24)

In [390]:
dfkm.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
2523,2523,https://m.media-amazon.com/images/I/71hCLs5t0z...,images/val/2523.jpeg,Ethnix by Raymond,Men's Regular Tunic Shirt,kurta_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
2534,2534,https://m.media-amazon.com/images/I/81BQ-WWY2c...,images/val/2534.jpeg,Ethnix by Raymond,Men's Regular Tunic Shirt (RTKB00855-O5_Medium...,kurta_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
2562,2562,https://m.media-amazon.com/images/I/91kC7+dDnN...,images/val/2562.jpeg,Ethnix by Raymond,Men's Regular Tunic Shirt (RTKB01713-MR_Rust 92),kurta_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
2575,2575,https://m.media-amazon.com/images/I/51P9MYE-71...,images/val/2575.jpeg,Sanwara,Men's Regular Shirt,kurta_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
2582,2582,https://m.media-amazon.com/images/I/81VZhAMXIv...,images/val/2582.jpeg,Ethnix by Raymond,Men's Regular Tunic Shirt (RTKB00713-L2_Light ...,kurta_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [391]:
mkur = df_none.index[df_none.class_label == 'kurta_men']

In [392]:
dfr.shape

(7462, 24)

In [393]:
dfr = dfr.drop(mkur)

In [394]:
dfr.shape

(7437, 24)

In [395]:
dfl = df_none[df_none.class_label == 'leggings_and_salwars']

In [396]:
dfl.shape

(129, 24)

In [397]:
dfl.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
3011,3011,https://m.media-amazon.com/images/I/41pbx-Mo-N...,images/val/3011.jpeg,PI World,Cotton Blend Solid Patiala Beige Orange,leggings_and_salwars,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3021,3021,https://m.media-amazon.com/images/I/615cOLjkJa...,images/val/3021.jpeg,NEHA FASHION [Neha Fashion],NEHA FASHION [Neha Fashion] Women's Cotton Dre...,leggings_and_salwars,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3023,3023,https://m.media-amazon.com/images/I/71r7gQIFMw...,images/val/3023.jpeg,Aurelia,Women's Cotton Chudidar Bottom,leggings_and_salwars,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3026,3026,https://rukminim1.flixcart.com/image/309/371/j...,images/val/3026.jpeg,INDIAN FLOWER,Viscose Solid Patiala,leggings_and_salwars,N/A,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3034,3034,https://m.media-amazon.com/images/I/71V7tW5Azd...,images/val/3034.jpeg,W for Woman,Chudidar Synthetic Bottom,leggings_and_salwars,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [398]:
c1 = (dfr.product_title.str.contains('churidar', flags=re.IGNORECASE))
c2 = (dfr.product_title.str.contains('patiala', flags=re.IGNORECASE))
c3 = (dfr.none == 1)
dfr.loc[(c1 | c2) & c3, 'leggings_and_salwars'] = 1
dfr.loc[(c1 | c2) & c3, 'none'] = 0

In [399]:
df_none = dfr[dfr.none == 1]
df_none.shape

(1667, 24)

In [400]:
dfle = df_none[df_none.class_label == 'lehenga']
dfle.shape

(167, 24)

In [401]:
dfle.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
3503,3503,N/A,images/val/3503.jpg,N/A,N/A,lehenga,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3504,3504,N/A,images/val/3504.jpeg,N/A,N/A,lehenga,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3507,3507,N/A,images/val/3507.jpg,N/A,N/A,lehenga,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3511,3511,N/A,images/val/3511.jpg,N/A,N/A,lehenga,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3512,3512,N/A,images/val/3512.jpeg,N/A,N/A,lehenga,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [402]:
dflef = dfr[dfr.class_label == 'lehenga']

In [403]:
dflef.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
3500,3500,"https://assets.myntassets.com/h_720,q_90,w_540...",images/val/3500.jpeg,MIMOSA,Pink &amp; Navy Blue Embroidered Semi-Stitched...,lehenga,NaN,False,0,0,...,1,1,0,1,0,0,0,0,0,NaN
3501,3501,"https://assets.myntassets.com/h_720,q_90,w_540...",images/val/3501.jpeg,Pothys,Brown &amp; Orange Poly Chiffon Woven Design H...,lehenga,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,NaN
3502,3502,"https://assets.myntassets.com/h_720,q_90,w_540...",images/val/3502.jpeg,Bitiya by Bhama,Black Ready to Wear Lehenga with Top,lehenga,NaN,False,0,0,...,0,0,0,1,0,0,0,0,0,NaN
3503,3503,N/A,images/val/3503.jpg,N/A,N/A,lehenga,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
3504,3504,N/A,images/val/3504.jpeg,N/A,N/A,lehenga,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [404]:
dflef.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
3995,3995,"https://assets.myntassets.com/h_720,q_90,w_540...",images/val/3995.jpeg,SHOPGARB,Grey &amp; Silver Embroidered Semi-Stitched Le...,lehenga,NaN,False,0,0,...,1,1,0,1,0,0,0,0,0,NaN
3996,3996,https://assets0.mirraw.com/images/7724588/09-B...,images/val/3996.jpeg,Mirraw,Orange Embroidered Foil Readymade Lehenga Cholis,lehenga,NaN,False,0,0,...,0,0,0,1,0,0,0,0,0,NaN
3997,3997,"https://assets.myntassets.com/h_720,q_90,w_540...",images/val/3997.jpeg,Chhabra 555,Women Green &amp; Golden Made to Measure Lehen...,lehenga,NaN,False,0,0,...,0,1,0,1,0,0,0,0,0,NaN
3998,3998,"https://assets.myntassets.com/h_720,q_90,w_540...",images/val/3998.jpeg,Pothys,Maroon Embroidered Half Saree,lehenga,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,NaN
3999,3999,N/A,images/val/3999.jpg,N/A,N/A,lehenga,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [405]:
dfleff = dflef[dflef.product_title == 'N/A']
dfleff.shape

(160, 24)

In [406]:
c1 = (dfr.product_title == 'N/A') 
c2 = (dfr.class_label == 'lehenga')
c3 = (dfr.none == 1)
dfr.loc[c1 & c2 & c3, 'lehenga'] = 1
dfr.loc[c1 & c2 & c3, 'none'] = 0

In [407]:
df_none = dfr[dfr.none == 1]
df_none.shape

(1507, 24)

In [408]:
df_none.columns

Index(['number', 'image_url', 'image_path', 'brand', 'product_title',
       'class_label', 'color', 'kurta', 'dhoti_pants', 'saree', 'sherwanis',
       'palazzos', 'nehru_jackets', 'petticoats', 'blouse', 'dupattas',
       'gowns', 'lehenga', 'women_kurta', 'kurta_men', 'mojaris_men',
       'mojaris_women', 'leggings_and_salwars', 'none'],
      dtype='object')

In [409]:
dfpe = df_none[df_none.class_label == 'petticoats']
dfpe.shape

(112, 24)

In [410]:
dfpe.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
6000,6000,N/A,images/val/6000.jpeg,N/A,N/A,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
6001,6001,N/A,images/val/6001.jpeg,N/A,N/A,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
6004,6004,N/A,images/val/6004.jpg,N/A,N/A,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
6005,6005,N/A,images/val/6005.jpg,N/A,N/A,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
6009,6009,N/A,images/val/6009.jpeg,N/A,N/A,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [411]:
dfpe.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
6488,6488,N/A,images/val/6488.jpg,N/A,N/A,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
6490,6490,N/A,images/val/6490.jpeg,N/A,N/A,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
6492,6492,N/A,images/val/6492.jpg,N/A,N/A,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
6494,6494,N/A,images/val/6494.png,N/A,N/A,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
6495,6495,https://m.media-amazon.com/images/I/71PIgM2Dm6...,images/val/6495.jpeg,HAIYUN,Shapewear Compression Tank Top for Women Slimm...,petticoats,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [412]:
pet = df_none.index[df_none.class_label == 'petticoats']

In [413]:
dfr = dfr.drop(pet)
dfr.shape

(7325, 24)

In [414]:
dfnj = df_none[df_none.class_label == 'nehru_jackets']
dfnj.shape

(171, 24)

In [415]:
dfnj.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
5000,5000,https://m.media-amazon.com/images/I/615+eI1ORR...,images/val/5000.jpeg,Routeen,Maroon Casual Ethnic Modi jacket waistcoat for...,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5003,5003,https://rukminim1.flixcart.com/image/309/371/j...,images/val/5003.jpeg,Fuzion Couture,Sleeveless Solid Men Jacket,nehru_jackets,N/A,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5004,5004,https://m.media-amazon.com/images/I/81aM7+9jJH...,images/val/5004.jpeg,Panache,Men's Poly Cotton Ethnic Jacket,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5007,5007,https://rukminim1.flixcart.com/image/309/371/k...,images/val/5007.jpeg,Klotthe,Sleeveless Printed Men Jacket,nehru_jackets,N/A,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5008,5008,N/A,images/val/5008.jpeg,N/A,N/A,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [416]:
dfnj.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
5483,5483,https://m.media-amazon.com/images/I/61Dhu1Alac...,images/val/5483.jpeg,MODI JACKET,Men's Grey Self Design Terry Rayon Jacket,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5489,5489,https://m.media-amazon.com/images/I/619w+jaYt7...,images/val/5489.jpeg,Maxence,Elegant Waistcoat For Men Ethnic Wear Beige Co...,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5494,5494,https://m.media-amazon.com/images/I/91kCgXJrNg...,images/val/5494.jpeg,Sobre Estilo,Men's Banded Collar Linen Jacket,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5498,5498,https://m.media-amazon.com/images/I/51lSAjdLpE...,images/val/5498.jpeg,Golden Bird,Wine Red Color Modi Linen Jacket for Men,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5499,5499,N/A,images/val/5499.jpeg,N/A,N/A,nehru_jackets,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [417]:
dfr.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
0,0,https://m.media-amazon.com/images/I/81LOPbFPiQ...,images/val/0.jpeg,Generic,Women's Khadi Cotton Saree With Blouse Piece (...,saree,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,NaN
1,1,https://m.media-amazon.com/images/I/81Q8Oktw4s...,images/val/1.jpeg,Yashvi Designer,Women's Net Saree With Unstitched Blouse Piece,saree,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,NaN
2,2,https://m.media-amazon.com/images/I/613S1YGCmo...,images/val/2.jpeg,Aarrah,Georgette Strip Print Saree[S_SHIKHA30021SR02_...,saree,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,NaN
3,3,https://m.media-amazon.com/images/I/819budhQl1...,images/val/3.jpeg,MIMOSA,Women's Patola Style Art Silk Saree (Green),saree,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,NaN
4,4,https://m.media-amazon.com/images/I/61cAZ94ZQV...,images/val/4.jpeg,Generic,Women's Pure Hand Block Patola Printed Cotton ...,saree,NaN,False,0,1,...,0,0,0,0,0,0,0,0,0,NaN

In [418]:
dfnj = dfr[dfr.class_label == 'nehru_jackets']
dfnj.shape

(500, 24)

In [419]:
df_none_dupattas.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
1501,1501,https://m.media-amazon.com/images/I/41pWWjX8hf...,images/val/1501.jpeg,Monika Collection,Women's Black Printed Rayon Soft Stole Size 70...,dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1520,1520,https://m.media-amazon.com/images/I/819coPVpZN...,images/val/1520.jpeg,Fabwomen Cotton Blend Printed Dupatta for Women,(Free Size),dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1522,1522,https://m.media-amazon.com/images/I/81+WH346Ym...,images/val/1522.jpeg,Monte Carlo,Women's Cotton Winter Accessory Set (220STL304...,dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1524,1524,https://m.media-amazon.com/images/I/71dbRatOby...,images/val/1524.jpeg,Linen Club,"Women's Linen Printed Stole (BBAPLLC88897, Red)",dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1538,1538,https://m.media-amazon.com/images/I/81DAtizC2U...,images/val/1538.jpeg,Nivah Fashion,Women's Georgette Embroidery Dress Material,dupattas,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [420]:
c1 = (dfr.product_title == 'N/A') 
c2 = (dfr.class_label == 'lehenga')
c3 = (dfr.none == 1)

dfr.loc[c1 & c2 & c3, 'lehenga'] = 1
dfr.loc[c1 & c2 & c3, 'none'] = 0

In [421]:
c1 = (dfr.class_label == 'nehru_jackets')
c2 = (dfr.none == 1)

dfr.loc[c1 & c2, 'nehru_jackets'] = 1
dfr.loc[c1 & c2, 'none'] = 0

In [422]:
dfmm = df_none[df_none.class_label == 'mojaris_men']
dfmm.shape

(275, 24)

In [423]:
dfmm.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
4002,4002,N/A,images/val/4002.jpeg,N/A,N/A,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4004,4004,https://m.media-amazon.com/images/I/71nkEIYwmX...,images/val/4004.jpeg,Black Wings,Men's Decent Loafers for Boys in Casual Or Off...,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4006,4006,https://m.media-amazon.com/images/I/41qgEGqi5Q...,images/val/4006.jpeg,lottary,Men Ethinic Footwear,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4007,4007,N/A,images/val/4007.jpeg,N/A,N/A,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4008,4008,N/A,images/val/4008.jpeg,N/A,N/A,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [424]:
dfmm.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
4488,4488,https://m.media-amazon.com/images/I/61ovMLzF4N...,images/val/4488.jpeg,Step n Style,Ladies Gold Pearl & Kundan Work Punjabi Jutti ...,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4490,4490,https://m.media-amazon.com/images/I/61vJGFcMcv...,images/val/4490.jpeg,FAUSTO,Men's Loafers & Mocassins Casual Shoes,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4492,4492,https://rukminim1.flixcart.com/image/309/371/k...,images/val/4492.jpeg,grow,Party Wear For Men,mojaris_men,N/A,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4495,4495,https://m.media-amazon.com/images/I/61i49ZdDO5...,images/val/4495.jpeg,Kraasa,Men's Casual Loafers,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4498,4498,https://m.media-amazon.com/images/I/71tIMdOqHZ...,images/val/4498.jpeg,Vellinto,Ethnic Mules for Men Open Jutis for Men Clogs ...,mojaris_men,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [425]:
mo = dfmm.index
dfr = dfr.drop(mo)

In [426]:
dfr.shape

(7050, 24)

In [427]:
dfmw = df_none[df_none.class_label == 'mojaris_women']
dfmw.shape

(257, 24)

In [428]:
dfmw.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
4500,4500,https://m.media-amazon.com/images/I/81CnpgwptA...,images/val/4500.jpeg,Perrots,Embroidery Work Adjustable Belt Fashionable Et...,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4505,4505,https://m.media-amazon.com/images/I/81ec7DpZOE...,images/val/4505.jpeg,Shree,Rajasthani Jaipuri Ethnic Womens Girls Ladies ...,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4508,4508,https://m.media-amazon.com/images/I/61yRfUg8s5...,images/val/4508.jpeg,Atulit,Stylish Bellies and Loafers for Women and Ladies.,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4509,4509,https://rukminim1.flixcart.com/image/309/371/k...,images/val/4509.jpeg,Azzra,Women's Leather Juttis Bite and Pinch Free Jut...,mojaris_women,Multicolor,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4510,4510,https://m.media-amazon.com/images/I/71baE8va3E...,images/val/4510.jpeg,5 ELEMENTS,Helen Silver Hand Embroidered Leather Juti for...,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [429]:
dfmw.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
4992,4992,N/A,images/val/4992.jpeg,N/A,N/A,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4993,4993,N/A,images/val/4993.jpeg,N/A,N/A,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4995,4995,https://m.media-amazon.com/images/I/71UF7Zcq+n...,images/val/4995.jpeg,Classico,Soft Leather Ethnic Women's Footwear,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4997,4997,https://m.media-amazon.com/images/I/712ag37WbQ...,images/val/4997.jpeg,RSK Ethnic Wear,Golden Color Mirror and Kuttdana Work Jutti wi...,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
4999,4999,https://m.media-amazon.com/images/I/61qk-G6lI-...,images/val/4999.jpeg,RearStep,Newly Designed Mojri for Women for Daily Colle...,mojaris_women,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [430]:
mw = dfmw.index
dfr = dfr.drop(mw)

In [431]:
dfr.shape

(6793, 24)

In [432]:
df_none.columns

Index(['number', 'image_url', 'image_path', 'brand', 'product_title',
       'class_label', 'color', 'kurta', 'dhoti_pants', 'saree', 'sherwanis',
       'palazzos', 'nehru_jackets', 'petticoats', 'blouse', 'dupattas',
       'gowns', 'lehenga', 'women_kurta', 'kurta_men', 'mojaris_men',
       'mojaris_women', 'leggings_and_salwars', 'none'],
      dtype='object')

In [433]:
dfpa = df_none[df_none.class_label == 'palazzos']
dfpa.shape

(210, 24)

In [434]:
dfpa.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
5500,5500,N/A,images/val/5500.jpg,N/A,N/A,palazzos,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5501,5501,https://rukminim1.flixcart.com/image/309/371/k...,images/val/5501.jpeg,labellzstylerz,Regular Fit Women White Rayon Trousers,palazzos,N/A,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5505,5505,N/A,images/val/5505.jpg,N/A,N/A,palazzos,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5508,5508,N/A,images/val/5508.jpg,N/A,N/A,palazzos,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5509,5509,https://rukminim1.flixcart.com/image/309/371/j...,images/val/5509.jpeg,Kannan,Regular Fit Women Multicolor Poly Crepe Trousers,palazzos,N/A,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [435]:
dfpa.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
5984,5984,https://assets0.mirraw.com/images/6490079/AP-3...,images/val/5984.jpg,Mirraw,Black Color Plain Lace Plazo,palazzos,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5988,5988,https://img6.craftsvilla.com/image/upload/w_30...,images/val/5988.jpg,Craftsvilla,Clora Mustard ...,palazzos,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5993,5993,https://rukminim1.flixcart.com/image/309/371/k...,images/val/5993.jpeg,kuriff,Regular Fit Women Black Rayon Trousers,palazzos,N/A,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5996,5996,N/A,images/val/5996.jpg,N/A,N/A,palazzos,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
5999,5999,https://rukminim1.flixcart.com/image/309/371/k...,images/val/5999.jpeg,TRIFON,Regular Fit Women White Pure Cotton Trousers,palazzos,N/A,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [436]:
c1 = (dfr.class_label == 'palazzos')
c2 = (dfr.none == 1)

dfr.loc[c1 & c2, 'palazzos'] = 1
dfr.loc[c1 & c2, 'none'] = 0

In [437]:
dfd = df_none[df_none.class_label == 'dhoti_pants']
dfd.shape

(49, 24)

In [438]:
dfd.head()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
1027,1027,https://m.media-amazon.com/images/I/41TIdoMFde...,images/val/1027.jpeg,BOMBSHELL,Stylish Women's Solid/Plain Satin Shirt & Pyja...,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1040,1040,https://m.media-amazon.com/images/I/71xZgJA0G5...,images/val/1040.jpeg,Aks,Women's Cotton Trouser Suit,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1058,1058,https://m.media-amazon.com/images/I/71GkvrScZ9...,images/val/1058.jpeg,BHARATASYA,Brown Block Printed Cotton Slub Short Kurta,dhoti_pants,NaN,True,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1070,1070,https://m.media-amazon.com/images/I/61EDS0KVFt...,images/val/1070.jpeg,Glampunch,Women's Exclusive Yellow Solid Ruffle Top for ...,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1077,1077,https://m.media-amazon.com/images/I/81NWU3gf-Y...,images/val/1077.jpeg,Aurelia,Women's Straight Fit Pants,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [439]:
dfd.tail()

,number,image_url,image_path,brand,product_title,class_label,color,kurta,dhoti_pants,saree,...,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars,none
1467,1467,https://m.media-amazon.com/images/I/71pa69GiqO...,images/val/1467.jpeg,YuvikaStore,L-40 Women's Hand Embroidered Lucknow Chikanka...,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1469,1469,https://m.media-amazon.com/images/I/61hHU0DsT8...,images/val/1469.jpeg,The Magic Wand,Sequined Velvet Crop Top with Pants Combo Set ...,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1475,1475,https://m.media-amazon.com/images/I/61Fjf+Gghr...,images/val/1475.jpeg,Just Wow,Women's Pleat-Front Regular Pants,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1482,1482,https://m.media-amazon.com/images/I/81BafmFRmA...,images/val/1482.jpeg,papa ki pari,Girls Western Dresses Top & Floral Print Plazz...,dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0
1491,1491,https://m.media-amazon.com/images/I/71WeE0Uk33...,images/val/1491.jpeg,KANGLI,Girl's Pure Rayon Heavy Combo Kurti (Pack of 2),dhoti_pants,NaN,False,0,0,...,0,0,0,0,0,0,0,0,0,1.0

In [440]:
dfr.iloc[1061, 4]

'Fabrify Fashion Women Dhoti'

In [441]:
dp = dfd.index

In [442]:
dfr = dfr.drop(dp)

In [443]:
dfr.shape

(6744, 24)

In [444]:
dfr.to_csv('/Users/butler/Documents/springboard_bootcamp/Classification_of_Indian_clothing_images/data/interim/df_val_multilabel.csv')

In [445]:
dfr = dfr.drop(['number', 'image_url', 'brand', 'product_title',
       'class_label', 'color', 'kurta', 'none'], axis=1)

In [446]:
dfr.head()

,image_path,dhoti_pants,saree,sherwanis,palazzos,nehru_jackets,petticoats,blouse,dupattas,gowns,lehenga,women_kurta,kurta_men,mojaris_men,mojaris_women,leggings_and_salwars
0,images/val/0.jpeg,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
1,images/val/1.jpeg,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
2,images/val/2.jpeg,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
3,images/val/3.jpeg,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
4,images/val/4.jpeg,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [447]:
dfr.to_csv('/Users/butler/Documents/springboard_bootcamp/Classification_of_Indian_clothing_images/data/interim/val_one_hot.csv')